package com.zhela.cloudblog.dao.intenalnews;

import com.zhela.cloudblog.model.intenalnews.VideoNews;
import com.zhela.cloudblog.model.intenalnews.VideoNewsExample;
import java.util.List;

public interface VideoNewsDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table video_news
     *
     * @ibatorgenerated Fri Oct 22 23:22:19 CST 2010
     */
    int countByExample(VideoNewsExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table video_news
     *
     * @ibatorgenerated Fri Oct 22 23:22:19 CST 2010
     */
    int deleteByExample(VideoNewsExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table video_news
     *
     * @ibatorgenerated Fri Oct 22 23:22:19 CST 2010
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table video_news
     *
     * @ibatorgenerated Fri Oct 22 23:22:19 CST 2010
     */
    void insert(VideoNews record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table video_news
     *
     * @ibatorgenerated Fri Oct 22 23:22:19 CST 2010
     */
    void insertSelective(VideoNews record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table video_news
     *
     * @ibatorgenerated Fri Oct 22 23:22:19 CST 2010
     */
    List<VideoNews> selectByExampleWithBLOBs(VideoNewsExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table video_news
     *
     * @ibatorgenerated Fri Oct 22 23:22:19 CST 2010
     */
    List<VideoNews> selectByExampleWithoutBLOBs(VideoNewsExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table video_news
     *
     * @ibatorgenerated Fri Oct 22 23:22:19 CST 2010
     */
    VideoNews selectByPrimaryKey(Long id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table video_news
     *
     * @ibatorgenerated Fri Oct 22 23:22:19 CST 2010
     */
    int updateByExampleSelective(VideoNews record, VideoNewsExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table video_news
     *
     * @ibatorgenerated Fri Oct 22 23:22:19 CST 2010
     */
    int updateByExampleWithBLOBs(VideoNews record, VideoNewsExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table video_news
     *
     * @ibatorgenerated Fri Oct 22 23:22:19 CST 2010
     */
    int updateByExampleWithoutBLOBs(VideoNews record, VideoNewsExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table video_news
     *
     * @ibatorgenerated Fri Oct 22 23:22:19 CST 2010
     */
    int updateByPrimaryKeySelective(VideoNews record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table video_news
     *
     * @ibatorgenerated Fri Oct 22 23:22:19 CST 2010
     */
    int updateByPrimaryKeyWithBLOBs(VideoNews record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table video_news
     *
     * @ibatorgenerated Fri Oct 22 23:22:19 CST 2010
     */
    int updateByPrimaryKeyWithoutBLOBs(VideoNews record);
}