package com.zhela.cloudblog.dao.device.impl;

import com.zhela.cloudblog.dao.device.DeviceLogDAO;
import com.zhela.cloudblog.model.device.DeviceLog;
import com.zhela.cloudblog.model.device.DeviceLogExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class DeviceLogDAOImpl extends SqlMapClientDaoSupport implements DeviceLogDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table device_log
     *
     * @ibatorgenerated Sat Oct 23 14:28:50 CST 2010
     */
    public DeviceLogDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table device_log
     *
     * @ibatorgenerated Sat Oct 23 14:28:50 CST 2010
     */
    public int countByExample(DeviceLogExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("device_log.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table device_log
     *
     * @ibatorgenerated Sat Oct 23 14:28:50 CST 2010
     */
    public int deleteByExample(DeviceLogExample example) {
        int rows = getSqlMapClientTemplate().delete("device_log.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table device_log
     *
     * @ibatorgenerated Sat Oct 23 14:28:50 CST 2010
     */
    public int deleteByPrimaryKey(Long id) {
        DeviceLog key = new DeviceLog();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("device_log.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table device_log
     *
     * @ibatorgenerated Sat Oct 23 14:28:50 CST 2010
     */
    public void insert(DeviceLog record) {
        getSqlMapClientTemplate().insert("device_log.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table device_log
     *
     * @ibatorgenerated Sat Oct 23 14:28:50 CST 2010
     */
    public void insertSelective(DeviceLog record) {
        getSqlMapClientTemplate().insert("device_log.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table device_log
     *
     * @ibatorgenerated Sat Oct 23 14:28:50 CST 2010
     */
    @SuppressWarnings("unchecked")
    public List<DeviceLog> selectByExample(DeviceLogExample example) {
        List<DeviceLog> list = getSqlMapClientTemplate().queryForList("device_log.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table device_log
     *
     * @ibatorgenerated Sat Oct 23 14:28:50 CST 2010
     */
    public DeviceLog selectByPrimaryKey(Long id) {
        DeviceLog key = new DeviceLog();
        key.setId(id);
        DeviceLog record = (DeviceLog) getSqlMapClientTemplate().queryForObject("device_log.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table device_log
     *
     * @ibatorgenerated Sat Oct 23 14:28:50 CST 2010
     */
    public int updateByExampleSelective(DeviceLog record, DeviceLogExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("device_log.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table device_log
     *
     * @ibatorgenerated Sat Oct 23 14:28:50 CST 2010
     */
    public int updateByExample(DeviceLog record, DeviceLogExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("device_log.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table device_log
     *
     * @ibatorgenerated Sat Oct 23 14:28:50 CST 2010
     */
    public int updateByPrimaryKeySelective(DeviceLog record) {
        int rows = getSqlMapClientTemplate().update("device_log.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table device_log
     *
     * @ibatorgenerated Sat Oct 23 14:28:50 CST 2010
     */
    public int updateByPrimaryKey(DeviceLog record) {
        int rows = getSqlMapClientTemplate().update("device_log.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table device_log
     *
     * @ibatorgenerated Sat Oct 23 14:28:50 CST 2010
     */
    private static class UpdateByExampleParms extends DeviceLogExample {
        private Object record;

        public UpdateByExampleParms(Object record, DeviceLogExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}