package com.zhela.cloudblog.model.ourservice;

import java.util.Date;

public class Comment {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column comment.id
     *
     * @ibatorgenerated Mon Nov 29 14:02:02 CST 2010
     */
    private Long id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column comment.service_bind_code
     *
     * @ibatorgenerated Mon Nov 29 14:02:02 CST 2010
     */
    private String serviceBindCode;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column comment.web_url
     *
     * @ibatorgenerated Mon Nov 29 14:02:02 CST 2010
     */
    private String webUrl;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column comment.user_ip
     *
     * @ibatorgenerated Mon Nov 29 14:02:02 CST 2010
     */
    private String userIp;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column comment.user_name
     *
     * @ibatorgenerated Mon Nov 29 14:02:02 CST 2010
     */
    private String userName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column comment.user_header
     *
     * @ibatorgenerated Mon Nov 29 14:02:02 CST 2010
     */
    private String userHeader;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column comment.update_time
     *
     * @ibatorgenerated Mon Nov 29 14:02:02 CST 2010
     */
    private Date updateTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column comment.content
     *
     * @ibatorgenerated Mon Nov 29 14:02:02 CST 2010
     */
    private String content;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column comment.id
     *
     * @return the value of comment.id
     *
     * @ibatorgenerated Mon Nov 29 14:02:02 CST 2010
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column comment.id
     *
     * @param id the value for comment.id
     *
     * @ibatorgenerated Mon Nov 29 14:02:02 CST 2010
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column comment.service_bind_code
     *
     * @return the value of comment.service_bind_code
     *
     * @ibatorgenerated Mon Nov 29 14:02:02 CST 2010
     */
    public String getServiceBindCode() {
        return serviceBindCode;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column comment.service_bind_code
     *
     * @param serviceBindCode the value for comment.service_bind_code
     *
     * @ibatorgenerated Mon Nov 29 14:02:02 CST 2010
     */
    public void setServiceBindCode(String serviceBindCode) {
        this.serviceBindCode = serviceBindCode;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column comment.web_url
     *
     * @return the value of comment.web_url
     *
     * @ibatorgenerated Mon Nov 29 14:02:02 CST 2010
     */
    public String getWebUrl() {
        return webUrl;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column comment.web_url
     *
     * @param webUrl the value for comment.web_url
     *
     * @ibatorgenerated Mon Nov 29 14:02:02 CST 2010
     */
    public void setWebUrl(String webUrl) {
        this.webUrl = webUrl;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column comment.user_ip
     *
     * @return the value of comment.user_ip
     *
     * @ibatorgenerated Mon Nov 29 14:02:02 CST 2010
     */
    public String getUserIp() {
        return userIp;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column comment.user_ip
     *
     * @param userIp the value for comment.user_ip
     *
     * @ibatorgenerated Mon Nov 29 14:02:02 CST 2010
     */
    public void setUserIp(String userIp) {
        this.userIp = userIp;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column comment.user_name
     *
     * @return the value of comment.user_name
     *
     * @ibatorgenerated Mon Nov 29 14:02:02 CST 2010
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column comment.user_name
     *
     * @param userName the value for comment.user_name
     *
     * @ibatorgenerated Mon Nov 29 14:02:02 CST 2010
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column comment.user_header
     *
     * @return the value of comment.user_header
     *
     * @ibatorgenerated Mon Nov 29 14:02:02 CST 2010
     */
    public String getUserHeader() {
        return userHeader;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column comment.user_header
     *
     * @param userHeader the value for comment.user_header
     *
     * @ibatorgenerated Mon Nov 29 14:02:02 CST 2010
     */
    public void setUserHeader(String userHeader) {
        this.userHeader = userHeader;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column comment.update_time
     *
     * @return the value of comment.update_time
     *
     * @ibatorgenerated Mon Nov 29 14:02:02 CST 2010
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column comment.update_time
     *
     * @param updateTime the value for comment.update_time
     *
     * @ibatorgenerated Mon Nov 29 14:02:02 CST 2010
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column comment.content
     *
     * @return the value of comment.content
     *
     * @ibatorgenerated Mon Nov 29 14:02:02 CST 2010
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column comment.content
     *
     * @param content the value for comment.content
     *
     * @ibatorgenerated Mon Nov 29 14:02:02 CST 2010
     */
    public void setContent(String content) {
        this.content = content;
    }
}