package com.twitpic.db.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class PicturesParameterExample {

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database table pictures_parameter
	 * @abatorgenerated  Thu Aug 27 22:34:53 CST 2009
	 */
	protected String orderByClause;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database table pictures_parameter
	 * @abatorgenerated  Thu Aug 27 22:34:53 CST 2009
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table pictures_parameter
	 * @abatorgenerated  Thu Aug 27 22:34:53 CST 2009
	 */
	public PicturesParameterExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table pictures_parameter
	 * @abatorgenerated  Thu Aug 27 22:34:53 CST 2009
	 */
	protected PicturesParameterExample(PicturesParameterExample example) {
		this.orderByClause = example.orderByClause;
		this.oredCriteria = example.oredCriteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table pictures_parameter
	 * @abatorgenerated  Thu Aug 27 22:34:53 CST 2009
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table pictures_parameter
	 * @abatorgenerated  Thu Aug 27 22:34:53 CST 2009
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table pictures_parameter
	 * @abatorgenerated  Thu Aug 27 22:34:53 CST 2009
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table pictures_parameter
	 * @abatorgenerated  Thu Aug 27 22:34:53 CST 2009
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table pictures_parameter
	 * @abatorgenerated  Thu Aug 27 22:34:53 CST 2009
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table pictures_parameter
	 * @abatorgenerated  Thu Aug 27 22:34:53 CST 2009
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table pictures_parameter
	 * @abatorgenerated  Thu Aug 27 22:34:53 CST 2009
	 */
	public void clear() {
		oredCriteria.clear();
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table pictures_parameter
	 * @abatorgenerated  Thu Aug 27 22:34:53 CST 2009
	 */
	public static class Criteria {
		protected List<String> criteriaWithoutValue;
		protected List<Map<String, Object>> criteriaWithSingleValue;
		protected List<Map<String, Object>> criteriaWithListValue;
		protected List<Map<String, Object>> criteriaWithBetweenValue;

		protected Criteria() {
			super();
			criteriaWithoutValue = new ArrayList<String>();
			criteriaWithSingleValue = new ArrayList<Map<String, Object>>();
			criteriaWithListValue = new ArrayList<Map<String, Object>>();
			criteriaWithBetweenValue = new ArrayList<Map<String, Object>>();
		}

		public boolean isValid() {
			return criteriaWithoutValue.size() > 0
					|| criteriaWithSingleValue.size() > 0
					|| criteriaWithListValue.size() > 0
					|| criteriaWithBetweenValue.size() > 0;
		}

		public List<String> getCriteriaWithoutValue() {
			return criteriaWithoutValue;
		}

		public List<Map<String, Object>> getCriteriaWithSingleValue() {
			return criteriaWithSingleValue;
		}

		public List<Map<String, Object>> getCriteriaWithListValue() {
			return criteriaWithListValue;
		}

		public List<Map<String, Object>> getCriteriaWithBetweenValue() {
			return criteriaWithBetweenValue;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteriaWithoutValue.add(condition);
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			Map<String, Object> map = new HashMap<String, Object>();
			map.put("condition", condition);
			map.put("value", value);
			criteriaWithSingleValue.add(map);
		}

		protected void addCriterion(String condition,
				List<? extends Object> values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property
						+ " cannot be null or empty");
			}
			Map<String, Object> map = new HashMap<String, Object>();
			map.put("condition", condition);
			map.put("values", values);
			criteriaWithListValue.add(map);
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			List<Object> list = new ArrayList<Object>();
			list.add(value1);
			list.add(value2);
			Map<String, Object> map = new HashMap<String, Object>();
			map.put("condition", condition);
			map.put("values", list);
			criteriaWithBetweenValue.add(map);
		}

		public Criteria andIdPicturesIsNull() {
			addCriterion("id_pictures is null");
			return this;
		}

		public Criteria andIdPicturesIsNotNull() {
			addCriterion("id_pictures is not null");
			return this;
		}

		public Criteria andIdPicturesEqualTo(Long value) {
			addCriterion("id_pictures =", value, "idPictures");
			return this;
		}

		public Criteria andIdPicturesNotEqualTo(Long value) {
			addCriterion("id_pictures <>", value, "idPictures");
			return this;
		}

		public Criteria andIdPicturesGreaterThan(Long value) {
			addCriterion("id_pictures >", value, "idPictures");
			return this;
		}

		public Criteria andIdPicturesGreaterThanOrEqualTo(Long value) {
			addCriterion("id_pictures >=", value, "idPictures");
			return this;
		}

		public Criteria andIdPicturesLessThan(Long value) {
			addCriterion("id_pictures <", value, "idPictures");
			return this;
		}

		public Criteria andIdPicturesLessThanOrEqualTo(Long value) {
			addCriterion("id_pictures <=", value, "idPictures");
			return this;
		}

		public Criteria andIdPicturesIn(List<Long> values) {
			addCriterion("id_pictures in", values, "idPictures");
			return this;
		}

		public Criteria andIdPicturesNotIn(List<Long> values) {
			addCriterion("id_pictures not in", values, "idPictures");
			return this;
		}

		public Criteria andIdPicturesBetween(Long value1, Long value2) {
			addCriterion("id_pictures between", value1, value2, "idPictures");
			return this;
		}

		public Criteria andIdPicturesNotBetween(Long value1, Long value2) {
			addCriterion("id_pictures not between", value1, value2,
					"idPictures");
			return this;
		}

		public Criteria andUploadAccountIsNull() {
			addCriterion("upload_account is null");
			return this;
		}

		public Criteria andUploadAccountIsNotNull() {
			addCriterion("upload_account is not null");
			return this;
		}

		public Criteria andUploadAccountEqualTo(String value) {
			addCriterion("upload_account =", value, "uploadAccount");
			return this;
		}

		public Criteria andUploadAccountNotEqualTo(String value) {
			addCriterion("upload_account <>", value, "uploadAccount");
			return this;
		}

		public Criteria andUploadAccountGreaterThan(String value) {
			addCriterion("upload_account >", value, "uploadAccount");
			return this;
		}

		public Criteria andUploadAccountGreaterThanOrEqualTo(String value) {
			addCriterion("upload_account >=", value, "uploadAccount");
			return this;
		}

		public Criteria andUploadAccountLessThan(String value) {
			addCriterion("upload_account <", value, "uploadAccount");
			return this;
		}

		public Criteria andUploadAccountLessThanOrEqualTo(String value) {
			addCriterion("upload_account <=", value, "uploadAccount");
			return this;
		}

		public Criteria andUploadAccountLike(String value) {
			addCriterion("upload_account like", value, "uploadAccount");
			return this;
		}

		public Criteria andUploadAccountNotLike(String value) {
			addCriterion("upload_account not like", value, "uploadAccount");
			return this;
		}

		public Criteria andUploadAccountIn(List<String> values) {
			addCriterion("upload_account in", values, "uploadAccount");
			return this;
		}

		public Criteria andUploadAccountNotIn(List<String> values) {
			addCriterion("upload_account not in", values, "uploadAccount");
			return this;
		}

		public Criteria andUploadAccountBetween(String value1, String value2) {
			addCriterion("upload_account between", value1, value2,
					"uploadAccount");
			return this;
		}

		public Criteria andUploadAccountNotBetween(String value1, String value2) {
			addCriterion("upload_account not between", value1, value2,
					"uploadAccount");
			return this;
		}

		public Criteria andUploadTimeIsNull() {
			addCriterion("upload_time is null");
			return this;
		}

		public Criteria andUploadTimeIsNotNull() {
			addCriterion("upload_time is not null");
			return this;
		}

		public Criteria andUploadTimeEqualTo(Date value) {
			addCriterion("upload_time =", value, "uploadTime");
			return this;
		}

		public Criteria andUploadTimeNotEqualTo(Date value) {
			addCriterion("upload_time <>", value, "uploadTime");
			return this;
		}

		public Criteria andUploadTimeGreaterThan(Date value) {
			addCriterion("upload_time >", value, "uploadTime");
			return this;
		}

		public Criteria andUploadTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("upload_time >=", value, "uploadTime");
			return this;
		}

		public Criteria andUploadTimeLessThan(Date value) {
			addCriterion("upload_time <", value, "uploadTime");
			return this;
		}

		public Criteria andUploadTimeLessThanOrEqualTo(Date value) {
			addCriterion("upload_time <=", value, "uploadTime");
			return this;
		}

		public Criteria andUploadTimeIn(List<Date> values) {
			addCriterion("upload_time in", values, "uploadTime");
			return this;
		}

		public Criteria andUploadTimeNotIn(List<Date> values) {
			addCriterion("upload_time not in", values, "uploadTime");
			return this;
		}

		public Criteria andUploadTimeBetween(Date value1, Date value2) {
			addCriterion("upload_time between", value1, value2, "uploadTime");
			return this;
		}

		public Criteria andUploadTimeNotBetween(Date value1, Date value2) {
			addCriterion("upload_time not between", value1, value2,
					"uploadTime");
			return this;
		}

		public Criteria andStatusIsNull() {
			addCriterion("status is null");
			return this;
		}

		public Criteria andStatusIsNotNull() {
			addCriterion("status is not null");
			return this;
		}

		public Criteria andStatusEqualTo(Integer value) {
			addCriterion("status =", value, "status");
			return this;
		}

		public Criteria andStatusNotEqualTo(Integer value) {
			addCriterion("status <>", value, "status");
			return this;
		}

		public Criteria andStatusGreaterThan(Integer value) {
			addCriterion("status >", value, "status");
			return this;
		}

		public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
			addCriterion("status >=", value, "status");
			return this;
		}

		public Criteria andStatusLessThan(Integer value) {
			addCriterion("status <", value, "status");
			return this;
		}

		public Criteria andStatusLessThanOrEqualTo(Integer value) {
			addCriterion("status <=", value, "status");
			return this;
		}

		public Criteria andStatusIn(List<Integer> values) {
			addCriterion("status in", values, "status");
			return this;
		}

		public Criteria andStatusNotIn(List<Integer> values) {
			addCriterion("status not in", values, "status");
			return this;
		}

		public Criteria andStatusBetween(Integer value1, Integer value2) {
			addCriterion("status between", value1, value2, "status");
			return this;
		}

		public Criteria andStatusNotBetween(Integer value1, Integer value2) {
			addCriterion("status not between", value1, value2, "status");
			return this;
		}

		public Criteria andDeviceIsNull() {
			addCriterion("device is null");
			return this;
		}

		public Criteria andDeviceIsNotNull() {
			addCriterion("device is not null");
			return this;
		}

		public Criteria andDeviceEqualTo(String value) {
			addCriterion("device =", value, "device");
			return this;
		}

		public Criteria andDeviceNotEqualTo(String value) {
			addCriterion("device <>", value, "device");
			return this;
		}

		public Criteria andDeviceGreaterThan(String value) {
			addCriterion("device >", value, "device");
			return this;
		}

		public Criteria andDeviceGreaterThanOrEqualTo(String value) {
			addCriterion("device >=", value, "device");
			return this;
		}

		public Criteria andDeviceLessThan(String value) {
			addCriterion("device <", value, "device");
			return this;
		}

		public Criteria andDeviceLessThanOrEqualTo(String value) {
			addCriterion("device <=", value, "device");
			return this;
		}

		public Criteria andDeviceLike(String value) {
			addCriterion("device like", value, "device");
			return this;
		}

		public Criteria andDeviceNotLike(String value) {
			addCriterion("device not like", value, "device");
			return this;
		}

		public Criteria andDeviceIn(List<String> values) {
			addCriterion("device in", values, "device");
			return this;
		}

		public Criteria andDeviceNotIn(List<String> values) {
			addCriterion("device not in", values, "device");
			return this;
		}

		public Criteria andDeviceBetween(String value1, String value2) {
			addCriterion("device between", value1, value2, "device");
			return this;
		}

		public Criteria andDeviceNotBetween(String value1, String value2) {
			addCriterion("device not between", value1, value2, "device");
			return this;
		}

		public Criteria andTitleIsNull() {
			addCriterion("title is null");
			return this;
		}

		public Criteria andTitleIsNotNull() {
			addCriterion("title is not null");
			return this;
		}

		public Criteria andTitleEqualTo(String value) {
			addCriterion("title =", value, "title");
			return this;
		}

		public Criteria andTitleNotEqualTo(String value) {
			addCriterion("title <>", value, "title");
			return this;
		}

		public Criteria andTitleGreaterThan(String value) {
			addCriterion("title >", value, "title");
			return this;
		}

		public Criteria andTitleGreaterThanOrEqualTo(String value) {
			addCriterion("title >=", value, "title");
			return this;
		}

		public Criteria andTitleLessThan(String value) {
			addCriterion("title <", value, "title");
			return this;
		}

		public Criteria andTitleLessThanOrEqualTo(String value) {
			addCriterion("title <=", value, "title");
			return this;
		}

		public Criteria andTitleLike(String value) {
			addCriterion("title like", value, "title");
			return this;
		}

		public Criteria andTitleNotLike(String value) {
			addCriterion("title not like", value, "title");
			return this;
		}

		public Criteria andTitleIn(List<String> values) {
			addCriterion("title in", values, "title");
			return this;
		}

		public Criteria andTitleNotIn(List<String> values) {
			addCriterion("title not in", values, "title");
			return this;
		}

		public Criteria andTitleBetween(String value1, String value2) {
			addCriterion("title between", value1, value2, "title");
			return this;
		}

		public Criteria andTitleNotBetween(String value1, String value2) {
			addCriterion("title not between", value1, value2, "title");
			return this;
		}

		public Criteria andDescriptionIsNull() {
			addCriterion("description is null");
			return this;
		}

		public Criteria andDescriptionIsNotNull() {
			addCriterion("description is not null");
			return this;
		}

		public Criteria andDescriptionEqualTo(String value) {
			addCriterion("description =", value, "description");
			return this;
		}

		public Criteria andDescriptionNotEqualTo(String value) {
			addCriterion("description <>", value, "description");
			return this;
		}

		public Criteria andDescriptionGreaterThan(String value) {
			addCriterion("description >", value, "description");
			return this;
		}

		public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
			addCriterion("description >=", value, "description");
			return this;
		}

		public Criteria andDescriptionLessThan(String value) {
			addCriterion("description <", value, "description");
			return this;
		}

		public Criteria andDescriptionLessThanOrEqualTo(String value) {
			addCriterion("description <=", value, "description");
			return this;
		}

		public Criteria andDescriptionLike(String value) {
			addCriterion("description like", value, "description");
			return this;
		}

		public Criteria andDescriptionNotLike(String value) {
			addCriterion("description not like", value, "description");
			return this;
		}

		public Criteria andDescriptionIn(List<String> values) {
			addCriterion("description in", values, "description");
			return this;
		}

		public Criteria andDescriptionNotIn(List<String> values) {
			addCriterion("description not in", values, "description");
			return this;
		}

		public Criteria andDescriptionBetween(String value1, String value2) {
			addCriterion("description between", value1, value2, "description");
			return this;
		}

		public Criteria andDescriptionNotBetween(String value1, String value2) {
			addCriterion("description not between", value1, value2,
					"description");
			return this;
		}
	}
}