package com.zhelazhela.db.dao;

import com.zhelazhela.db.model.DiscountNews;
import com.zhelazhela.db.model.DiscountNewsExample;
import java.util.List;

public interface DiscountNewsDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table discount_news
     *
     * @ibatorgenerated Fri Dec 18 16:20:44 CST 2009
     */
    int countByExample(DiscountNewsExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table discount_news
     *
     * @ibatorgenerated Fri Dec 18 16:20:44 CST 2009
     */
    int deleteByExample(DiscountNewsExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table discount_news
     *
     * @ibatorgenerated Fri Dec 18 16:20:44 CST 2009
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table discount_news
     *
     * @ibatorgenerated Fri Dec 18 16:20:44 CST 2009
     */
    void insert(DiscountNews record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table discount_news
     *
     * @ibatorgenerated Fri Dec 18 16:20:44 CST 2009
     */
    void insertSelective(DiscountNews record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table discount_news
     *
     * @ibatorgenerated Fri Dec 18 16:20:44 CST 2009
     */
    List<DiscountNews> selectByExampleWithBLOBs(DiscountNewsExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table discount_news
     *
     * @ibatorgenerated Fri Dec 18 16:20:44 CST 2009
     */
    List<DiscountNews> selectByExampleWithoutBLOBs(DiscountNewsExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table discount_news
     *
     * @ibatorgenerated Fri Dec 18 16:20:44 CST 2009
     */
    DiscountNews selectByPrimaryKey(Long id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table discount_news
     *
     * @ibatorgenerated Fri Dec 18 16:20:44 CST 2009
     */
    int updateByExampleSelective(DiscountNews record, DiscountNewsExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table discount_news
     *
     * @ibatorgenerated Fri Dec 18 16:20:44 CST 2009
     */
    int updateByExampleWithBLOBs(DiscountNews record, DiscountNewsExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table discount_news
     *
     * @ibatorgenerated Fri Dec 18 16:20:44 CST 2009
     */
    int updateByExampleWithoutBLOBs(DiscountNews record, DiscountNewsExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table discount_news
     *
     * @ibatorgenerated Fri Dec 18 16:20:44 CST 2009
     */
    int updateByPrimaryKeySelective(DiscountNews record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table discount_news
     *
     * @ibatorgenerated Fri Dec 18 16:20:44 CST 2009
     */
    int updateByPrimaryKeyWithBLOBs(DiscountNews record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table discount_news
     *
     * @ibatorgenerated Fri Dec 18 16:20:44 CST 2009
     */
    int updateByPrimaryKeyWithoutBLOBs(DiscountNews record);
    
    long insertSelectiveReturnId(DiscountNews record);
    
    List<DiscountNews> selectWithProgramInfoByExampleWithoutBLOBs(DiscountNewsExample example);
    
    DiscountNews selectWithProgramInfoByPrimaryKey(Long id);
    
    List<DiscountNews> selectWithPrgramInfoConditionAnd(String approve_user_condition,Boolean approve_result,String news_title,java.util.List<String> categorys,java.util.List<String> areas,String orderByClause,int page,int pageSize);
    
    int countWithPrgramInfoConditionAnd(String approve_user_condition,Boolean approve_result,String news_title,java.util.List<String> categorys,java.util.List<String> areas);
    
    List<DiscountNews> selectWithPrgramInfoConditionOr(String approve_user_condition,Boolean approve_result,String news_title,java.util.List<String> categorys,java.util.List<String> areas,String orderByClause,int page,int pageSize);
    
    int countWithPrgramInfoConditionOr(String approve_user_condition,Boolean approve_result,String news_title,java.util.List<String> categorys,java.util.List<String> areas);
}