package com.zhelazhela.db.dao;

import com.zhelazhela.db.model.GoodsComment;
import com.zhelazhela.db.model.GoodsCommentExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class GoodsCommentDAOImpl extends SqlMapClientDaoSupport implements GoodsCommentDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table goods_comment
	 * @ibatorgenerated  Mon Feb 15 01:04:29 CST 2010
	 */
	public GoodsCommentDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table goods_comment
	 * @ibatorgenerated  Mon Feb 15 01:04:29 CST 2010
	 */
	public int countByExample(GoodsCommentExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"goods_comment.ibatorgenerated_countByExample", example);
		return count;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table goods_comment
	 * @ibatorgenerated  Mon Feb 15 01:04:29 CST 2010
	 */
	public int deleteByExample(GoodsCommentExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"goods_comment.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table goods_comment
	 * @ibatorgenerated  Mon Feb 15 01:04:29 CST 2010
	 */
	public int deleteByPrimaryKey(Long id) {
		GoodsComment key = new GoodsComment();
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete(
				"goods_comment.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table goods_comment
	 * @ibatorgenerated  Mon Feb 15 01:04:29 CST 2010
	 */
	public void insert(GoodsComment record) {
		getSqlMapClientTemplate().insert(
				"goods_comment.ibatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table goods_comment
	 * @ibatorgenerated  Mon Feb 15 01:04:29 CST 2010
	 */
	public void insertSelective(GoodsComment record) {
		getSqlMapClientTemplate().insert(
				"goods_comment.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table goods_comment
	 * @ibatorgenerated  Mon Feb 15 01:04:29 CST 2010
	 */
	@SuppressWarnings("unchecked")
	public List<GoodsComment> selectByExample(GoodsCommentExample example) {
		List<GoodsComment> list = getSqlMapClientTemplate().queryForList(
				"goods_comment.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table goods_comment
	 * @ibatorgenerated  Mon Feb 15 01:04:29 CST 2010
	 */
	public GoodsComment selectByPrimaryKey(Long id) {
		GoodsComment key = new GoodsComment();
		key.setId(id);
		GoodsComment record = (GoodsComment) getSqlMapClientTemplate()
				.queryForObject(
						"goods_comment.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table goods_comment
	 * @ibatorgenerated  Mon Feb 15 01:04:29 CST 2010
	 */
	public int updateByExampleSelective(GoodsComment record,
			GoodsCommentExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate()
				.update(
						"goods_comment.ibatorgenerated_updateByExampleSelective",
						parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table goods_comment
	 * @ibatorgenerated  Mon Feb 15 01:04:29 CST 2010
	 */
	public int updateByExample(GoodsComment record, GoodsCommentExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"goods_comment.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table goods_comment
	 * @ibatorgenerated  Mon Feb 15 01:04:29 CST 2010
	 */
	public int updateByPrimaryKeySelective(GoodsComment record) {
		int rows = getSqlMapClientTemplate().update(
				"goods_comment.ibatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table goods_comment
	 * @ibatorgenerated  Mon Feb 15 01:04:29 CST 2010
	 */
	public int updateByPrimaryKey(GoodsComment record) {
		int rows = getSqlMapClientTemplate().update(
				"goods_comment.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table goods_comment
	 * @ibatorgenerated  Mon Feb 15 01:04:29 CST 2010
	 */
	private static class UpdateByExampleParms extends GoodsCommentExample {
		private Object record;

		public UpdateByExampleParms(Object record, GoodsCommentExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}