package com.zhelazhela.db.dao;

import com.zhelazhela.db.model.Grouper;
import com.zhelazhela.db.model.GrouperExample;
import java.util.List;

public interface GrouperDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table grouper
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    int countByExample(GrouperExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table grouper
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    int deleteByExample(GrouperExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table grouper
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table grouper
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    void insert(Grouper record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table grouper
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    void insertSelective(Grouper record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table grouper
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    List<Grouper> selectByExample(GrouperExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table grouper
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    Grouper selectByPrimaryKey(Long id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table grouper
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    int updateByExampleSelective(Grouper record, GrouperExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table grouper
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    int updateByExample(Grouper record, GrouperExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table grouper
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    int updateByPrimaryKeySelective(Grouper record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table grouper
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    int updateByPrimaryKey(Grouper record);
}