package com.zhelazhela.db.dao;

import com.zhelazhela.db.model.InboxMessage;
import com.zhelazhela.db.model.InboxMessageExample;
import java.util.List;

public interface InboxMessageDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table inbox_message
     *
     * @ibatorgenerated Fri Feb 12 23:38:36 CST 2010
     */
    int countByExample(InboxMessageExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table inbox_message
     *
     * @ibatorgenerated Fri Feb 12 23:38:36 CST 2010
     */
    int deleteByExample(InboxMessageExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table inbox_message
     *
     * @ibatorgenerated Fri Feb 12 23:38:36 CST 2010
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table inbox_message
     *
     * @ibatorgenerated Fri Feb 12 23:38:36 CST 2010
     */
    void insert(InboxMessage record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table inbox_message
     *
     * @ibatorgenerated Fri Feb 12 23:38:36 CST 2010
     */
    void insertSelective(InboxMessage record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table inbox_message
     *
     * @ibatorgenerated Fri Feb 12 23:38:36 CST 2010
     */
    List<InboxMessage> selectByExample(InboxMessageExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table inbox_message
     *
     * @ibatorgenerated Fri Feb 12 23:38:36 CST 2010
     */
    InboxMessage selectByPrimaryKey(Long id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table inbox_message
     *
     * @ibatorgenerated Fri Feb 12 23:38:36 CST 2010
     */
    int updateByExampleSelective(InboxMessage record, InboxMessageExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table inbox_message
     *
     * @ibatorgenerated Fri Feb 12 23:38:36 CST 2010
     */
    int updateByExample(InboxMessage record, InboxMessageExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table inbox_message
     *
     * @ibatorgenerated Fri Feb 12 23:38:36 CST 2010
     */
    int updateByPrimaryKeySelective(InboxMessage record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table inbox_message
     *
     * @ibatorgenerated Fri Feb 12 23:38:36 CST 2010
     */
    int updateByPrimaryKey(InboxMessage record);
}