package com.zhelazhela.db.dao;

import com.zhelazhela.db.model.ManageUser;
import com.zhelazhela.db.model.ManageUserExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class ManageUserDAOImpl extends SqlMapClientDaoSupport implements ManageUserDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table manage_user
	 * @ibatorgenerated  Sat Dec 19 11:24:05 CST 2009
	 */
	public ManageUserDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table manage_user
	 * @ibatorgenerated  Sat Dec 19 11:24:05 CST 2009
	 */
	public int countByExample(ManageUserExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"manage_user.ibatorgenerated_countByExample", example);
		return count;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table manage_user
	 * @ibatorgenerated  Sat Dec 19 11:24:05 CST 2009
	 */
	public int deleteByExample(ManageUserExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"manage_user.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table manage_user
	 * @ibatorgenerated  Sat Dec 19 11:24:05 CST 2009
	 */
	public int deleteByPrimaryKey(String account) {
		ManageUser key = new ManageUser();
		key.setAccount(account);
		int rows = getSqlMapClientTemplate().delete(
				"manage_user.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table manage_user
	 * @ibatorgenerated  Sat Dec 19 11:24:05 CST 2009
	 */
	public void insert(ManageUser record) {
		getSqlMapClientTemplate().insert("manage_user.ibatorgenerated_insert",
				record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table manage_user
	 * @ibatorgenerated  Sat Dec 19 11:24:05 CST 2009
	 */
	public void insertSelective(ManageUser record) {
		getSqlMapClientTemplate().insert(
				"manage_user.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table manage_user
	 * @ibatorgenerated  Sat Dec 19 11:24:05 CST 2009
	 */
	@SuppressWarnings("unchecked")
	public List<ManageUser> selectByExample(ManageUserExample example) {
		List<ManageUser> list = getSqlMapClientTemplate().queryForList(
				"manage_user.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table manage_user
	 * @ibatorgenerated  Sat Dec 19 11:24:05 CST 2009
	 */
	public ManageUser selectByPrimaryKey(String account) {
		ManageUser key = new ManageUser();
		key.setAccount(account);
		ManageUser record = (ManageUser) getSqlMapClientTemplate()
				.queryForObject(
						"manage_user.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table manage_user
	 * @ibatorgenerated  Sat Dec 19 11:24:05 CST 2009
	 */
	public int updateByExampleSelective(ManageUser record,
			ManageUserExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"manage_user.ibatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table manage_user
	 * @ibatorgenerated  Sat Dec 19 11:24:05 CST 2009
	 */
	public int updateByExample(ManageUser record, ManageUserExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"manage_user.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table manage_user
	 * @ibatorgenerated  Sat Dec 19 11:24:05 CST 2009
	 */
	public int updateByPrimaryKeySelective(ManageUser record) {
		int rows = getSqlMapClientTemplate().update(
				"manage_user.ibatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table manage_user
	 * @ibatorgenerated  Sat Dec 19 11:24:05 CST 2009
	 */
	public int updateByPrimaryKey(ManageUser record) {
		int rows = getSqlMapClientTemplate().update(
				"manage_user.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table manage_user
	 * @ibatorgenerated  Sat Dec 19 11:24:05 CST 2009
	 */
	private static class UpdateByExampleParms extends ManageUserExample {
		private Object record;

		public UpdateByExampleParms(Object record, ManageUserExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}