package com.zhelazhela.db.dao;

import com.zhelazhela.db.model.OutboxMessage;
import com.zhelazhela.db.model.OutboxMessageExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class OutboxMessageDAOImpl extends SqlMapClientDaoSupport implements OutboxMessageDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table outbox_message
     *
     * @ibatorgenerated Fri Feb 12 23:38:36 CST 2010
     */
    public OutboxMessageDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table outbox_message
     *
     * @ibatorgenerated Fri Feb 12 23:38:36 CST 2010
     */
    public int countByExample(OutboxMessageExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("outbox_message.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table outbox_message
     *
     * @ibatorgenerated Fri Feb 12 23:38:36 CST 2010
     */
    public int deleteByExample(OutboxMessageExample example) {
        int rows = getSqlMapClientTemplate().delete("outbox_message.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table outbox_message
     *
     * @ibatorgenerated Fri Feb 12 23:38:36 CST 2010
     */
    public int deleteByPrimaryKey(Long id) {
        OutboxMessage key = new OutboxMessage();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("outbox_message.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table outbox_message
     *
     * @ibatorgenerated Fri Feb 12 23:38:36 CST 2010
     */
    public void insert(OutboxMessage record) {
        getSqlMapClientTemplate().insert("outbox_message.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table outbox_message
     *
     * @ibatorgenerated Fri Feb 12 23:38:36 CST 2010
     */
    public void insertSelective(OutboxMessage record) {
        getSqlMapClientTemplate().insert("outbox_message.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table outbox_message
     *
     * @ibatorgenerated Fri Feb 12 23:38:36 CST 2010
     */
    @SuppressWarnings("unchecked")
    public List<OutboxMessage> selectByExample(OutboxMessageExample example) {
        List<OutboxMessage> list = getSqlMapClientTemplate().queryForList("outbox_message.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table outbox_message
     *
     * @ibatorgenerated Fri Feb 12 23:38:36 CST 2010
     */
    public OutboxMessage selectByPrimaryKey(Long id) {
        OutboxMessage key = new OutboxMessage();
        key.setId(id);
        OutboxMessage record = (OutboxMessage) getSqlMapClientTemplate().queryForObject("outbox_message.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table outbox_message
     *
     * @ibatorgenerated Fri Feb 12 23:38:36 CST 2010
     */
    public int updateByExampleSelective(OutboxMessage record, OutboxMessageExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("outbox_message.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table outbox_message
     *
     * @ibatorgenerated Fri Feb 12 23:38:36 CST 2010
     */
    public int updateByExample(OutboxMessage record, OutboxMessageExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("outbox_message.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table outbox_message
     *
     * @ibatorgenerated Fri Feb 12 23:38:36 CST 2010
     */
    public int updateByPrimaryKeySelective(OutboxMessage record) {
        int rows = getSqlMapClientTemplate().update("outbox_message.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table outbox_message
     *
     * @ibatorgenerated Fri Feb 12 23:38:36 CST 2010
     */
    public int updateByPrimaryKey(OutboxMessage record) {
        int rows = getSqlMapClientTemplate().update("outbox_message.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table outbox_message
     *
     * @ibatorgenerated Fri Feb 12 23:38:36 CST 2010
     */
    private static class UpdateByExampleParms extends OutboxMessageExample {
        private Object record;

        public UpdateByExampleParms(Object record, OutboxMessageExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}