package com.zhelazhela.db.dao;

import com.zhelazhela.db.model.SecurityQuestion;
import com.zhelazhela.db.model.SecurityQuestionExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class SecurityQuestionDAOImpl extends SqlMapClientDaoSupport implements SecurityQuestionDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table security_question
     *
     * @ibatorgenerated Fri Feb 12 23:38:36 CST 2010
     */
    public SecurityQuestionDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table security_question
     *
     * @ibatorgenerated Fri Feb 12 23:38:36 CST 2010
     */
    public int countByExample(SecurityQuestionExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("security_question.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table security_question
     *
     * @ibatorgenerated Fri Feb 12 23:38:36 CST 2010
     */
    public int deleteByExample(SecurityQuestionExample example) {
        int rows = getSqlMapClientTemplate().delete("security_question.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table security_question
     *
     * @ibatorgenerated Fri Feb 12 23:38:36 CST 2010
     */
    public int deleteByPrimaryKey(Long id) {
        SecurityQuestion key = new SecurityQuestion();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("security_question.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table security_question
     *
     * @ibatorgenerated Fri Feb 12 23:38:36 CST 2010
     */
    public void insert(SecurityQuestion record) {
        getSqlMapClientTemplate().insert("security_question.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table security_question
     *
     * @ibatorgenerated Fri Feb 12 23:38:36 CST 2010
     */
    public void insertSelective(SecurityQuestion record) {
        getSqlMapClientTemplate().insert("security_question.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table security_question
     *
     * @ibatorgenerated Fri Feb 12 23:38:36 CST 2010
     */
    @SuppressWarnings("unchecked")
    public List<SecurityQuestion> selectByExample(SecurityQuestionExample example) {
        List<SecurityQuestion> list = getSqlMapClientTemplate().queryForList("security_question.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table security_question
     *
     * @ibatorgenerated Fri Feb 12 23:38:36 CST 2010
     */
    public SecurityQuestion selectByPrimaryKey(Long id) {
        SecurityQuestion key = new SecurityQuestion();
        key.setId(id);
        SecurityQuestion record = (SecurityQuestion) getSqlMapClientTemplate().queryForObject("security_question.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table security_question
     *
     * @ibatorgenerated Fri Feb 12 23:38:36 CST 2010
     */
    public int updateByExampleSelective(SecurityQuestion record, SecurityQuestionExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("security_question.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table security_question
     *
     * @ibatorgenerated Fri Feb 12 23:38:36 CST 2010
     */
    public int updateByExample(SecurityQuestion record, SecurityQuestionExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("security_question.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table security_question
     *
     * @ibatorgenerated Fri Feb 12 23:38:36 CST 2010
     */
    public int updateByPrimaryKeySelective(SecurityQuestion record) {
        int rows = getSqlMapClientTemplate().update("security_question.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table security_question
     *
     * @ibatorgenerated Fri Feb 12 23:38:36 CST 2010
     */
    public int updateByPrimaryKey(SecurityQuestion record) {
        int rows = getSqlMapClientTemplate().update("security_question.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table security_question
     *
     * @ibatorgenerated Fri Feb 12 23:38:36 CST 2010
     */
    private static class UpdateByExampleParms extends SecurityQuestionExample {
        private Object record;

        public UpdateByExampleParms(Object record, SecurityQuestionExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}