package com.zhelazhela.db.dao;

import com.zhelazhela.db.model.UserCertification;
import com.zhelazhela.db.model.UserCertificationExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class UserCertificationDAOImpl extends SqlMapClientDaoSupport implements UserCertificationDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user_certification
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    public UserCertificationDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user_certification
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    public int countByExample(UserCertificationExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("user_certification.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user_certification
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    public int deleteByExample(UserCertificationExample example) {
        int rows = getSqlMapClientTemplate().delete("user_certification.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user_certification
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    public int deleteByPrimaryKey(Long id) {
        UserCertification key = new UserCertification();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("user_certification.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user_certification
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    public void insert(UserCertification record) {
        getSqlMapClientTemplate().insert("user_certification.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user_certification
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    public void insertSelective(UserCertification record) {
        getSqlMapClientTemplate().insert("user_certification.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user_certification
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    @SuppressWarnings("unchecked")
    public List<UserCertification> selectByExample(UserCertificationExample example) {
        List<UserCertification> list = getSqlMapClientTemplate().queryForList("user_certification.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user_certification
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    public UserCertification selectByPrimaryKey(Long id) {
        UserCertification key = new UserCertification();
        key.setId(id);
        UserCertification record = (UserCertification) getSqlMapClientTemplate().queryForObject("user_certification.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user_certification
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    public int updateByExampleSelective(UserCertification record, UserCertificationExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("user_certification.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user_certification
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    public int updateByExample(UserCertification record, UserCertificationExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("user_certification.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user_certification
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    public int updateByPrimaryKeySelective(UserCertification record) {
        int rows = getSqlMapClientTemplate().update("user_certification.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user_certification
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    public int updateByPrimaryKey(UserCertification record) {
        int rows = getSqlMapClientTemplate().update("user_certification.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table user_certification
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    private static class UpdateByExampleParms extends UserCertificationExample {
        private Object record;

        public UpdateByExampleParms(Object record, UserCertificationExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}