package com.zhela.cloudblog.dao.users.impl;

import com.zhela.cloudblog.dao.users.UsersDAO;
import com.zhela.cloudblog.model.users.Users;
import com.zhela.cloudblog.model.users.UsersExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class UsersDAOImpl extends SqlMapClientDaoSupport implements UsersDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table users
     *
     * @ibatorgenerated Sun Oct 24 10:00:06 CST 2010
     */
    public UsersDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table users
     *
     * @ibatorgenerated Sun Oct 24 10:00:06 CST 2010
     */
    public int countByExample(UsersExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("users.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table users
     *
     * @ibatorgenerated Sun Oct 24 10:00:06 CST 2010
     */
    public int deleteByExample(UsersExample example) {
        int rows = getSqlMapClientTemplate().delete("users.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table users
     *
     * @ibatorgenerated Sun Oct 24 10:00:06 CST 2010
     */
    public int deleteByPrimaryKey(String account) {
        Users key = new Users();
        key.setAccount(account);
        int rows = getSqlMapClientTemplate().delete("users.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table users
     *
     * @ibatorgenerated Sun Oct 24 10:00:06 CST 2010
     */
    public void insert(Users record) {
        getSqlMapClientTemplate().insert("users.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table users
     *
     * @ibatorgenerated Sun Oct 24 10:00:06 CST 2010
     */
    public void insertSelective(Users record) {
        getSqlMapClientTemplate().insert("users.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table users
     *
     * @ibatorgenerated Sun Oct 24 10:00:06 CST 2010
     */
    @SuppressWarnings("unchecked")
    public List<Users> selectByExample(UsersExample example) {
        List<Users> list = getSqlMapClientTemplate().queryForList("users.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table users
     *
     * @ibatorgenerated Sun Oct 24 10:00:06 CST 2010
     */
    public Users selectByPrimaryKey(String account) {
        Users key = new Users();
        key.setAccount(account);
        Users record = (Users) getSqlMapClientTemplate().queryForObject("users.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table users
     *
     * @ibatorgenerated Sun Oct 24 10:00:06 CST 2010
     */
    public int updateByExampleSelective(Users record, UsersExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("users.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table users
     *
     * @ibatorgenerated Sun Oct 24 10:00:06 CST 2010
     */
    public int updateByExample(Users record, UsersExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("users.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table users
     *
     * @ibatorgenerated Sun Oct 24 10:00:06 CST 2010
     */
    public int updateByPrimaryKeySelective(Users record) {
        int rows = getSqlMapClientTemplate().update("users.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table users
     *
     * @ibatorgenerated Sun Oct 24 10:00:06 CST 2010
     */
    public int updateByPrimaryKey(Users record) {
        int rows = getSqlMapClientTemplate().update("users.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table users
     *
     * @ibatorgenerated Sun Oct 24 10:00:06 CST 2010
     */
    private static class UpdateByExampleParms extends UsersExample {
        private Object record;

        public UpdateByExampleParms(Object record, UsersExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}