package com.twitpic.db.dao;

import com.twitpic.db.model.Admins;
import com.twitpic.db.model.AdminsExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class AdminsDAOImpl extends SqlMapClientDaoSupport implements AdminsDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table admins
     *
     * @abatorgenerated Wed Aug 12 09:51:14 CST 2009
     */
    public AdminsDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table admins
     *
     * @abatorgenerated Wed Aug 12 09:51:14 CST 2009
     */
    public void insert(Admins record) {
        getSqlMapClientTemplate().insert("admins.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table admins
     *
     * @abatorgenerated Wed Aug 12 09:51:14 CST 2009
     */
    public int updateByPrimaryKey(Admins record) {
        int rows = getSqlMapClientTemplate().update("admins.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table admins
     *
     * @abatorgenerated Wed Aug 12 09:51:14 CST 2009
     */
    public int updateByPrimaryKeySelective(Admins record) {
        int rows = getSqlMapClientTemplate().update("admins.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table admins
     *
     * @abatorgenerated Wed Aug 12 09:51:14 CST 2009
     */
    @SuppressWarnings("unchecked")
    public List<Admins> selectByExample(AdminsExample example) {
        List<Admins> list = (List<Admins>) getSqlMapClientTemplate().queryForList("admins.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table admins
     *
     * @abatorgenerated Wed Aug 12 09:51:14 CST 2009
     */
    public Admins selectByPrimaryKey(Long id) {
        Admins key = new Admins();
        key.setId(id);
        Admins record = (Admins) getSqlMapClientTemplate().queryForObject("admins.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table admins
     *
     * @abatorgenerated Wed Aug 12 09:51:14 CST 2009
     */
    public int deleteByExample(AdminsExample example) {
        int rows = getSqlMapClientTemplate().delete("admins.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table admins
     *
     * @abatorgenerated Wed Aug 12 09:51:14 CST 2009
     */
    public int deleteByPrimaryKey(Long id) {
        Admins key = new Admins();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("admins.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table admins
     *
     * @abatorgenerated Wed Aug 12 09:51:14 CST 2009
     */
    public int countByExample(AdminsExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("admins.abatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table admins
     *
     * @abatorgenerated Wed Aug 12 09:51:14 CST 2009
     */
    public int updateByExampleSelective(Admins record, AdminsExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("admins.abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table admins
     *
     * @abatorgenerated Wed Aug 12 09:51:14 CST 2009
     */
    public int updateByExample(Admins record, AdminsExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("admins.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table admins
     *
     * @abatorgenerated Wed Aug 12 09:51:14 CST 2009
     */
    private static class UpdateByExampleParms extends AdminsExample {
        private Object record;

        public UpdateByExampleParms(Object record, AdminsExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}