package com.twitpic.db.dao;

import com.twitpic.db.model.Comments;
import com.twitpic.db.model.CommentsExample;
import com.twitpic.domain.CommentsInfo;

import java.util.List;

public interface CommentsDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table comments
	 * @abatorgenerated  Wed Aug 05 16:18:34 CST 2009
	 */
	void insert(Comments record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table comments
	 * @abatorgenerated  Wed Aug 05 16:18:34 CST 2009
	 */
	int updateByPrimaryKeyWithoutBLOBs(Comments record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table comments
	 * @abatorgenerated  Wed Aug 05 16:18:34 CST 2009
	 */
	int updateByPrimaryKeyWithBLOBs(Comments record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table comments
	 * @abatorgenerated  Wed Aug 05 16:18:34 CST 2009
	 */
	int updateByPrimaryKeySelective(Comments record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table comments
	 * @abatorgenerated  Wed Aug 05 16:18:34 CST 2009
	 */
	List<Comments> selectByExampleWithoutBLOBs(CommentsExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table comments
	 * @abatorgenerated  Wed Aug 05 16:18:34 CST 2009
	 */
	List<Comments> selectByExampleWithBLOBs(CommentsExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table comments
	 * @abatorgenerated  Wed Aug 05 16:18:34 CST 2009
	 */
	Comments selectByPrimaryKey(Long id);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table comments
	 * @abatorgenerated  Wed Aug 05 16:18:34 CST 2009
	 */
	int deleteByExample(CommentsExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table comments
	 * @abatorgenerated  Wed Aug 05 16:18:34 CST 2009
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table comments
	 * @abatorgenerated  Wed Aug 05 16:18:34 CST 2009
	 */
	int countByExample(CommentsExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table comments
	 * @abatorgenerated  Wed Aug 05 16:18:34 CST 2009
	 */
	int updateByExampleSelective(Comments record, CommentsExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table comments
	 * @abatorgenerated  Wed Aug 05 16:18:34 CST 2009
	 */
	int updateByExampleWithBLOBs(Comments record, CommentsExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table comments
	 * @abatorgenerated  Wed Aug 05 16:18:34 CST 2009
	 */
	int updateByExampleWithoutBLOBs(Comments record, CommentsExample example);
	
	Long insert_return_id(Comments record);
	
	List<CommentsInfo> selectCommentsInfoBLOBs(Long id,String account,Long id_pictures,Long start_index,Integer size);
}