package com.twitpic.db.dao;

import com.twitpic.db.model.PicturesParameter;
import com.twitpic.db.model.PicturesParameterExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class PicturesParameterDAOImpl extends SqlMapClientDaoSupport implements PicturesParameterDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table pictures_parameter
	 * @abatorgenerated  Wed Aug 05 16:26:10 CST 2009
	 */
	public PicturesParameterDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table pictures_parameter
	 * @abatorgenerated  Wed Aug 05 16:26:10 CST 2009
	 */
	public void insert(PicturesParameter record) {
		getSqlMapClientTemplate().insert(
				"pictures_parameter.abatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table pictures_parameter
	 * @abatorgenerated  Wed Aug 05 16:26:10 CST 2009
	 */
	public int updateByPrimaryKeyWithoutBLOBs(PicturesParameter record) {
		int rows = getSqlMapClientTemplate()
				.update(
						"pictures_parameter.abatorgenerated_updateByPrimaryKey",
						record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table pictures_parameter
	 * @abatorgenerated  Wed Aug 05 16:26:10 CST 2009
	 */
	public int updateByPrimaryKeyWithBLOBs(PicturesParameter record) {
		int rows = getSqlMapClientTemplate()
				.update(
						"pictures_parameter.abatorgenerated_updateByPrimaryKeyWithBLOBs",
						record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table pictures_parameter
	 * @abatorgenerated  Wed Aug 05 16:26:10 CST 2009
	 */
	public int updateByPrimaryKeySelective(PicturesParameter record) {
		int rows = getSqlMapClientTemplate()
				.update(
						"pictures_parameter.abatorgenerated_updateByPrimaryKeySelective",
						record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table pictures_parameter
	 * @abatorgenerated  Wed Aug 05 16:26:10 CST 2009
	 */
	@SuppressWarnings("unchecked")
	public List<PicturesParameter> selectByExampleWithoutBLOBs(
			PicturesParameterExample example) {
		List<PicturesParameter> list = (List<PicturesParameter>) getSqlMapClientTemplate()
				.queryForList(
						"pictures_parameter.abatorgenerated_selectByExample",
						example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table pictures_parameter
	 * @abatorgenerated  Wed Aug 05 16:26:10 CST 2009
	 */
	@SuppressWarnings("unchecked")
	public List<PicturesParameter> selectByExampleWithBLOBs(
			PicturesParameterExample example) {
		List<PicturesParameter> list = (List<PicturesParameter>) getSqlMapClientTemplate()
				.queryForList(
						"pictures_parameter.abatorgenerated_selectByExampleWithBLOBs",
						example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table pictures_parameter
	 * @abatorgenerated  Wed Aug 05 16:26:10 CST 2009
	 */
	public PicturesParameter selectByPrimaryKey(Long idPictures) {
		PicturesParameter key = new PicturesParameter();
		key.setIdPictures(idPictures);
		PicturesParameter record = (PicturesParameter) getSqlMapClientTemplate()
				.queryForObject(
						"pictures_parameter.abatorgenerated_selectByPrimaryKey",
						key);
		return record;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table pictures_parameter
	 * @abatorgenerated  Wed Aug 05 16:26:10 CST 2009
	 */
	public int deleteByExample(PicturesParameterExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"pictures_parameter.abatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table pictures_parameter
	 * @abatorgenerated  Wed Aug 05 16:26:10 CST 2009
	 */
	public int deleteByPrimaryKey(Long idPictures) {
		PicturesParameter key = new PicturesParameter();
		key.setIdPictures(idPictures);
		int rows = getSqlMapClientTemplate().delete(
				"pictures_parameter.abatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table pictures_parameter
	 * @abatorgenerated  Wed Aug 05 16:26:10 CST 2009
	 */
	public int countByExample(PicturesParameterExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"pictures_parameter.abatorgenerated_countByExample", example);
		return count;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table pictures_parameter
	 * @abatorgenerated  Wed Aug 05 16:26:10 CST 2009
	 */
	public int updateByExampleSelective(PicturesParameter record,
			PicturesParameterExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"pictures_parameter.abatorgenerated_updateByExampleSelective",
				parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table pictures_parameter
	 * @abatorgenerated  Wed Aug 05 16:26:10 CST 2009
	 */
	public int updateByExampleWithBLOBs(PicturesParameter record,
			PicturesParameterExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"pictures_parameter.abatorgenerated_updateByExampleWithBLOBs",
				parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table pictures_parameter
	 * @abatorgenerated  Wed Aug 05 16:26:10 CST 2009
	 */
	public int updateByExampleWithoutBLOBs(PicturesParameter record,
			PicturesParameterExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"pictures_parameter.abatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table pictures_parameter
	 * @abatorgenerated  Wed Aug 05 16:26:10 CST 2009
	 */
	private static class UpdateByExampleParms extends PicturesParameterExample {
		private Object record;

		public UpdateByExampleParms(Object record,
				PicturesParameterExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}