package com.twitpic.db.dao;

import com.twitpic.db.model.PicturesCollection;
import com.twitpic.db.model.PicturesCollectionExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class PicturesCollectionDAOImpl extends SqlMapClientDaoSupport implements PicturesCollectionDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pictures_collection
     *
     * @ibatorgenerated Wed Sep 02 16:12:27 CST 2009
     */
    public PicturesCollectionDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pictures_collection
     *
     * @ibatorgenerated Wed Sep 02 16:12:27 CST 2009
     */
    public int countByExample(PicturesCollectionExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("pictures_collection.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pictures_collection
     *
     * @ibatorgenerated Wed Sep 02 16:12:27 CST 2009
     */
    public int deleteByExample(PicturesCollectionExample example) {
        int rows = getSqlMapClientTemplate().delete("pictures_collection.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pictures_collection
     *
     * @ibatorgenerated Wed Sep 02 16:12:27 CST 2009
     */
    public int deleteByPrimaryKey(Long id) {
        PicturesCollection key = new PicturesCollection();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("pictures_collection.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pictures_collection
     *
     * @ibatorgenerated Wed Sep 02 16:12:27 CST 2009
     */
    public void insert(PicturesCollection record) {
        getSqlMapClientTemplate().insert("pictures_collection.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pictures_collection
     *
     * @ibatorgenerated Wed Sep 02 16:12:27 CST 2009
     */
    public void insertSelective(PicturesCollection record) {
        getSqlMapClientTemplate().insert("pictures_collection.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pictures_collection
     *
     * @ibatorgenerated Wed Sep 02 16:12:27 CST 2009
     */
    @SuppressWarnings("unchecked")
    public List<PicturesCollection> selectByExample(PicturesCollectionExample example) {
        List<PicturesCollection> list = getSqlMapClientTemplate().queryForList("pictures_collection.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pictures_collection
     *
     * @ibatorgenerated Wed Sep 02 16:12:27 CST 2009
     */
    public PicturesCollection selectByPrimaryKey(Long id) {
        PicturesCollection key = new PicturesCollection();
        key.setId(id);
        PicturesCollection record = (PicturesCollection) getSqlMapClientTemplate().queryForObject("pictures_collection.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pictures_collection
     *
     * @ibatorgenerated Wed Sep 02 16:12:27 CST 2009
     */
    public int updateByExampleSelective(PicturesCollection record, PicturesCollectionExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("pictures_collection.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pictures_collection
     *
     * @ibatorgenerated Wed Sep 02 16:12:27 CST 2009
     */
    public int updateByExample(PicturesCollection record, PicturesCollectionExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("pictures_collection.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pictures_collection
     *
     * @ibatorgenerated Wed Sep 02 16:12:27 CST 2009
     */
    public int updateByPrimaryKeySelective(PicturesCollection record) {
        int rows = getSqlMapClientTemplate().update("pictures_collection.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pictures_collection
     *
     * @ibatorgenerated Wed Sep 02 16:12:27 CST 2009
     */
    public int updateByPrimaryKey(PicturesCollection record) {
        int rows = getSqlMapClientTemplate().update("pictures_collection.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table pictures_collection
     *
     * @ibatorgenerated Wed Sep 02 16:12:27 CST 2009
     */
    private static class UpdateByExampleParms extends PicturesCollectionExample {
        private Object record;

        public UpdateByExampleParms(Object record, PicturesCollectionExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }

	@Override
	public long insert_return_id(PicturesCollection record) {
		return (Long)getSqlMapClientTemplate().insert("pictures_collection.insert_return_id", record);
	}

	@SuppressWarnings("unchecked")
	@Override
	public int count_collection_picture(String account, Long idPicture,
			Long idCollections) {
		java.util.Map maps = new java.util.HashMap();
		maps.put("account", account);
		maps.put("id_pictures", idPicture);
		maps.put("id_collections", idCollections);
		Integer result =  (Integer)  getSqlMapClientTemplate().queryForObject("pictures_collection.count_collected_picture", maps);
		if(result==null){
			return 0;
		}
		return result;
	}
}