package com.twitpic.db.dao;

import com.twitpic.db.model.TagsRel;
import com.twitpic.db.model.TagsRelExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class TagsRelDAOImpl extends SqlMapClientDaoSupport implements TagsRelDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table tags_rel
     *
     * @abatorgenerated Sun Aug 02 17:41:31 CST 2009
     */
    public TagsRelDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table tags_rel
     *
     * @abatorgenerated Sun Aug 02 17:41:31 CST 2009
     */
    public void insert(TagsRel record) {
        getSqlMapClientTemplate().insert("tags_rel.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table tags_rel
     *
     * @abatorgenerated Sun Aug 02 17:41:31 CST 2009
     */
    public int updateByPrimaryKey(TagsRel record) {
        int rows = getSqlMapClientTemplate().update("tags_rel.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table tags_rel
     *
     * @abatorgenerated Sun Aug 02 17:41:31 CST 2009
     */
    public int updateByPrimaryKeySelective(TagsRel record) {
        int rows = getSqlMapClientTemplate().update("tags_rel.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table tags_rel
     *
     * @abatorgenerated Sun Aug 02 17:41:31 CST 2009
     */
    @SuppressWarnings("unchecked")
    public List<TagsRel> selectByExample(TagsRelExample example) {
        List<TagsRel> list = (List<TagsRel>) getSqlMapClientTemplate().queryForList("tags_rel.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table tags_rel
     *
     * @abatorgenerated Sun Aug 02 17:41:31 CST 2009
     */
    public TagsRel selectByPrimaryKey(Long id) {
        TagsRel key = new TagsRel();
        key.setId(id);
        TagsRel record = (TagsRel) getSqlMapClientTemplate().queryForObject("tags_rel.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table tags_rel
     *
     * @abatorgenerated Sun Aug 02 17:41:31 CST 2009
     */
    public int deleteByExample(TagsRelExample example) {
        int rows = getSqlMapClientTemplate().delete("tags_rel.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table tags_rel
     *
     * @abatorgenerated Sun Aug 02 17:41:31 CST 2009
     */
    public int deleteByPrimaryKey(Long id) {
        TagsRel key = new TagsRel();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("tags_rel.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table tags_rel
     *
     * @abatorgenerated Sun Aug 02 17:41:31 CST 2009
     */
    public int countByExample(TagsRelExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("tags_rel.abatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table tags_rel
     *
     * @abatorgenerated Sun Aug 02 17:41:31 CST 2009
     */
    public int updateByExampleSelective(TagsRel record, TagsRelExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("tags_rel.abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table tags_rel
     *
     * @abatorgenerated Sun Aug 02 17:41:31 CST 2009
     */
    public int updateByExample(TagsRel record, TagsRelExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("tags_rel.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table tags_rel
     *
     * @abatorgenerated Sun Aug 02 17:41:31 CST 2009
     */
    private static class UpdateByExampleParms extends TagsRelExample {
        private Object record;

        public UpdateByExampleParms(Object record, TagsRelExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}