package com.twitpic.db.dao;

import com.twitpic.db.model.UsersProfile;
import com.twitpic.db.model.UsersProfileExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class UsersProfileDAOImpl extends SqlMapClientDaoSupport implements UsersProfileDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table users_profile
     *
     * @abatorgenerated Sun Aug 02 17:41:31 CST 2009
     */
    public UsersProfileDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table users_profile
     *
     * @abatorgenerated Sun Aug 02 17:41:31 CST 2009
     */
    public void insert(UsersProfile record) {
        getSqlMapClientTemplate().insert("users_profile.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table users_profile
     *
     * @abatorgenerated Sun Aug 02 17:41:31 CST 2009
     */
    public int updateByPrimaryKey(UsersProfile record) {
        int rows = getSqlMapClientTemplate().update("users_profile.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table users_profile
     *
     * @abatorgenerated Sun Aug 02 17:41:31 CST 2009
     */
    public int updateByPrimaryKeySelective(UsersProfile record) {
        int rows = getSqlMapClientTemplate().update("users_profile.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table users_profile
     *
     * @abatorgenerated Sun Aug 02 17:41:31 CST 2009
     */
    @SuppressWarnings("unchecked")
    public List<UsersProfile> selectByExample(UsersProfileExample example) {
        List<UsersProfile> list = (List<UsersProfile>) getSqlMapClientTemplate().queryForList("users_profile.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table users_profile
     *
     * @abatorgenerated Sun Aug 02 17:41:31 CST 2009
     */
    public UsersProfile selectByPrimaryKey(String account) {
        UsersProfile key = new UsersProfile();
        key.setAccount(account);
        UsersProfile record = (UsersProfile) getSqlMapClientTemplate().queryForObject("users_profile.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table users_profile
     *
     * @abatorgenerated Sun Aug 02 17:41:31 CST 2009
     */
    public int deleteByExample(UsersProfileExample example) {
        int rows = getSqlMapClientTemplate().delete("users_profile.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table users_profile
     *
     * @abatorgenerated Sun Aug 02 17:41:31 CST 2009
     */
    public int deleteByPrimaryKey(String account) {
        UsersProfile key = new UsersProfile();
        key.setAccount(account);
        int rows = getSqlMapClientTemplate().delete("users_profile.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table users_profile
     *
     * @abatorgenerated Sun Aug 02 17:41:31 CST 2009
     */
    public int countByExample(UsersProfileExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("users_profile.abatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table users_profile
     *
     * @abatorgenerated Sun Aug 02 17:41:31 CST 2009
     */
    public int updateByExampleSelective(UsersProfile record, UsersProfileExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("users_profile.abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table users_profile
     *
     * @abatorgenerated Sun Aug 02 17:41:31 CST 2009
     */
    public int updateByExample(UsersProfile record, UsersProfileExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("users_profile.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table users_profile
     *
     * @abatorgenerated Sun Aug 02 17:41:31 CST 2009
     */
    private static class UpdateByExampleParms extends UsersProfileExample {
        private Object record;

        public UpdateByExampleParms(Object record, UsersProfileExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}