package com.zhela.cloudblog.dao.ourservice.impl;

import com.zhela.cloudblog.dao.ourservice.MakeBetterDAO;
import com.zhela.cloudblog.model.ourservice.MakeBetter;
import com.zhela.cloudblog.model.ourservice.MakeBetterExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class MakeBetterDAOImpl extends SqlMapClientDaoSupport implements MakeBetterDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table make_better
     *
     * @ibatorgenerated Fri Dec 10 17:02:49 CST 2010
     */
    public MakeBetterDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table make_better
     *
     * @ibatorgenerated Fri Dec 10 17:02:49 CST 2010
     */
    public int countByExample(MakeBetterExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("make_better.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table make_better
     *
     * @ibatorgenerated Fri Dec 10 17:02:49 CST 2010
     */
    public int deleteByExample(MakeBetterExample example) {
        int rows = getSqlMapClientTemplate().delete("make_better.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table make_better
     *
     * @ibatorgenerated Fri Dec 10 17:02:49 CST 2010
     */
    public int deleteByPrimaryKey(Long id) {
        MakeBetter key = new MakeBetter();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("make_better.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table make_better
     *
     * @ibatorgenerated Fri Dec 10 17:02:49 CST 2010
     */
    public void insert(MakeBetter record) {
        getSqlMapClientTemplate().insert("make_better.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table make_better
     *
     * @ibatorgenerated Fri Dec 10 17:02:49 CST 2010
     */
    public void insertSelective(MakeBetter record) {
        getSqlMapClientTemplate().insert("make_better.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table make_better
     *
     * @ibatorgenerated Fri Dec 10 17:02:49 CST 2010
     */
    @SuppressWarnings("unchecked")
    public List<MakeBetter> selectByExampleWithBLOBs(MakeBetterExample example) {
        List<MakeBetter> list = getSqlMapClientTemplate().queryForList("make_better.ibatorgenerated_selectByExampleWithBLOBs", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table make_better
     *
     * @ibatorgenerated Fri Dec 10 17:02:49 CST 2010
     */
    @SuppressWarnings("unchecked")
    public List<MakeBetter> selectByExampleWithoutBLOBs(MakeBetterExample example) {
        List<MakeBetter> list = getSqlMapClientTemplate().queryForList("make_better.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table make_better
     *
     * @ibatorgenerated Fri Dec 10 17:02:49 CST 2010
     */
    public MakeBetter selectByPrimaryKey(Long id) {
        MakeBetter key = new MakeBetter();
        key.setId(id);
        MakeBetter record = (MakeBetter) getSqlMapClientTemplate().queryForObject("make_better.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table make_better
     *
     * @ibatorgenerated Fri Dec 10 17:02:49 CST 2010
     */
    public int updateByExampleSelective(MakeBetter record, MakeBetterExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("make_better.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table make_better
     *
     * @ibatorgenerated Fri Dec 10 17:02:49 CST 2010
     */
    public int updateByExampleWithBLOBs(MakeBetter record, MakeBetterExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("make_better.ibatorgenerated_updateByExampleWithBLOBs", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table make_better
     *
     * @ibatorgenerated Fri Dec 10 17:02:49 CST 2010
     */
    public int updateByExampleWithoutBLOBs(MakeBetter record, MakeBetterExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("make_better.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table make_better
     *
     * @ibatorgenerated Fri Dec 10 17:02:49 CST 2010
     */
    public int updateByPrimaryKeySelective(MakeBetter record) {
        int rows = getSqlMapClientTemplate().update("make_better.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table make_better
     *
     * @ibatorgenerated Fri Dec 10 17:02:49 CST 2010
     */
    public int updateByPrimaryKeyWithBLOBs(MakeBetter record) {
        int rows = getSqlMapClientTemplate().update("make_better.ibatorgenerated_updateByPrimaryKeyWithBLOBs", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table make_better
     *
     * @ibatorgenerated Fri Dec 10 17:02:49 CST 2010
     */
    public int updateByPrimaryKeyWithoutBLOBs(MakeBetter record) {
        int rows = getSqlMapClientTemplate().update("make_better.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table make_better
     *
     * @ibatorgenerated Fri Dec 10 17:02:49 CST 2010
     */
    private static class UpdateByExampleParms extends MakeBetterExample {
        private Object record;

        public UpdateByExampleParms(Object record, MakeBetterExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}