package com.zhela.cloudblog.dao.ourservice.impl;

import com.zhela.cloudblog.dao.ourservice.OtherAnswerDAO;
import com.zhela.cloudblog.model.ourservice.OtherAnswer;
import com.zhela.cloudblog.model.ourservice.OtherAnswerExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class OtherAnswerDAOImpl extends SqlMapClientDaoSupport implements OtherAnswerDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table other_answer
     *
     * @ibatorgenerated Thu Dec 16 14:30:38 CST 2010
     */
    public OtherAnswerDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table other_answer
     *
     * @ibatorgenerated Thu Dec 16 14:30:38 CST 2010
     */
    public int countByExample(OtherAnswerExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("other_answer.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table other_answer
     *
     * @ibatorgenerated Thu Dec 16 14:30:38 CST 2010
     */
    public int deleteByExample(OtherAnswerExample example) {
        int rows = getSqlMapClientTemplate().delete("other_answer.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table other_answer
     *
     * @ibatorgenerated Thu Dec 16 14:30:38 CST 2010
     */
    public int deleteByPrimaryKey(Long id) {
        OtherAnswer key = new OtherAnswer();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("other_answer.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table other_answer
     *
     * @ibatorgenerated Thu Dec 16 14:30:38 CST 2010
     */
    public void insert(OtherAnswer record) {
        getSqlMapClientTemplate().insert("other_answer.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table other_answer
     *
     * @ibatorgenerated Thu Dec 16 14:30:38 CST 2010
     */
    public void insertSelective(OtherAnswer record) {
        getSqlMapClientTemplate().insert("other_answer.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table other_answer
     *
     * @ibatorgenerated Thu Dec 16 14:30:38 CST 2010
     */
    @SuppressWarnings("unchecked")
    public List<OtherAnswer> selectByExampleWithBLOBs(OtherAnswerExample example) {
        List<OtherAnswer> list = getSqlMapClientTemplate().queryForList("other_answer.ibatorgenerated_selectByExampleWithBLOBs", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table other_answer
     *
     * @ibatorgenerated Thu Dec 16 14:30:38 CST 2010
     */
    @SuppressWarnings("unchecked")
    public List<OtherAnswer> selectByExampleWithoutBLOBs(OtherAnswerExample example) {
        List<OtherAnswer> list = getSqlMapClientTemplate().queryForList("other_answer.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table other_answer
     *
     * @ibatorgenerated Thu Dec 16 14:30:38 CST 2010
     */
    public OtherAnswer selectByPrimaryKey(Long id) {
        OtherAnswer key = new OtherAnswer();
        key.setId(id);
        OtherAnswer record = (OtherAnswer) getSqlMapClientTemplate().queryForObject("other_answer.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table other_answer
     *
     * @ibatorgenerated Thu Dec 16 14:30:38 CST 2010
     */
    public int updateByExampleSelective(OtherAnswer record, OtherAnswerExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("other_answer.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table other_answer
     *
     * @ibatorgenerated Thu Dec 16 14:30:38 CST 2010
     */
    public int updateByExampleWithBLOBs(OtherAnswer record, OtherAnswerExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("other_answer.ibatorgenerated_updateByExampleWithBLOBs", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table other_answer
     *
     * @ibatorgenerated Thu Dec 16 14:30:38 CST 2010
     */
    public int updateByExampleWithoutBLOBs(OtherAnswer record, OtherAnswerExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("other_answer.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table other_answer
     *
     * @ibatorgenerated Thu Dec 16 14:30:38 CST 2010
     */
    public int updateByPrimaryKeySelective(OtherAnswer record) {
        int rows = getSqlMapClientTemplate().update("other_answer.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table other_answer
     *
     * @ibatorgenerated Thu Dec 16 14:30:38 CST 2010
     */
    public int updateByPrimaryKeyWithBLOBs(OtherAnswer record) {
        int rows = getSqlMapClientTemplate().update("other_answer.ibatorgenerated_updateByPrimaryKeyWithBLOBs", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table other_answer
     *
     * @ibatorgenerated Thu Dec 16 14:30:38 CST 2010
     */
    public int updateByPrimaryKeyWithoutBLOBs(OtherAnswer record) {
        int rows = getSqlMapClientTemplate().update("other_answer.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table other_answer
     *
     * @ibatorgenerated Thu Dec 16 14:30:38 CST 2010
     */
    private static class UpdateByExampleParms extends OtherAnswerExample {
        private Object record;

        public UpdateByExampleParms(Object record, OtherAnswerExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}