package com.zhela.cloudblog.dao.ourservice.impl;

import com.zhela.cloudblog.dao.ourservice.OurServiceDAO;
import com.zhela.cloudblog.model.ourservice.OurService;
import com.zhela.cloudblog.model.ourservice.OurServiceExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class OurServiceDAOImpl extends SqlMapClientDaoSupport implements OurServiceDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table our_service
     *
     * @ibatorgenerated Mon Nov 29 14:02:02 CST 2010
     */
    public OurServiceDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table our_service
     *
     * @ibatorgenerated Mon Nov 29 14:02:02 CST 2010
     */
    public int countByExample(OurServiceExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("our_service.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table our_service
     *
     * @ibatorgenerated Mon Nov 29 14:02:02 CST 2010
     */
    public int deleteByExample(OurServiceExample example) {
        int rows = getSqlMapClientTemplate().delete("our_service.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table our_service
     *
     * @ibatorgenerated Mon Nov 29 14:02:02 CST 2010
     */
    public int deleteByPrimaryKey(Integer id) {
        OurService key = new OurService();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("our_service.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table our_service
     *
     * @ibatorgenerated Mon Nov 29 14:02:02 CST 2010
     */
    public void insert(OurService record) {
        getSqlMapClientTemplate().insert("our_service.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table our_service
     *
     * @ibatorgenerated Mon Nov 29 14:02:02 CST 2010
     */
    public void insertSelective(OurService record) {
        getSqlMapClientTemplate().insert("our_service.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table our_service
     *
     * @ibatorgenerated Mon Nov 29 14:02:02 CST 2010
     */
    @SuppressWarnings("unchecked")
    public List<OurService> selectByExample(OurServiceExample example) {
        List<OurService> list = getSqlMapClientTemplate().queryForList("our_service.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table our_service
     *
     * @ibatorgenerated Mon Nov 29 14:02:02 CST 2010
     */
    public OurService selectByPrimaryKey(Integer id) {
        OurService key = new OurService();
        key.setId(id);
        OurService record = (OurService) getSqlMapClientTemplate().queryForObject("our_service.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table our_service
     *
     * @ibatorgenerated Mon Nov 29 14:02:02 CST 2010
     */
    public int updateByExampleSelective(OurService record, OurServiceExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("our_service.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table our_service
     *
     * @ibatorgenerated Mon Nov 29 14:02:02 CST 2010
     */
    public int updateByExample(OurService record, OurServiceExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("our_service.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table our_service
     *
     * @ibatorgenerated Mon Nov 29 14:02:02 CST 2010
     */
    public int updateByPrimaryKeySelective(OurService record) {
        int rows = getSqlMapClientTemplate().update("our_service.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table our_service
     *
     * @ibatorgenerated Mon Nov 29 14:02:02 CST 2010
     */
    public int updateByPrimaryKey(OurService record) {
        int rows = getSqlMapClientTemplate().update("our_service.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table our_service
     *
     * @ibatorgenerated Mon Nov 29 14:02:02 CST 2010
     */
    private static class UpdateByExampleParms extends OurServiceExample {
        private Object record;

        public UpdateByExampleParms(Object record, OurServiceExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}