package com.zhela.cloudblog.dao.ourservice.impl;

import com.zhela.cloudblog.dao.ourservice.QuestionDAO;
import com.zhela.cloudblog.model.ourservice.Question;
import com.zhela.cloudblog.model.ourservice.QuestionExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class QuestionDAOImpl extends SqlMapClientDaoSupport implements QuestionDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table question
     *
     * @ibatorgenerated Thu Dec 16 14:30:38 CST 2010
     */
    public QuestionDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table question
     *
     * @ibatorgenerated Thu Dec 16 14:30:38 CST 2010
     */
    public int countByExample(QuestionExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("question.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table question
     *
     * @ibatorgenerated Thu Dec 16 14:30:38 CST 2010
     */
    public int deleteByExample(QuestionExample example) {
        int rows = getSqlMapClientTemplate().delete("question.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table question
     *
     * @ibatorgenerated Thu Dec 16 14:30:38 CST 2010
     */
    public int deleteByPrimaryKey(Long id) {
        Question key = new Question();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("question.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table question
     *
     * @ibatorgenerated Thu Dec 16 14:30:38 CST 2010
     */
    public void insert(Question record) {
        getSqlMapClientTemplate().insert("question.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table question
     *
     * @ibatorgenerated Thu Dec 16 14:30:38 CST 2010
     */
    public void insertSelective(Question record) {
        getSqlMapClientTemplate().insert("question.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table question
     *
     * @ibatorgenerated Thu Dec 16 14:30:38 CST 2010
     */
    @SuppressWarnings("unchecked")
    public List<Question> selectByExampleWithBLOBs(QuestionExample example) {
        List<Question> list = getSqlMapClientTemplate().queryForList("question.ibatorgenerated_selectByExampleWithBLOBs", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table question
     *
     * @ibatorgenerated Thu Dec 16 14:30:38 CST 2010
     */
    @SuppressWarnings("unchecked")
    public List<Question> selectByExampleWithoutBLOBs(QuestionExample example) {
        List<Question> list = getSqlMapClientTemplate().queryForList("question.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table question
     *
     * @ibatorgenerated Thu Dec 16 14:30:38 CST 2010
     */
    public Question selectByPrimaryKey(Long id) {
        Question key = new Question();
        key.setId(id);
        Question record = (Question) getSqlMapClientTemplate().queryForObject("question.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table question
     *
     * @ibatorgenerated Thu Dec 16 14:30:38 CST 2010
     */
    public int updateByExampleSelective(Question record, QuestionExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("question.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table question
     *
     * @ibatorgenerated Thu Dec 16 14:30:38 CST 2010
     */
    public int updateByExampleWithBLOBs(Question record, QuestionExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("question.ibatorgenerated_updateByExampleWithBLOBs", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table question
     *
     * @ibatorgenerated Thu Dec 16 14:30:38 CST 2010
     */
    public int updateByExampleWithoutBLOBs(Question record, QuestionExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("question.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table question
     *
     * @ibatorgenerated Thu Dec 16 14:30:38 CST 2010
     */
    public int updateByPrimaryKeySelective(Question record) {
        int rows = getSqlMapClientTemplate().update("question.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table question
     *
     * @ibatorgenerated Thu Dec 16 14:30:38 CST 2010
     */
    public int updateByPrimaryKeyWithBLOBs(Question record) {
        int rows = getSqlMapClientTemplate().update("question.ibatorgenerated_updateByPrimaryKeyWithBLOBs", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table question
     *
     * @ibatorgenerated Thu Dec 16 14:30:38 CST 2010
     */
    public int updateByPrimaryKeyWithoutBLOBs(Question record) {
        int rows = getSqlMapClientTemplate().update("question.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table question
     *
     * @ibatorgenerated Thu Dec 16 14:30:38 CST 2010
     */
    private static class UpdateByExampleParms extends QuestionExample {
        private Object record;

        public UpdateByExampleParms(Object record, QuestionExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}