package com.zhela.cloudblog.dao.ourservice.impl;

import com.zhela.cloudblog.dao.ourservice.ServiceBindDAO;
import com.zhela.cloudblog.model.ourservice.ServiceBind;
import com.zhela.cloudblog.model.ourservice.ServiceBindExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class ServiceBindDAOImpl extends SqlMapClientDaoSupport implements ServiceBindDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table service_bind
     *
     * @ibatorgenerated Mon Nov 29 14:02:02 CST 2010
     */
    public ServiceBindDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table service_bind
     *
     * @ibatorgenerated Mon Nov 29 14:02:02 CST 2010
     */
    public int countByExample(ServiceBindExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("service_bind.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table service_bind
     *
     * @ibatorgenerated Mon Nov 29 14:02:02 CST 2010
     */
    public int deleteByExample(ServiceBindExample example) {
        int rows = getSqlMapClientTemplate().delete("service_bind.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table service_bind
     *
     * @ibatorgenerated Mon Nov 29 14:02:02 CST 2010
     */
    public int deleteByPrimaryKey(String code) {
        ServiceBind key = new ServiceBind();
        key.setCode(code);
        int rows = getSqlMapClientTemplate().delete("service_bind.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table service_bind
     *
     * @ibatorgenerated Mon Nov 29 14:02:02 CST 2010
     */
    public void insert(ServiceBind record) {
        getSqlMapClientTemplate().insert("service_bind.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table service_bind
     *
     * @ibatorgenerated Mon Nov 29 14:02:02 CST 2010
     */
    public void insertSelective(ServiceBind record) {
        getSqlMapClientTemplate().insert("service_bind.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table service_bind
     *
     * @ibatorgenerated Mon Nov 29 14:02:02 CST 2010
     */
    @SuppressWarnings("unchecked")
    public List<ServiceBind> selectByExample(ServiceBindExample example) {
        List<ServiceBind> list = getSqlMapClientTemplate().queryForList("service_bind.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table service_bind
     *
     * @ibatorgenerated Mon Nov 29 14:02:02 CST 2010
     */
    public ServiceBind selectByPrimaryKey(String code) {
        ServiceBind key = new ServiceBind();
        key.setCode(code);
        ServiceBind record = (ServiceBind) getSqlMapClientTemplate().queryForObject("service_bind.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table service_bind
     *
     * @ibatorgenerated Mon Nov 29 14:02:02 CST 2010
     */
    public int updateByExampleSelective(ServiceBind record, ServiceBindExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("service_bind.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table service_bind
     *
     * @ibatorgenerated Mon Nov 29 14:02:02 CST 2010
     */
    public int updateByExample(ServiceBind record, ServiceBindExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("service_bind.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table service_bind
     *
     * @ibatorgenerated Mon Nov 29 14:02:02 CST 2010
     */
    public int updateByPrimaryKeySelective(ServiceBind record) {
        int rows = getSqlMapClientTemplate().update("service_bind.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table service_bind
     *
     * @ibatorgenerated Mon Nov 29 14:02:02 CST 2010
     */
    public int updateByPrimaryKey(ServiceBind record) {
        int rows = getSqlMapClientTemplate().update("service_bind.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table service_bind
     *
     * @ibatorgenerated Mon Nov 29 14:02:02 CST 2010
     */
    private static class UpdateByExampleParms extends ServiceBindExample {
        private Object record;

        public UpdateByExampleParms(Object record, ServiceBindExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}