package com.zhela.cloudblog.dao.ourservice.impl;

import com.zhela.cloudblog.model.ourservice.Survey;
import com.zhela.cloudblog.model.ourservice.SurveyExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class SurveyDAOImpl extends SqlMapClientDaoSupport implements SurveyDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table survey
     *
     * @ibatorgenerated Thu Dec 16 15:38:55 CST 2010
     */
    public SurveyDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table survey
     *
     * @ibatorgenerated Thu Dec 16 15:38:55 CST 2010
     */
    public int countByExample(SurveyExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("survey.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table survey
     *
     * @ibatorgenerated Thu Dec 16 15:38:55 CST 2010
     */
    public int deleteByExample(SurveyExample example) {
        int rows = getSqlMapClientTemplate().delete("survey.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table survey
     *
     * @ibatorgenerated Thu Dec 16 15:38:55 CST 2010
     */
    public int deleteByPrimaryKey(Long id) {
        Survey key = new Survey();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("survey.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table survey
     *
     * @ibatorgenerated Thu Dec 16 15:38:55 CST 2010
     */
    public void insert(Survey record) {
        getSqlMapClientTemplate().insert("survey.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table survey
     *
     * @ibatorgenerated Thu Dec 16 15:38:55 CST 2010
     */
    public void insertSelective(Survey record) {
        getSqlMapClientTemplate().insert("survey.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table survey
     *
     * @ibatorgenerated Thu Dec 16 15:38:55 CST 2010
     */
    @SuppressWarnings("unchecked")
    public List<Survey> selectByExample(SurveyExample example) {
        List<Survey> list = getSqlMapClientTemplate().queryForList("survey.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table survey
     *
     * @ibatorgenerated Thu Dec 16 15:38:55 CST 2010
     */
    public Survey selectByPrimaryKey(Long id) {
        Survey key = new Survey();
        key.setId(id);
        Survey record = (Survey) getSqlMapClientTemplate().queryForObject("survey.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table survey
     *
     * @ibatorgenerated Thu Dec 16 15:38:55 CST 2010
     */
    public int updateByExampleSelective(Survey record, SurveyExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("survey.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table survey
     *
     * @ibatorgenerated Thu Dec 16 15:38:55 CST 2010
     */
    public int updateByExample(Survey record, SurveyExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("survey.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table survey
     *
     * @ibatorgenerated Thu Dec 16 15:38:55 CST 2010
     */
    public int updateByPrimaryKeySelective(Survey record) {
        int rows = getSqlMapClientTemplate().update("survey.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table survey
     *
     * @ibatorgenerated Thu Dec 16 15:38:55 CST 2010
     */
    public int updateByPrimaryKey(Survey record) {
        int rows = getSqlMapClientTemplate().update("survey.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table survey
     *
     * @ibatorgenerated Thu Dec 16 15:38:55 CST 2010
     */
    private static class UpdateByExampleParms extends SurveyExample {
        private Object record;

        public UpdateByExampleParms(Object record, SurveyExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}