package com.zhela.cloudblog.model.device;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.zhela.cloudblog.model.DefaultExample;

public class DeviceLogExample extends DefaultExample{

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table device_log
	 * @ibatorgenerated  Sat Oct 23 14:28:50 CST 2010
	 */
	protected String orderByClause;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table device_log
	 * @ibatorgenerated  Sat Oct 23 14:28:50 CST 2010
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table device_log
	 * @ibatorgenerated  Sat Oct 23 14:28:50 CST 2010
	 */
	public DeviceLogExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table device_log
	 * @ibatorgenerated  Sat Oct 23 14:28:50 CST 2010
	 */
	protected DeviceLogExample(DeviceLogExample example) {
		this.orderByClause = example.orderByClause;
		this.oredCriteria = example.oredCriteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table device_log
	 * @ibatorgenerated  Sat Oct 23 14:28:50 CST 2010
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table device_log
	 * @ibatorgenerated  Sat Oct 23 14:28:50 CST 2010
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table device_log
	 * @ibatorgenerated  Sat Oct 23 14:28:50 CST 2010
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table device_log
	 * @ibatorgenerated  Sat Oct 23 14:28:50 CST 2010
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table device_log
	 * @ibatorgenerated  Sat Oct 23 14:28:50 CST 2010
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table device_log
	 * @ibatorgenerated  Sat Oct 23 14:28:50 CST 2010
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table device_log
	 * @ibatorgenerated  Sat Oct 23 14:28:50 CST 2010
	 */
	public void clear() {
		oredCriteria.clear();
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table device_log
	 * @ibatorgenerated  Sat Oct 23 14:28:50 CST 2010
	 */
	public static class Criteria {
		protected List<String> criteriaWithoutValue;
		protected List<Map<String, Object>> criteriaWithSingleValue;
		protected List<Map<String, Object>> criteriaWithListValue;
		protected List<Map<String, Object>> criteriaWithBetweenValue;

		protected Criteria() {
			super();
			criteriaWithoutValue = new ArrayList<String>();
			criteriaWithSingleValue = new ArrayList<Map<String, Object>>();
			criteriaWithListValue = new ArrayList<Map<String, Object>>();
			criteriaWithBetweenValue = new ArrayList<Map<String, Object>>();
		}

		public boolean isValid() {
			return criteriaWithoutValue.size() > 0
					|| criteriaWithSingleValue.size() > 0
					|| criteriaWithListValue.size() > 0
					|| criteriaWithBetweenValue.size() > 0;
		}

		public List<String> getCriteriaWithoutValue() {
			return criteriaWithoutValue;
		}

		public List<Map<String, Object>> getCriteriaWithSingleValue() {
			return criteriaWithSingleValue;
		}

		public List<Map<String, Object>> getCriteriaWithListValue() {
			return criteriaWithListValue;
		}

		public List<Map<String, Object>> getCriteriaWithBetweenValue() {
			return criteriaWithBetweenValue;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteriaWithoutValue.add(condition);
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			Map<String, Object> map = new HashMap<String, Object>();
			map.put("condition", condition);
			map.put("value", value);
			criteriaWithSingleValue.add(map);
		}

		protected void addCriterion(String condition,
				List<? extends Object> values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property
						+ " cannot be null or empty");
			}
			Map<String, Object> map = new HashMap<String, Object>();
			map.put("condition", condition);
			map.put("values", values);
			criteriaWithListValue.add(map);
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			List<Object> list = new ArrayList<Object>();
			list.add(value1);
			list.add(value2);
			Map<String, Object> map = new HashMap<String, Object>();
			map.put("condition", condition);
			map.put("values", list);
			criteriaWithBetweenValue.add(map);
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return this;
		}

		public Criteria andIdEqualTo(Long value) {
			addCriterion("id =", value, "id");
			return this;
		}

		public Criteria andIdNotEqualTo(Long value) {
			addCriterion("id <>", value, "id");
			return this;
		}

		public Criteria andIdGreaterThan(Long value) {
			addCriterion("id >", value, "id");
			return this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Long value) {
			addCriterion("id >=", value, "id");
			return this;
		}

		public Criteria andIdLessThan(Long value) {
			addCriterion("id <", value, "id");
			return this;
		}

		public Criteria andIdLessThanOrEqualTo(Long value) {
			addCriterion("id <=", value, "id");
			return this;
		}

		public Criteria andIdIn(List<Long> values) {
			addCriterion("id in", values, "id");
			return this;
		}

		public Criteria andIdNotIn(List<Long> values) {
			addCriterion("id not in", values, "id");
			return this;
		}

		public Criteria andIdBetween(Long value1, Long value2) {
			addCriterion("id between", value1, value2, "id");
			return this;
		}

		public Criteria andIdNotBetween(Long value1, Long value2) {
			addCriterion("id not between", value1, value2, "id");
			return this;
		}

		public Criteria andSessionIdIsNull() {
			addCriterion("session_id is null");
			return this;
		}

		public Criteria andSessionIdIsNotNull() {
			addCriterion("session_id is not null");
			return this;
		}

		public Criteria andSessionIdEqualTo(String value) {
			addCriterion("session_id =", value, "sessionId");
			return this;
		}

		public Criteria andSessionIdNotEqualTo(String value) {
			addCriterion("session_id <>", value, "sessionId");
			return this;
		}

		public Criteria andSessionIdGreaterThan(String value) {
			addCriterion("session_id >", value, "sessionId");
			return this;
		}

		public Criteria andSessionIdGreaterThanOrEqualTo(String value) {
			addCriterion("session_id >=", value, "sessionId");
			return this;
		}

		public Criteria andSessionIdLessThan(String value) {
			addCriterion("session_id <", value, "sessionId");
			return this;
		}

		public Criteria andSessionIdLessThanOrEqualTo(String value) {
			addCriterion("session_id <=", value, "sessionId");
			return this;
		}

		public Criteria andSessionIdLike(String value) {
			addCriterion("session_id like", value, "sessionId");
			return this;
		}

		public Criteria andSessionIdNotLike(String value) {
			addCriterion("session_id not like", value, "sessionId");
			return this;
		}

		public Criteria andSessionIdIn(List<String> values) {
			addCriterion("session_id in", values, "sessionId");
			return this;
		}

		public Criteria andSessionIdNotIn(List<String> values) {
			addCriterion("session_id not in", values, "sessionId");
			return this;
		}

		public Criteria andSessionIdBetween(String value1, String value2) {
			addCriterion("session_id between", value1, value2, "sessionId");
			return this;
		}

		public Criteria andSessionIdNotBetween(String value1, String value2) {
			addCriterion("session_id not between", value1, value2, "sessionId");
			return this;
		}

		public Criteria andDeviceIdIsNull() {
			addCriterion("device_id is null");
			return this;
		}

		public Criteria andDeviceIdIsNotNull() {
			addCriterion("device_id is not null");
			return this;
		}

		public Criteria andDeviceIdEqualTo(String value) {
			addCriterion("device_id =", value, "deviceId");
			return this;
		}

		public Criteria andDeviceIdNotEqualTo(String value) {
			addCriterion("device_id <>", value, "deviceId");
			return this;
		}

		public Criteria andDeviceIdGreaterThan(String value) {
			addCriterion("device_id >", value, "deviceId");
			return this;
		}

		public Criteria andDeviceIdGreaterThanOrEqualTo(String value) {
			addCriterion("device_id >=", value, "deviceId");
			return this;
		}

		public Criteria andDeviceIdLessThan(String value) {
			addCriterion("device_id <", value, "deviceId");
			return this;
		}

		public Criteria andDeviceIdLessThanOrEqualTo(String value) {
			addCriterion("device_id <=", value, "deviceId");
			return this;
		}

		public Criteria andDeviceIdLike(String value) {
			addCriterion("device_id like", value, "deviceId");
			return this;
		}

		public Criteria andDeviceIdNotLike(String value) {
			addCriterion("device_id not like", value, "deviceId");
			return this;
		}

		public Criteria andDeviceIdIn(List<String> values) {
			addCriterion("device_id in", values, "deviceId");
			return this;
		}

		public Criteria andDeviceIdNotIn(List<String> values) {
			addCriterion("device_id not in", values, "deviceId");
			return this;
		}

		public Criteria andDeviceIdBetween(String value1, String value2) {
			addCriterion("device_id between", value1, value2, "deviceId");
			return this;
		}

		public Criteria andDeviceIdNotBetween(String value1, String value2) {
			addCriterion("device_id not between", value1, value2, "deviceId");
			return this;
		}

		public Criteria andDeviceNameIsNull() {
			addCriterion("device_name is null");
			return this;
		}

		public Criteria andDeviceNameIsNotNull() {
			addCriterion("device_name is not null");
			return this;
		}

		public Criteria andDeviceNameEqualTo(String value) {
			addCriterion("device_name =", value, "deviceName");
			return this;
		}

		public Criteria andDeviceNameNotEqualTo(String value) {
			addCriterion("device_name <>", value, "deviceName");
			return this;
		}

		public Criteria andDeviceNameGreaterThan(String value) {
			addCriterion("device_name >", value, "deviceName");
			return this;
		}

		public Criteria andDeviceNameGreaterThanOrEqualTo(String value) {
			addCriterion("device_name >=", value, "deviceName");
			return this;
		}

		public Criteria andDeviceNameLessThan(String value) {
			addCriterion("device_name <", value, "deviceName");
			return this;
		}

		public Criteria andDeviceNameLessThanOrEqualTo(String value) {
			addCriterion("device_name <=", value, "deviceName");
			return this;
		}

		public Criteria andDeviceNameLike(String value) {
			addCriterion("device_name like", value, "deviceName");
			return this;
		}

		public Criteria andDeviceNameNotLike(String value) {
			addCriterion("device_name not like", value, "deviceName");
			return this;
		}

		public Criteria andDeviceNameIn(List<String> values) {
			addCriterion("device_name in", values, "deviceName");
			return this;
		}

		public Criteria andDeviceNameNotIn(List<String> values) {
			addCriterion("device_name not in", values, "deviceName");
			return this;
		}

		public Criteria andDeviceNameBetween(String value1, String value2) {
			addCriterion("device_name between", value1, value2, "deviceName");
			return this;
		}

		public Criteria andDeviceNameNotBetween(String value1, String value2) {
			addCriterion("device_name not between", value1, value2,
					"deviceName");
			return this;
		}

		public Criteria andDeviceSystemIsNull() {
			addCriterion("device_system is null");
			return this;
		}

		public Criteria andDeviceSystemIsNotNull() {
			addCriterion("device_system is not null");
			return this;
		}

		public Criteria andDeviceSystemEqualTo(String value) {
			addCriterion("device_system =", value, "deviceSystem");
			return this;
		}

		public Criteria andDeviceSystemNotEqualTo(String value) {
			addCriterion("device_system <>", value, "deviceSystem");
			return this;
		}

		public Criteria andDeviceSystemGreaterThan(String value) {
			addCriterion("device_system >", value, "deviceSystem");
			return this;
		}

		public Criteria andDeviceSystemGreaterThanOrEqualTo(String value) {
			addCriterion("device_system >=", value, "deviceSystem");
			return this;
		}

		public Criteria andDeviceSystemLessThan(String value) {
			addCriterion("device_system <", value, "deviceSystem");
			return this;
		}

		public Criteria andDeviceSystemLessThanOrEqualTo(String value) {
			addCriterion("device_system <=", value, "deviceSystem");
			return this;
		}

		public Criteria andDeviceSystemLike(String value) {
			addCriterion("device_system like", value, "deviceSystem");
			return this;
		}

		public Criteria andDeviceSystemNotLike(String value) {
			addCriterion("device_system not like", value, "deviceSystem");
			return this;
		}

		public Criteria andDeviceSystemIn(List<String> values) {
			addCriterion("device_system in", values, "deviceSystem");
			return this;
		}

		public Criteria andDeviceSystemNotIn(List<String> values) {
			addCriterion("device_system not in", values, "deviceSystem");
			return this;
		}

		public Criteria andDeviceSystemBetween(String value1, String value2) {
			addCriterion("device_system between", value1, value2,
					"deviceSystem");
			return this;
		}

		public Criteria andDeviceSystemNotBetween(String value1, String value2) {
			addCriterion("device_system not between", value1, value2,
					"deviceSystem");
			return this;
		}

		public Criteria andActionIsNull() {
			addCriterion("action is null");
			return this;
		}

		public Criteria andActionIsNotNull() {
			addCriterion("action is not null");
			return this;
		}

		public Criteria andActionEqualTo(Integer value) {
			addCriterion("action =", value, "action");
			return this;
		}

		public Criteria andActionNotEqualTo(Integer value) {
			addCriterion("action <>", value, "action");
			return this;
		}

		public Criteria andActionGreaterThan(Integer value) {
			addCriterion("action >", value, "action");
			return this;
		}

		public Criteria andActionGreaterThanOrEqualTo(Integer value) {
			addCriterion("action >=", value, "action");
			return this;
		}

		public Criteria andActionLessThan(Integer value) {
			addCriterion("action <", value, "action");
			return this;
		}

		public Criteria andActionLessThanOrEqualTo(Integer value) {
			addCriterion("action <=", value, "action");
			return this;
		}

		public Criteria andActionIn(List<Integer> values) {
			addCriterion("action in", values, "action");
			return this;
		}

		public Criteria andActionNotIn(List<Integer> values) {
			addCriterion("action not in", values, "action");
			return this;
		}

		public Criteria andActionBetween(Integer value1, Integer value2) {
			addCriterion("action between", value1, value2, "action");
			return this;
		}

		public Criteria andActionNotBetween(Integer value1, Integer value2) {
			addCriterion("action not between", value1, value2, "action");
			return this;
		}

		public Criteria andUpdateTimeIsNull() {
			addCriterion("update_time is null");
			return this;
		}

		public Criteria andUpdateTimeIsNotNull() {
			addCriterion("update_time is not null");
			return this;
		}

		public Criteria andUpdateTimeEqualTo(Date value) {
			addCriterion("update_time =", value, "updateTime");
			return this;
		}

		public Criteria andUpdateTimeNotEqualTo(Date value) {
			addCriterion("update_time <>", value, "updateTime");
			return this;
		}

		public Criteria andUpdateTimeGreaterThan(Date value) {
			addCriterion("update_time >", value, "updateTime");
			return this;
		}

		public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("update_time >=", value, "updateTime");
			return this;
		}

		public Criteria andUpdateTimeLessThan(Date value) {
			addCriterion("update_time <", value, "updateTime");
			return this;
		}

		public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
			addCriterion("update_time <=", value, "updateTime");
			return this;
		}

		public Criteria andUpdateTimeIn(List<Date> values) {
			addCriterion("update_time in", values, "updateTime");
			return this;
		}

		public Criteria andUpdateTimeNotIn(List<Date> values) {
			addCriterion("update_time not in", values, "updateTime");
			return this;
		}

		public Criteria andUpdateTimeBetween(Date value1, Date value2) {
			addCriterion("update_time between", value1, value2, "updateTime");
			return this;
		}

		public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
			addCriterion("update_time not between", value1, value2,
					"updateTime");
			return this;
		}
	}
}