package com.zhela.cloudblog.model.internalnews;

import java.util.Date;

public class TextNews {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column text_news.id
     *
     * @ibatorgenerated Fri Oct 22 23:22:19 CST 2010
     */
    private Long id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column text_news.provider_id
     *
     * @ibatorgenerated Fri Oct 22 23:22:19 CST 2010
     */
    private Long providerId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column text_news.tweet_id
     *
     * @ibatorgenerated Fri Oct 22 23:22:19 CST 2010
     */
    private String tweetId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column text_news.tweet_name
     *
     * @ibatorgenerated Fri Oct 22 23:22:19 CST 2010
     */
    private String tweetName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column text_news.tweet_header
     *
     * @ibatorgenerated Fri Oct 22 23:22:19 CST 2010
     */
    private String tweetHeader;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column text_news.title
     *
     * @ibatorgenerated Fri Oct 22 23:22:19 CST 2010
     */
    private String title;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column text_news.update_time
     *
     * @ibatorgenerated Fri Oct 22 23:22:19 CST 2010
     */
    private Date updateTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column text_news.description
     *
     * @ibatorgenerated Fri Oct 22 23:22:19 CST 2010
     */
    private String description;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column text_news.id
     *
     * @return the value of text_news.id
     *
     * @ibatorgenerated Fri Oct 22 23:22:19 CST 2010
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column text_news.id
     *
     * @param id the value for text_news.id
     *
     * @ibatorgenerated Fri Oct 22 23:22:19 CST 2010
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column text_news.provider_id
     *
     * @return the value of text_news.provider_id
     *
     * @ibatorgenerated Fri Oct 22 23:22:19 CST 2010
     */
    public Long getProviderId() {
        return providerId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column text_news.provider_id
     *
     * @param providerId the value for text_news.provider_id
     *
     * @ibatorgenerated Fri Oct 22 23:22:19 CST 2010
     */
    public void setProviderId(Long providerId) {
        this.providerId = providerId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column text_news.tweet_id
     *
     * @return the value of text_news.tweet_id
     *
     * @ibatorgenerated Fri Oct 22 23:22:19 CST 2010
     */
    public String getTweetId() {
        return tweetId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column text_news.tweet_id
     *
     * @param tweetId the value for text_news.tweet_id
     *
     * @ibatorgenerated Fri Oct 22 23:22:19 CST 2010
     */
    public void setTweetId(String tweetId) {
        this.tweetId = tweetId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column text_news.tweet_name
     *
     * @return the value of text_news.tweet_name
     *
     * @ibatorgenerated Fri Oct 22 23:22:19 CST 2010
     */
    public String getTweetName() {
        return tweetName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column text_news.tweet_name
     *
     * @param tweetName the value for text_news.tweet_name
     *
     * @ibatorgenerated Fri Oct 22 23:22:19 CST 2010
     */
    public void setTweetName(String tweetName) {
        this.tweetName = tweetName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column text_news.tweet_header
     *
     * @return the value of text_news.tweet_header
     *
     * @ibatorgenerated Fri Oct 22 23:22:19 CST 2010
     */
    public String getTweetHeader() {
        return tweetHeader;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column text_news.tweet_header
     *
     * @param tweetHeader the value for text_news.tweet_header
     *
     * @ibatorgenerated Fri Oct 22 23:22:19 CST 2010
     */
    public void setTweetHeader(String tweetHeader) {
        this.tweetHeader = tweetHeader;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column text_news.title
     *
     * @return the value of text_news.title
     *
     * @ibatorgenerated Fri Oct 22 23:22:19 CST 2010
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column text_news.title
     *
     * @param title the value for text_news.title
     *
     * @ibatorgenerated Fri Oct 22 23:22:19 CST 2010
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column text_news.update_time
     *
     * @return the value of text_news.update_time
     *
     * @ibatorgenerated Fri Oct 22 23:22:19 CST 2010
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column text_news.update_time
     *
     * @param updateTime the value for text_news.update_time
     *
     * @ibatorgenerated Fri Oct 22 23:22:19 CST 2010
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column text_news.description
     *
     * @return the value of text_news.description
     *
     * @ibatorgenerated Fri Oct 22 23:22:19 CST 2010
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column text_news.description
     *
     * @param description the value for text_news.description
     *
     * @ibatorgenerated Fri Oct 22 23:22:19 CST 2010
     */
    public void setDescription(String description) {
        this.description = description;
    }
}