package com.zhelazhela.db.model;

import java.util.Date;

import org.apache.commons.lang.StringUtils;

public class BlogQa {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column blog_qa.id
     *
     * @ibatorgenerated Sun Jan 31 12:38:51 CST 2010
     */
    private Long id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column blog_qa.user_name
     *
     * @ibatorgenerated Sun Jan 31 12:38:51 CST 2010
     */
    private String userName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column blog_qa.user_email
     *
     * @ibatorgenerated Sun Jan 31 12:38:51 CST 2010
     */
    private String userEmail;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column blog_qa.title
     *
     * @ibatorgenerated Sun Jan 31 12:38:51 CST 2010
     */
    private String title;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column blog_qa.content
     *
     * @ibatorgenerated Sun Jan 31 12:38:51 CST 2010
     */
    private String content;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column blog_qa.comment_time
     *
     * @ibatorgenerated Sun Jan 31 12:38:51 CST 2010
     */
    private Date commentTime;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column blog_qa.id
     *
     * @return the value of blog_qa.id
     *
     * @ibatorgenerated Sun Jan 31 12:38:51 CST 2010
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column blog_qa.id
     *
     * @param id the value for blog_qa.id
     *
     * @ibatorgenerated Sun Jan 31 12:38:51 CST 2010
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column blog_qa.user_name
     *
     * @return the value of blog_qa.user_name
     *
     * @ibatorgenerated Sun Jan 31 12:38:51 CST 2010
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column blog_qa.user_name
     *
     * @param userName the value for blog_qa.user_name
     *
     * @ibatorgenerated Sun Jan 31 12:38:51 CST 2010
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column blog_qa.user_email
     *
     * @return the value of blog_qa.user_email
     *
     * @ibatorgenerated Sun Jan 31 12:38:51 CST 2010
     */
    public String getUserEmail() {
        return userEmail;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column blog_qa.user_email
     *
     * @param userEmail the value for blog_qa.user_email
     *
     * @ibatorgenerated Sun Jan 31 12:38:51 CST 2010
     */
    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column blog_qa.title
     *
     * @return the value of blog_qa.title
     *
     * @ibatorgenerated Sun Jan 31 12:38:51 CST 2010
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column blog_qa.title
     *
     * @param title the value for blog_qa.title
     *
     * @ibatorgenerated Sun Jan 31 12:38:51 CST 2010
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column blog_qa.content
     *
     * @return the value of blog_qa.content
     *
     * @ibatorgenerated Sun Jan 31 12:38:51 CST 2010
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column blog_qa.content
     *
     * @param content the value for blog_qa.content
     *
     * @ibatorgenerated Sun Jan 31 12:38:51 CST 2010
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column blog_qa.comment_time
     *
     * @return the value of blog_qa.comment_time
     *
     * @ibatorgenerated Sun Jan 31 12:38:51 CST 2010
     */
    public Date getCommentTime() {
        return commentTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column blog_qa.comment_time
     *
     * @param commentTime the value for blog_qa.comment_time
     *
     * @ibatorgenerated Sun Jan 31 12:38:51 CST 2010
     */
    public void setCommentTime(Date commentTime) {
        this.commentTime = commentTime;
    }
    
    public boolean isValid(){
    	if(StringUtils.isNotBlank(title)&&StringUtils.isNotBlank(userName)&&StringUtils.isNotBlank(userEmail)&&StringUtils.isNotBlank(content)){
    		return true;
    	}
    	return false;
    }
}