package com.zhelazhela.db.model;

import java.util.Date;

public class Certification {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column certification.id
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    private Long id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column certification.name
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    private String name;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column certification.icon
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    private String icon;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column certification.description
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    private String description;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column certification.update_time
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    private Date updateTime;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column certification.id
     *
     * @return the value of certification.id
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column certification.id
     *
     * @param id the value for certification.id
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column certification.name
     *
     * @return the value of certification.name
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column certification.name
     *
     * @param name the value for certification.name
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column certification.icon
     *
     * @return the value of certification.icon
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column certification.icon
     *
     * @param icon the value for certification.icon
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    public void setIcon(String icon) {
        this.icon = icon;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column certification.description
     *
     * @return the value of certification.description
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column certification.description
     *
     * @param description the value for certification.description
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column certification.update_time
     *
     * @return the value of certification.update_time
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column certification.update_time
     *
     * @param updateTime the value for certification.update_time
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}