package com.zhelazhela.db.model;

import java.util.Date;

public class Providers {
	
	public final static int LEVEL_OK = 1;
	
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column providers.id
     *
     * @ibatorgenerated Tue Sep 07 09:56:04 GMT+08:00 2010
     */
    private Long id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column providers.name
     *
     * @ibatorgenerated Tue Sep 07 09:56:04 GMT+08:00 2010
     */
    private String name;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column providers.title
     *
     * @ibatorgenerated Tue Sep 07 09:56:04 GMT+08:00 2010
     */
    private String title;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column providers.img
     *
     * @ibatorgenerated Tue Sep 07 09:56:04 GMT+08:00 2010
     */
    private String img;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column providers.domain
     *
     * @ibatorgenerated Tue Sep 07 09:56:04 GMT+08:00 2010
     */
    private String domain;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column providers.level
     *
     * @ibatorgenerated Tue Sep 07 09:56:04 GMT+08:00 2010
     */
    private Integer level;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column providers.reg_time
     *
     * @ibatorgenerated Tue Sep 07 09:56:04 GMT+08:00 2010
     */
    private Date regTime;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column providers.id
     *
     * @return the value of providers.id
     *
     * @ibatorgenerated Tue Sep 07 09:56:04 GMT+08:00 2010
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column providers.id
     *
     * @param id the value for providers.id
     *
     * @ibatorgenerated Tue Sep 07 09:56:04 GMT+08:00 2010
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column providers.name
     *
     * @return the value of providers.name
     *
     * @ibatorgenerated Tue Sep 07 09:56:04 GMT+08:00 2010
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column providers.name
     *
     * @param name the value for providers.name
     *
     * @ibatorgenerated Tue Sep 07 09:56:04 GMT+08:00 2010
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column providers.title
     *
     * @return the value of providers.title
     *
     * @ibatorgenerated Tue Sep 07 09:56:04 GMT+08:00 2010
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column providers.title
     *
     * @param title the value for providers.title
     *
     * @ibatorgenerated Tue Sep 07 09:56:04 GMT+08:00 2010
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column providers.img
     *
     * @return the value of providers.img
     *
     * @ibatorgenerated Tue Sep 07 09:56:04 GMT+08:00 2010
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column providers.img
     *
     * @param img the value for providers.img
     *
     * @ibatorgenerated Tue Sep 07 09:56:04 GMT+08:00 2010
     */
    public void setImg(String img) {
        this.img = img;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column providers.domain
     *
     * @return the value of providers.domain
     *
     * @ibatorgenerated Tue Sep 07 09:56:04 GMT+08:00 2010
     */
    public String getDomain() {
        return domain;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column providers.domain
     *
     * @param domain the value for providers.domain
     *
     * @ibatorgenerated Tue Sep 07 09:56:04 GMT+08:00 2010
     */
    public void setDomain(String domain) {
        this.domain = domain;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column providers.level
     *
     * @return the value of providers.level
     *
     * @ibatorgenerated Tue Sep 07 09:56:04 GMT+08:00 2010
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column providers.level
     *
     * @param level the value for providers.level
     *
     * @ibatorgenerated Tue Sep 07 09:56:04 GMT+08:00 2010
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column providers.reg_time
     *
     * @return the value of providers.reg_time
     *
     * @ibatorgenerated Tue Sep 07 09:56:04 GMT+08:00 2010
     */
    public Date getRegTime() {
        return regTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column providers.reg_time
     *
     * @param regTime the value for providers.reg_time
     *
     * @ibatorgenerated Tue Sep 07 09:56:04 GMT+08:00 2010
     */
    public void setRegTime(Date regTime) {
        this.regTime = regTime;
    }
}