package com.zhelazhela.db.model;

public class SecurityQuestion {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column security_question.id
     *
     * @ibatorgenerated Fri Feb 12 23:38:36 CST 2010
     */
    private Long id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column security_question.question
     *
     * @ibatorgenerated Fri Feb 12 23:38:36 CST 2010
     */
    private String question;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column security_question.id
     *
     * @return the value of security_question.id
     *
     * @ibatorgenerated Fri Feb 12 23:38:36 CST 2010
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column security_question.id
     *
     * @param id the value for security_question.id
     *
     * @ibatorgenerated Fri Feb 12 23:38:36 CST 2010
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column security_question.question
     *
     * @return the value of security_question.question
     *
     * @ibatorgenerated Fri Feb 12 23:38:36 CST 2010
     */
    public String getQuestion() {
        return question;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column security_question.question
     *
     * @param question the value for security_question.question
     *
     * @ibatorgenerated Fri Feb 12 23:38:36 CST 2010
     */
    public void setQuestion(String question) {
        this.question = question;
    }
}