package com.zhela.cloudblog.dao.ourservice.impl;

import com.zhela.cloudblog.dao.ourservice.CommentDAO;
import com.zhela.cloudblog.model.ourservice.Comment;
import com.zhela.cloudblog.model.ourservice.CommentExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class CommentDAOImpl extends SqlMapClientDaoSupport implements CommentDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table comment
     *
     * @ibatorgenerated Mon Nov 29 14:02:02 CST 2010
     */
    public CommentDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table comment
     *
     * @ibatorgenerated Mon Nov 29 14:02:02 CST 2010
     */
    public int countByExample(CommentExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("comment.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table comment
     *
     * @ibatorgenerated Mon Nov 29 14:02:02 CST 2010
     */
    public int deleteByExample(CommentExample example) {
        int rows = getSqlMapClientTemplate().delete("comment.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table comment
     *
     * @ibatorgenerated Mon Nov 29 14:02:02 CST 2010
     */
    public int deleteByPrimaryKey(Long id) {
        Comment key = new Comment();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("comment.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table comment
     *
     * @ibatorgenerated Mon Nov 29 14:02:02 CST 2010
     */
    public void insert(Comment record) {
        getSqlMapClientTemplate().insert("comment.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table comment
     *
     * @ibatorgenerated Mon Nov 29 14:02:02 CST 2010
     */
    public void insertSelective(Comment record) {
        getSqlMapClientTemplate().insert("comment.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table comment
     *
     * @ibatorgenerated Mon Nov 29 14:02:02 CST 2010
     */
    @SuppressWarnings("unchecked")
    public List<Comment> selectByExampleWithBLOBs(CommentExample example) {
        List<Comment> list = getSqlMapClientTemplate().queryForList("comment.ibatorgenerated_selectByExampleWithBLOBs", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table comment
     *
     * @ibatorgenerated Mon Nov 29 14:02:02 CST 2010
     */
    @SuppressWarnings("unchecked")
    public List<Comment> selectByExampleWithoutBLOBs(CommentExample example) {
        List<Comment> list = getSqlMapClientTemplate().queryForList("comment.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table comment
     *
     * @ibatorgenerated Mon Nov 29 14:02:02 CST 2010
     */
    public Comment selectByPrimaryKey(Long id) {
        Comment key = new Comment();
        key.setId(id);
        Comment record = (Comment) getSqlMapClientTemplate().queryForObject("comment.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table comment
     *
     * @ibatorgenerated Mon Nov 29 14:02:02 CST 2010
     */
    public int updateByExampleSelective(Comment record, CommentExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("comment.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table comment
     *
     * @ibatorgenerated Mon Nov 29 14:02:02 CST 2010
     */
    public int updateByExampleWithBLOBs(Comment record, CommentExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("comment.ibatorgenerated_updateByExampleWithBLOBs", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table comment
     *
     * @ibatorgenerated Mon Nov 29 14:02:02 CST 2010
     */
    public int updateByExampleWithoutBLOBs(Comment record, CommentExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("comment.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table comment
     *
     * @ibatorgenerated Mon Nov 29 14:02:02 CST 2010
     */
    public int updateByPrimaryKeySelective(Comment record) {
        int rows = getSqlMapClientTemplate().update("comment.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table comment
     *
     * @ibatorgenerated Mon Nov 29 14:02:02 CST 2010
     */
    public int updateByPrimaryKeyWithBLOBs(Comment record) {
        int rows = getSqlMapClientTemplate().update("comment.ibatorgenerated_updateByPrimaryKeyWithBLOBs", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table comment
     *
     * @ibatorgenerated Mon Nov 29 14:02:02 CST 2010
     */
    public int updateByPrimaryKeyWithoutBLOBs(Comment record) {
        int rows = getSqlMapClientTemplate().update("comment.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table comment
     *
     * @ibatorgenerated Mon Nov 29 14:02:02 CST 2010
     */
    private static class UpdateByExampleParms extends CommentExample {
        private Object record;

        public UpdateByExampleParms(Object record, CommentExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}