package com.zhela.cloudblog.dao.ourservice;

import com.zhela.cloudblog.model.ourservice.MakeBetter;
import com.zhela.cloudblog.model.ourservice.MakeBetterExample;
import java.util.List;

public interface MakeBetterDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table make_better
     *
     * @ibatorgenerated Fri Dec 10 17:02:49 CST 2010
     */
    int countByExample(MakeBetterExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table make_better
     *
     * @ibatorgenerated Fri Dec 10 17:02:49 CST 2010
     */
    int deleteByExample(MakeBetterExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table make_better
     *
     * @ibatorgenerated Fri Dec 10 17:02:49 CST 2010
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table make_better
     *
     * @ibatorgenerated Fri Dec 10 17:02:49 CST 2010
     */
    void insert(MakeBetter record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table make_better
     *
     * @ibatorgenerated Fri Dec 10 17:02:49 CST 2010
     */
    void insertSelective(MakeBetter record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table make_better
     *
     * @ibatorgenerated Fri Dec 10 17:02:49 CST 2010
     */
    List<MakeBetter> selectByExampleWithBLOBs(MakeBetterExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table make_better
     *
     * @ibatorgenerated Fri Dec 10 17:02:49 CST 2010
     */
    List<MakeBetter> selectByExampleWithoutBLOBs(MakeBetterExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table make_better
     *
     * @ibatorgenerated Fri Dec 10 17:02:49 CST 2010
     */
    MakeBetter selectByPrimaryKey(Long id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table make_better
     *
     * @ibatorgenerated Fri Dec 10 17:02:49 CST 2010
     */
    int updateByExampleSelective(MakeBetter record, MakeBetterExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table make_better
     *
     * @ibatorgenerated Fri Dec 10 17:02:49 CST 2010
     */
    int updateByExampleWithBLOBs(MakeBetter record, MakeBetterExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table make_better
     *
     * @ibatorgenerated Fri Dec 10 17:02:49 CST 2010
     */
    int updateByExampleWithoutBLOBs(MakeBetter record, MakeBetterExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table make_better
     *
     * @ibatorgenerated Fri Dec 10 17:02:49 CST 2010
     */
    int updateByPrimaryKeySelective(MakeBetter record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table make_better
     *
     * @ibatorgenerated Fri Dec 10 17:02:49 CST 2010
     */
    int updateByPrimaryKeyWithBLOBs(MakeBetter record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table make_better
     *
     * @ibatorgenerated Fri Dec 10 17:02:49 CST 2010
     */
    int updateByPrimaryKeyWithoutBLOBs(MakeBetter record);
}