package com.zhelazhela.db.dao;

import com.zhelazhela.db.model.BaseProfile;
import com.zhelazhela.db.model.BaseProfileExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class BaseProfileDAOImpl extends SqlMapClientDaoSupport implements BaseProfileDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table base_profile
	 * @ibatorgenerated  Sun Feb 14 17:18:03 CST 2010
	 */
	public BaseProfileDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table base_profile
	 * @ibatorgenerated  Sun Feb 14 17:18:03 CST 2010
	 */
	public int countByExample(BaseProfileExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"base_profile.ibatorgenerated_countByExample", example);
		return count;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table base_profile
	 * @ibatorgenerated  Sun Feb 14 17:18:03 CST 2010
	 */
	public int deleteByExample(BaseProfileExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"base_profile.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table base_profile
	 * @ibatorgenerated  Sun Feb 14 17:18:03 CST 2010
	 */
	public int deleteByPrimaryKey(Long userId) {
		BaseProfile key = new BaseProfile();
		key.setUserId(userId);
		int rows = getSqlMapClientTemplate().delete(
				"base_profile.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table base_profile
	 * @ibatorgenerated  Sun Feb 14 17:18:03 CST 2010
	 */
	public void insert(BaseProfile record) {
		getSqlMapClientTemplate().insert("base_profile.ibatorgenerated_insert",
				record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table base_profile
	 * @ibatorgenerated  Sun Feb 14 17:18:03 CST 2010
	 */
	public void insertSelective(BaseProfile record) {
		getSqlMapClientTemplate().insert(
				"base_profile.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table base_profile
	 * @ibatorgenerated  Sun Feb 14 17:18:03 CST 2010
	 */
	@SuppressWarnings("unchecked")
	public List<BaseProfile> selectByExample(BaseProfileExample example) {
		List<BaseProfile> list = getSqlMapClientTemplate().queryForList(
				"base_profile.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table base_profile
	 * @ibatorgenerated  Sun Feb 14 17:18:03 CST 2010
	 */
	public BaseProfile selectByPrimaryKey(Long userId) {
		BaseProfile key = new BaseProfile();
		key.setUserId(userId);
		BaseProfile record = (BaseProfile) getSqlMapClientTemplate()
				.queryForObject(
						"base_profile.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table base_profile
	 * @ibatorgenerated  Sun Feb 14 17:18:03 CST 2010
	 */
	public int updateByExampleSelective(BaseProfile record,
			BaseProfileExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"base_profile.ibatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table base_profile
	 * @ibatorgenerated  Sun Feb 14 17:18:03 CST 2010
	 */
	public int updateByExample(BaseProfile record, BaseProfileExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"base_profile.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table base_profile
	 * @ibatorgenerated  Sun Feb 14 17:18:03 CST 2010
	 */
	public int updateByPrimaryKeySelective(BaseProfile record) {
		int rows = getSqlMapClientTemplate().update(
				"base_profile.ibatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table base_profile
	 * @ibatorgenerated  Sun Feb 14 17:18:03 CST 2010
	 */
	public int updateByPrimaryKey(BaseProfile record) {
		int rows = getSqlMapClientTemplate().update(
				"base_profile.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table base_profile
	 * @ibatorgenerated  Sun Feb 14 17:18:03 CST 2010
	 */
	private static class UpdateByExampleParms extends BaseProfileExample {
		private Object record;

		public UpdateByExampleParms(Object record, BaseProfileExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}