package com.zhelazhela.db.dao;

import com.zhelazhela.db.model.BlockUser;
import com.zhelazhela.db.model.BlockUserExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class BlockUserDAOImpl extends SqlMapClientDaoSupport implements BlockUserDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table block_user
     *
     * @ibatorgenerated Fri Feb 12 23:38:36 CST 2010
     */
    public BlockUserDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table block_user
     *
     * @ibatorgenerated Fri Feb 12 23:38:36 CST 2010
     */
    public int countByExample(BlockUserExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("block_user.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table block_user
     *
     * @ibatorgenerated Fri Feb 12 23:38:36 CST 2010
     */
    public int deleteByExample(BlockUserExample example) {
        int rows = getSqlMapClientTemplate().delete("block_user.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table block_user
     *
     * @ibatorgenerated Fri Feb 12 23:38:36 CST 2010
     */
    public void insert(BlockUser record) {
        getSqlMapClientTemplate().insert("block_user.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table block_user
     *
     * @ibatorgenerated Fri Feb 12 23:38:36 CST 2010
     */
    public void insertSelective(BlockUser record) {
        getSqlMapClientTemplate().insert("block_user.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table block_user
     *
     * @ibatorgenerated Fri Feb 12 23:38:36 CST 2010
     */
    @SuppressWarnings("unchecked")
    public List<BlockUser> selectByExample(BlockUserExample example) {
        List<BlockUser> list = getSqlMapClientTemplate().queryForList("block_user.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table block_user
     *
     * @ibatorgenerated Fri Feb 12 23:38:36 CST 2010
     */
    public int updateByExampleSelective(BlockUser record, BlockUserExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("block_user.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table block_user
     *
     * @ibatorgenerated Fri Feb 12 23:38:36 CST 2010
     */
    public int updateByExample(BlockUser record, BlockUserExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("block_user.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table block_user
     *
     * @ibatorgenerated Fri Feb 12 23:38:36 CST 2010
     */
    private static class UpdateByExampleParms extends BlockUserExample {
        private Object record;

        public UpdateByExampleParms(Object record, BlockUserExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}