package com.zhelazhela.db.dao;

import com.zhelazhela.db.model.BlogQa;
import com.zhelazhela.db.model.BlogQaExample;
import java.util.List;

public interface BlogQaDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table blog_qa
     *
     * @ibatorgenerated Sun Jan 31 12:38:51 CST 2010
     */
    int countByExample(BlogQaExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table blog_qa
     *
     * @ibatorgenerated Sun Jan 31 12:38:51 CST 2010
     */
    int deleteByExample(BlogQaExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table blog_qa
     *
     * @ibatorgenerated Sun Jan 31 12:38:51 CST 2010
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table blog_qa
     *
     * @ibatorgenerated Sun Jan 31 12:38:51 CST 2010
     */
    void insert(BlogQa record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table blog_qa
     *
     * @ibatorgenerated Sun Jan 31 12:38:51 CST 2010
     */
    void insertSelective(BlogQa record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table blog_qa
     *
     * @ibatorgenerated Sun Jan 31 12:38:51 CST 2010
     */
    List<BlogQa> selectByExample(BlogQaExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table blog_qa
     *
     * @ibatorgenerated Sun Jan 31 12:38:51 CST 2010
     */
    BlogQa selectByPrimaryKey(Long id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table blog_qa
     *
     * @ibatorgenerated Sun Jan 31 12:38:51 CST 2010
     */
    int updateByExampleSelective(BlogQa record, BlogQaExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table blog_qa
     *
     * @ibatorgenerated Sun Jan 31 12:38:51 CST 2010
     */
    int updateByExample(BlogQa record, BlogQaExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table blog_qa
     *
     * @ibatorgenerated Sun Jan 31 12:38:51 CST 2010
     */
    int updateByPrimaryKeySelective(BlogQa record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table blog_qa
     *
     * @ibatorgenerated Sun Jan 31 12:38:51 CST 2010
     */
    int updateByPrimaryKey(BlogQa record);
}