package com.zhelazhela.db.dao;

import com.zhelazhela.db.model.City;
import com.zhelazhela.db.model.CityExample;
import java.util.List;

public interface CityDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table city
     *
     * @ibatorgenerated Fri Dec 18 11:08:41 CST 2009
     */
    int countByExample(CityExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table city
     *
     * @ibatorgenerated Fri Dec 18 11:08:41 CST 2009
     */
    int deleteByExample(CityExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table city
     *
     * @ibatorgenerated Fri Dec 18 11:08:41 CST 2009
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table city
     *
     * @ibatorgenerated Fri Dec 18 11:08:41 CST 2009
     */
    void insert(City record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table city
     *
     * @ibatorgenerated Fri Dec 18 11:08:41 CST 2009
     */
    void insertSelective(City record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table city
     *
     * @ibatorgenerated Fri Dec 18 11:08:41 CST 2009
     */
    List<City> selectByExample(CityExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table city
     *
     * @ibatorgenerated Fri Dec 18 11:08:41 CST 2009
     */
    City selectByPrimaryKey(Long id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table city
     *
     * @ibatorgenerated Fri Dec 18 11:08:41 CST 2009
     */
    int updateByExampleSelective(City record, CityExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table city
     *
     * @ibatorgenerated Fri Dec 18 11:08:41 CST 2009
     */
    int updateByExample(City record, CityExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table city
     *
     * @ibatorgenerated Fri Dec 18 11:08:41 CST 2009
     */
    int updateByPrimaryKeySelective(City record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table city
     *
     * @ibatorgenerated Fri Dec 18 11:08:41 CST 2009
     */
    int updateByPrimaryKey(City record);
}