package com.zhelazhela.db.dao;

import com.zhelazhela.db.model.DiscountNews;
import com.zhelazhela.db.model.DiscountNewsExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class DiscountNewsDAOImpl extends SqlMapClientDaoSupport implements DiscountNewsDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table discount_news
     *
     * @ibatorgenerated Fri Dec 18 16:20:44 CST 2009
     */
    public DiscountNewsDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table discount_news
     *
     * @ibatorgenerated Fri Dec 18 16:20:44 CST 2009
     */
    public int countByExample(DiscountNewsExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("discount_news.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table discount_news
     *
     * @ibatorgenerated Fri Dec 18 16:20:44 CST 2009
     */
    public int deleteByExample(DiscountNewsExample example) {
        int rows = getSqlMapClientTemplate().delete("discount_news.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table discount_news
     *
     * @ibatorgenerated Fri Dec 18 16:20:44 CST 2009
     */
    public int deleteByPrimaryKey(Long id) {
        DiscountNews key = new DiscountNews();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("discount_news.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table discount_news
     *
     * @ibatorgenerated Fri Dec 18 16:20:44 CST 2009
     */
    public void insert(DiscountNews record) {
        getSqlMapClientTemplate().insert("discount_news.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table discount_news
     *
     * @ibatorgenerated Fri Dec 18 16:20:44 CST 2009
     */
    public void insertSelective(DiscountNews record) {
        getSqlMapClientTemplate().insert("discount_news.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table discount_news
     *
     * @ibatorgenerated Fri Dec 18 16:20:44 CST 2009
     */
    @SuppressWarnings("unchecked")
    public List<DiscountNews> selectByExampleWithBLOBs(DiscountNewsExample example) {
        List<DiscountNews> list = getSqlMapClientTemplate().queryForList("discount_news.ibatorgenerated_selectByExampleWithBLOBs", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table discount_news
     *
     * @ibatorgenerated Fri Dec 18 16:20:44 CST 2009
     */
    @SuppressWarnings("unchecked")
    public List<DiscountNews> selectByExampleWithoutBLOBs(DiscountNewsExample example) {
        List<DiscountNews> list = getSqlMapClientTemplate().queryForList("discount_news.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table discount_news
     *
     * @ibatorgenerated Fri Dec 18 16:20:44 CST 2009
     */
    public DiscountNews selectByPrimaryKey(Long id) {
        DiscountNews key = new DiscountNews();
        key.setId(id);
        DiscountNews record = (DiscountNews) getSqlMapClientTemplate().queryForObject("discount_news.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table discount_news
     *
     * @ibatorgenerated Fri Dec 18 16:20:44 CST 2009
     */
    public int updateByExampleSelective(DiscountNews record, DiscountNewsExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("discount_news.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table discount_news
     *
     * @ibatorgenerated Fri Dec 18 16:20:44 CST 2009
     */
    public int updateByExampleWithBLOBs(DiscountNews record, DiscountNewsExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("discount_news.ibatorgenerated_updateByExampleWithBLOBs", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table discount_news
     *
     * @ibatorgenerated Fri Dec 18 16:20:44 CST 2009
     */
    public int updateByExampleWithoutBLOBs(DiscountNews record, DiscountNewsExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("discount_news.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table discount_news
     *
     * @ibatorgenerated Fri Dec 18 16:20:44 CST 2009
     */
    public int updateByPrimaryKeySelective(DiscountNews record) {
        int rows = getSqlMapClientTemplate().update("discount_news.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table discount_news
     *
     * @ibatorgenerated Fri Dec 18 16:20:44 CST 2009
     */
    public int updateByPrimaryKeyWithBLOBs(DiscountNews record) {
        int rows = getSqlMapClientTemplate().update("discount_news.ibatorgenerated_updateByPrimaryKeyWithBLOBs", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table discount_news
     *
     * @ibatorgenerated Fri Dec 18 16:20:44 CST 2009
     */
    public int updateByPrimaryKeyWithoutBLOBs(DiscountNews record) {
        int rows = getSqlMapClientTemplate().update("discount_news.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table discount_news
     *
     * @ibatorgenerated Fri Dec 18 16:20:44 CST 2009
     */
    private static class UpdateByExampleParms extends DiscountNewsExample {
        private Object record;

        public UpdateByExampleParms(Object record, DiscountNewsExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }

	@Override
	public long insertSelectiveReturnId(DiscountNews record) {
		return (Long)getSqlMapClientTemplate().insert("discount_news.insertSelective_returnId", record);
	}

	@SuppressWarnings("unchecked")
	@Override
	public List<DiscountNews> selectWithProgramInfoByExampleWithoutBLOBs(
			DiscountNewsExample example) {
		 List<DiscountNews> list = getSqlMapClientTemplate().queryForList("discount_news.dicount_news_programInfo", example);
		 return list;
	}
	
	public DiscountNews selectWithProgramInfoByPrimaryKey(Long id) {
        DiscountNews key = new DiscountNews();
        key.setId(id);
        DiscountNews record = (DiscountNews) getSqlMapClientTemplate().queryForObject("discount_news.selectWithProgramInfoByPrimaryKey", key);
        return record;
    }
}