package com.zhelazhela.db.dao;

import com.zhelazhela.db.model.DiscountInfo;
import com.zhelazhela.db.model.DiscountInfoExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class DiscountInfoDAOImpl extends SqlMapClientDaoSupport implements DiscountInfoDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table discount_info
	 * @ibatorgenerated  Fri Dec 18 11:08:41 CST 2009
	 */
	public DiscountInfoDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table discount_info
	 * @ibatorgenerated  Fri Dec 18 11:08:41 CST 2009
	 */
	public int countByExample(DiscountInfoExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"discount_info.ibatorgenerated_countByExample", example);
		return count;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table discount_info
	 * @ibatorgenerated  Fri Dec 18 11:08:41 CST 2009
	 */
	public int deleteByExample(DiscountInfoExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"discount_info.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table discount_info
	 * @ibatorgenerated  Fri Dec 18 11:08:41 CST 2009
	 */
	public int deleteByPrimaryKey(Long id) {
		DiscountInfo key = new DiscountInfo();
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete(
				"discount_info.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table discount_info
	 * @ibatorgenerated  Fri Dec 18 11:08:41 CST 2009
	 */
	public void insert(DiscountInfo record) {
		getSqlMapClientTemplate().insert(
				"discount_info.ibatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table discount_info
	 * @ibatorgenerated  Fri Dec 18 11:08:41 CST 2009
	 */
	public void insertSelective(DiscountInfo record) {
		getSqlMapClientTemplate().insert(
				"discount_info.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table discount_info
	 * @ibatorgenerated  Fri Dec 18 11:08:41 CST 2009
	 */
	@SuppressWarnings("unchecked")
	public List<DiscountInfo> selectByExampleWithBLOBs(
			DiscountInfoExample example) {
		List<DiscountInfo> list = getSqlMapClientTemplate().queryForList(
				"discount_info.ibatorgenerated_selectByExampleWithBLOBs",
				example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table discount_info
	 * @ibatorgenerated  Fri Dec 18 11:08:41 CST 2009
	 */
	@SuppressWarnings("unchecked")
	public List<DiscountInfo> selectByExampleWithoutBLOBs(
			DiscountInfoExample example) {
		List<DiscountInfo> list = getSqlMapClientTemplate().queryForList(
				"discount_info.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table discount_info
	 * @ibatorgenerated  Fri Dec 18 11:08:41 CST 2009
	 */
	public DiscountInfo selectByPrimaryKey(Long id) {
		DiscountInfo key = new DiscountInfo();
		key.setId(id);
		DiscountInfo record = (DiscountInfo) getSqlMapClientTemplate()
				.queryForObject(
						"discount_info.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table discount_info
	 * @ibatorgenerated  Fri Dec 18 11:08:41 CST 2009
	 */
	public int updateByExampleSelective(DiscountInfo record,
			DiscountInfoExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate()
				.update(
						"discount_info.ibatorgenerated_updateByExampleSelective",
						parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table discount_info
	 * @ibatorgenerated  Fri Dec 18 11:08:41 CST 2009
	 */
	public int updateByExampleWithBLOBs(DiscountInfo record,
			DiscountInfoExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate()
				.update(
						"discount_info.ibatorgenerated_updateByExampleWithBLOBs",
						parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table discount_info
	 * @ibatorgenerated  Fri Dec 18 11:08:41 CST 2009
	 */
	public int updateByExampleWithoutBLOBs(DiscountInfo record,
			DiscountInfoExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"discount_info.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table discount_info
	 * @ibatorgenerated  Fri Dec 18 11:08:41 CST 2009
	 */
	public int updateByPrimaryKeySelective(DiscountInfo record) {
		int rows = getSqlMapClientTemplate().update(
				"discount_info.ibatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table discount_info
	 * @ibatorgenerated  Fri Dec 18 11:08:41 CST 2009
	 */
	public int updateByPrimaryKeyWithBLOBs(DiscountInfo record) {
		int rows = getSqlMapClientTemplate().update(
				"discount_info.ibatorgenerated_updateByPrimaryKeyWithBLOBs",
				record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table discount_info
	 * @ibatorgenerated  Fri Dec 18 11:08:41 CST 2009
	 */
	public int updateByPrimaryKeyWithoutBLOBs(DiscountInfo record) {
		int rows = getSqlMapClientTemplate().update(
				"discount_info.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table discount_info
	 * @ibatorgenerated  Fri Dec 18 11:08:41 CST 2009
	 */
	private static class UpdateByExampleParms extends DiscountInfoExample {
		private Object record;

		public UpdateByExampleParms(Object record, DiscountInfoExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}