package com.zhelazhela.db.dao;

import com.zhelazhela.db.model.GoodsPrice;
import com.zhelazhela.db.model.GoodsPriceExample;
import java.util.List;

public interface GoodsPriceDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table goods_price
	 * @ibatorgenerated  Sun Feb 14 23:42:49 CST 2010
	 */
	int countByExample(GoodsPriceExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table goods_price
	 * @ibatorgenerated  Sun Feb 14 23:42:49 CST 2010
	 */
	int deleteByExample(GoodsPriceExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table goods_price
	 * @ibatorgenerated  Sun Feb 14 23:42:49 CST 2010
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table goods_price
	 * @ibatorgenerated  Sun Feb 14 23:42:49 CST 2010
	 */
	void insert(GoodsPrice record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table goods_price
	 * @ibatorgenerated  Sun Feb 14 23:42:49 CST 2010
	 */
	void insertSelective(GoodsPrice record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table goods_price
	 * @ibatorgenerated  Sun Feb 14 23:42:49 CST 2010
	 */
	List<GoodsPrice> selectByExample(GoodsPriceExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table goods_price
	 * @ibatorgenerated  Sun Feb 14 23:42:49 CST 2010
	 */
	GoodsPrice selectByPrimaryKey(Long id);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table goods_price
	 * @ibatorgenerated  Sun Feb 14 23:42:49 CST 2010
	 */
	int updateByExampleSelective(GoodsPrice record, GoodsPriceExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table goods_price
	 * @ibatorgenerated  Sun Feb 14 23:42:49 CST 2010
	 */
	int updateByExample(GoodsPrice record, GoodsPriceExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table goods_price
	 * @ibatorgenerated  Sun Feb 14 23:42:49 CST 2010
	 */
	int updateByPrimaryKeySelective(GoodsPrice record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table goods_price
	 * @ibatorgenerated  Sun Feb 14 23:42:49 CST 2010
	 */
	int updateByPrimaryKey(GoodsPrice record);
}