package com.zhelazhela.db.dao;

import com.zhelazhela.db.model.GroupDiscussion;
import com.zhelazhela.db.model.GroupDiscussionExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class GroupDiscussionDAOImpl extends SqlMapClientDaoSupport implements GroupDiscussionDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table group_discussion
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    public GroupDiscussionDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table group_discussion
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    public int countByExample(GroupDiscussionExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("group_discussion.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table group_discussion
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    public int deleteByExample(GroupDiscussionExample example) {
        int rows = getSqlMapClientTemplate().delete("group_discussion.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table group_discussion
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    public int deleteByPrimaryKey(Long id) {
        GroupDiscussion key = new GroupDiscussion();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("group_discussion.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table group_discussion
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    public void insert(GroupDiscussion record) {
        getSqlMapClientTemplate().insert("group_discussion.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table group_discussion
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    public void insertSelective(GroupDiscussion record) {
        getSqlMapClientTemplate().insert("group_discussion.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table group_discussion
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    @SuppressWarnings("unchecked")
    public List<GroupDiscussion> selectByExample(GroupDiscussionExample example) {
        List<GroupDiscussion> list = getSqlMapClientTemplate().queryForList("group_discussion.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table group_discussion
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    public GroupDiscussion selectByPrimaryKey(Long id) {
        GroupDiscussion key = new GroupDiscussion();
        key.setId(id);
        GroupDiscussion record = (GroupDiscussion) getSqlMapClientTemplate().queryForObject("group_discussion.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table group_discussion
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    public int updateByExampleSelective(GroupDiscussion record, GroupDiscussionExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("group_discussion.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table group_discussion
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    public int updateByExample(GroupDiscussion record, GroupDiscussionExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("group_discussion.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table group_discussion
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    public int updateByPrimaryKeySelective(GroupDiscussion record) {
        int rows = getSqlMapClientTemplate().update("group_discussion.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table group_discussion
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    public int updateByPrimaryKey(GroupDiscussion record) {
        int rows = getSqlMapClientTemplate().update("group_discussion.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table group_discussion
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    private static class UpdateByExampleParms extends GroupDiscussionExample {
        private Object record;

        public UpdateByExampleParms(Object record, GroupDiscussionExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}