package com.zhelazhela.db.dao;

import com.zhelazhela.db.model.Grouper;
import com.zhelazhela.db.model.GrouperExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class GrouperDAOImpl extends SqlMapClientDaoSupport implements GrouperDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table grouper
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    public GrouperDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table grouper
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    public int countByExample(GrouperExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("grouper.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table grouper
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    public int deleteByExample(GrouperExample example) {
        int rows = getSqlMapClientTemplate().delete("grouper.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table grouper
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    public int deleteByPrimaryKey(Long id) {
        Grouper key = new Grouper();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("grouper.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table grouper
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    public void insert(Grouper record) {
        getSqlMapClientTemplate().insert("grouper.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table grouper
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    public void insertSelective(Grouper record) {
        getSqlMapClientTemplate().insert("grouper.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table grouper
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    @SuppressWarnings("unchecked")
    public List<Grouper> selectByExample(GrouperExample example) {
        List<Grouper> list = getSqlMapClientTemplate().queryForList("grouper.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table grouper
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    public Grouper selectByPrimaryKey(Long id) {
        Grouper key = new Grouper();
        key.setId(id);
        Grouper record = (Grouper) getSqlMapClientTemplate().queryForObject("grouper.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table grouper
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    public int updateByExampleSelective(Grouper record, GrouperExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("grouper.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table grouper
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    public int updateByExample(Grouper record, GrouperExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("grouper.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table grouper
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    public int updateByPrimaryKeySelective(Grouper record) {
        int rows = getSqlMapClientTemplate().update("grouper.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table grouper
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    public int updateByPrimaryKey(Grouper record) {
        int rows = getSqlMapClientTemplate().update("grouper.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table grouper
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    private static class UpdateByExampleParms extends GrouperExample {
        private Object record;

        public UpdateByExampleParms(Object record, GrouperExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}