package com.zhelazhela.db.dao;

import com.zhelazhela.db.model.ProvidersLog;
import com.zhelazhela.db.model.ProvidersLogExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class ProvidersLogDAOImpl extends SqlMapClientDaoSupport implements ProvidersLogDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table providers_log
     *
     * @ibatorgenerated Tue Sep 07 09:56:04 GMT+08:00 2010
     */
    public ProvidersLogDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table providers_log
     *
     * @ibatorgenerated Tue Sep 07 09:56:04 GMT+08:00 2010
     */
    public int countByExample(ProvidersLogExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("providers_log.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table providers_log
     *
     * @ibatorgenerated Tue Sep 07 09:56:04 GMT+08:00 2010
     */
    public int deleteByExample(ProvidersLogExample example) {
        int rows = getSqlMapClientTemplate().delete("providers_log.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table providers_log
     *
     * @ibatorgenerated Tue Sep 07 09:56:04 GMT+08:00 2010
     */
    public int deleteByPrimaryKey(Long id) {
        ProvidersLog key = new ProvidersLog();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("providers_log.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table providers_log
     *
     * @ibatorgenerated Tue Sep 07 09:56:04 GMT+08:00 2010
     */
    public void insert(ProvidersLog record) {
        getSqlMapClientTemplate().insert("providers_log.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table providers_log
     *
     * @ibatorgenerated Tue Sep 07 09:56:04 GMT+08:00 2010
     */
    public void insertSelective(ProvidersLog record) {
        getSqlMapClientTemplate().insert("providers_log.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table providers_log
     *
     * @ibatorgenerated Tue Sep 07 09:56:04 GMT+08:00 2010
     */
    @SuppressWarnings("unchecked")
    public List<ProvidersLog> selectByExample(ProvidersLogExample example) {
        List<ProvidersLog> list = getSqlMapClientTemplate().queryForList("providers_log.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table providers_log
     *
     * @ibatorgenerated Tue Sep 07 09:56:04 GMT+08:00 2010
     */
    public ProvidersLog selectByPrimaryKey(Long id) {
        ProvidersLog key = new ProvidersLog();
        key.setId(id);
        ProvidersLog record = (ProvidersLog) getSqlMapClientTemplate().queryForObject("providers_log.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table providers_log
     *
     * @ibatorgenerated Tue Sep 07 09:56:04 GMT+08:00 2010
     */
    public int updateByExampleSelective(ProvidersLog record, ProvidersLogExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("providers_log.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table providers_log
     *
     * @ibatorgenerated Tue Sep 07 09:56:04 GMT+08:00 2010
     */
    public int updateByExample(ProvidersLog record, ProvidersLogExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("providers_log.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table providers_log
     *
     * @ibatorgenerated Tue Sep 07 09:56:04 GMT+08:00 2010
     */
    public int updateByPrimaryKeySelective(ProvidersLog record) {
        int rows = getSqlMapClientTemplate().update("providers_log.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table providers_log
     *
     * @ibatorgenerated Tue Sep 07 09:56:04 GMT+08:00 2010
     */
    public int updateByPrimaryKey(ProvidersLog record) {
        int rows = getSqlMapClientTemplate().update("providers_log.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table providers_log
     *
     * @ibatorgenerated Tue Sep 07 09:56:04 GMT+08:00 2010
     */
    private static class UpdateByExampleParms extends ProvidersLogExample {
        private Object record;

        public UpdateByExampleParms(Object record, ProvidersLogExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}