package com.zhelazhela.db.dao;

import com.zhelazhela.db.model.Tags;
import com.zhelazhela.db.model.TagsExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class TagsDAOImpl extends SqlMapClientDaoSupport implements TagsDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tags
     *
     * @ibatorgenerated Wed Jan 27 10:34:47 CST 2010
     */
    public TagsDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tags
     *
     * @ibatorgenerated Wed Jan 27 10:34:47 CST 2010
     */
    public int countByExample(TagsExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("tags.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tags
     *
     * @ibatorgenerated Wed Jan 27 10:34:47 CST 2010
     */
    public int deleteByExample(TagsExample example) {
        int rows = getSqlMapClientTemplate().delete("tags.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tags
     *
     * @ibatorgenerated Wed Jan 27 10:34:47 CST 2010
     */
    public int deleteByPrimaryKey(Long id) {
        Tags key = new Tags();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("tags.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tags
     *
     * @ibatorgenerated Wed Jan 27 10:34:47 CST 2010
     */
    public void insert(Tags record) {
        getSqlMapClientTemplate().insert("tags.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tags
     *
     * @ibatorgenerated Wed Jan 27 10:34:47 CST 2010
     */
    public void insertSelective(Tags record) {
        getSqlMapClientTemplate().insert("tags.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tags
     *
     * @ibatorgenerated Wed Jan 27 10:34:47 CST 2010
     */
    @SuppressWarnings("unchecked")
    public List<Tags> selectByExample(TagsExample example) {
        List<Tags> list = getSqlMapClientTemplate().queryForList("tags.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tags
     *
     * @ibatorgenerated Wed Jan 27 10:34:47 CST 2010
     */
    public Tags selectByPrimaryKey(Long id) {
        Tags key = new Tags();
        key.setId(id);
        Tags record = (Tags) getSqlMapClientTemplate().queryForObject("tags.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tags
     *
     * @ibatorgenerated Wed Jan 27 10:34:47 CST 2010
     */
    public int updateByExampleSelective(Tags record, TagsExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("tags.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tags
     *
     * @ibatorgenerated Wed Jan 27 10:34:47 CST 2010
     */
    public int updateByExample(Tags record, TagsExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("tags.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tags
     *
     * @ibatorgenerated Wed Jan 27 10:34:47 CST 2010
     */
    public int updateByPrimaryKeySelective(Tags record) {
        int rows = getSqlMapClientTemplate().update("tags.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tags
     *
     * @ibatorgenerated Wed Jan 27 10:34:47 CST 2010
     */
    public int updateByPrimaryKey(Tags record) {
        int rows = getSqlMapClientTemplate().update("tags.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table tags
     *
     * @ibatorgenerated Wed Jan 27 10:34:47 CST 2010
     */
    private static class UpdateByExampleParms extends TagsExample {
        private Object record;

        public UpdateByExampleParms(Object record, TagsExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }

	@Override
	public long insertSelectiveReturnId(Tags record) {
		return (Long)getSqlMapClientTemplate().insert("tags.insertSelective_returnId", record);
	}
}