package com.zhelazhela.db.dao;

import com.zhelazhela.db.model.UrlRedirection;
import com.zhelazhela.db.model.UrlRedirectionExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class UrlRedirectionDAOImpl extends SqlMapClientDaoSupport implements UrlRedirectionDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table url_redirection
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    public UrlRedirectionDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table url_redirection
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    public int countByExample(UrlRedirectionExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("url_redirection.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table url_redirection
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    public int deleteByExample(UrlRedirectionExample example) {
        int rows = getSqlMapClientTemplate().delete("url_redirection.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table url_redirection
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    public int deleteByPrimaryKey(Long id) {
        UrlRedirection key = new UrlRedirection();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("url_redirection.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table url_redirection
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    public void insert(UrlRedirection record) {
        getSqlMapClientTemplate().insert("url_redirection.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table url_redirection
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    public void insertSelective(UrlRedirection record) {
        getSqlMapClientTemplate().insert("url_redirection.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table url_redirection
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    @SuppressWarnings("unchecked")
    public List<UrlRedirection> selectByExample(UrlRedirectionExample example) {
        List<UrlRedirection> list = getSqlMapClientTemplate().queryForList("url_redirection.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table url_redirection
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    public UrlRedirection selectByPrimaryKey(Long id) {
        UrlRedirection key = new UrlRedirection();
        key.setId(id);
        UrlRedirection record = (UrlRedirection) getSqlMapClientTemplate().queryForObject("url_redirection.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table url_redirection
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    public int updateByExampleSelective(UrlRedirection record, UrlRedirectionExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("url_redirection.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table url_redirection
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    public int updateByExample(UrlRedirection record, UrlRedirectionExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("url_redirection.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table url_redirection
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    public int updateByPrimaryKeySelective(UrlRedirection record) {
        int rows = getSqlMapClientTemplate().update("url_redirection.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table url_redirection
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    public int updateByPrimaryKey(UrlRedirection record) {
        int rows = getSqlMapClientTemplate().update("url_redirection.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table url_redirection
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    private static class UpdateByExampleParms extends UrlRedirectionExample {
        private Object record;

        public UpdateByExampleParms(Object record, UrlRedirectionExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}