package com.zhelazhela.db.dao;

import com.zhelazhela.db.model.Userinfo;
import com.zhelazhela.db.model.UserinfoExample;
import java.util.List;

public interface UserinfoDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table userinfo
	 * @ibatorgenerated  Sat Feb 13 11:31:43 CST 2010
	 */
	int countByExample(UserinfoExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table userinfo
	 * @ibatorgenerated  Sat Feb 13 11:31:43 CST 2010
	 */
	int deleteByExample(UserinfoExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table userinfo
	 * @ibatorgenerated  Sat Feb 13 11:31:43 CST 2010
	 */
	int deleteByPrimaryKey(Long userId);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table userinfo
	 * @ibatorgenerated  Sat Feb 13 11:31:43 CST 2010
	 */
	void insert(Userinfo record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table userinfo
	 * @ibatorgenerated  Sat Feb 13 11:31:43 CST 2010
	 */
	void insertSelective(Userinfo record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table userinfo
	 * @ibatorgenerated  Sat Feb 13 11:31:43 CST 2010
	 */
	List<Userinfo> selectByExample(UserinfoExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table userinfo
	 * @ibatorgenerated  Sat Feb 13 11:31:43 CST 2010
	 */
	Userinfo selectByPrimaryKey(Long userId);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table userinfo
	 * @ibatorgenerated  Sat Feb 13 11:31:43 CST 2010
	 */
	int updateByExampleSelective(Userinfo record, UserinfoExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table userinfo
	 * @ibatorgenerated  Sat Feb 13 11:31:43 CST 2010
	 */
	int updateByExample(Userinfo record, UserinfoExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table userinfo
	 * @ibatorgenerated  Sat Feb 13 11:31:43 CST 2010
	 */
	int updateByPrimaryKeySelective(Userinfo record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table userinfo
	 * @ibatorgenerated  Sat Feb 13 11:31:43 CST 2010
	 */
	int updateByPrimaryKey(Userinfo record);
}