package com.zhelazhela.db.dao;

import com.zhelazhela.db.model.WebSiteCollection;
import com.zhelazhela.db.model.WebSiteCollectionExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class WebSiteCollectionDAOImpl extends SqlMapClientDaoSupport implements WebSiteCollectionDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table web_site_collection
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    public WebSiteCollectionDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table web_site_collection
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    public int countByExample(WebSiteCollectionExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("web_site_collection.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table web_site_collection
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    public int deleteByExample(WebSiteCollectionExample example) {
        int rows = getSqlMapClientTemplate().delete("web_site_collection.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table web_site_collection
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    public int deleteByPrimaryKey(Long id) {
        WebSiteCollection key = new WebSiteCollection();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("web_site_collection.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table web_site_collection
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    public void insert(WebSiteCollection record) {
        getSqlMapClientTemplate().insert("web_site_collection.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table web_site_collection
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    public void insertSelective(WebSiteCollection record) {
        getSqlMapClientTemplate().insert("web_site_collection.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table web_site_collection
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    @SuppressWarnings("unchecked")
    public List<WebSiteCollection> selectByExample(WebSiteCollectionExample example) {
        List<WebSiteCollection> list = getSqlMapClientTemplate().queryForList("web_site_collection.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table web_site_collection
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    public WebSiteCollection selectByPrimaryKey(Long id) {
        WebSiteCollection key = new WebSiteCollection();
        key.setId(id);
        WebSiteCollection record = (WebSiteCollection) getSqlMapClientTemplate().queryForObject("web_site_collection.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table web_site_collection
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    public int updateByExampleSelective(WebSiteCollection record, WebSiteCollectionExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("web_site_collection.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table web_site_collection
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    public int updateByExample(WebSiteCollection record, WebSiteCollectionExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("web_site_collection.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table web_site_collection
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    public int updateByPrimaryKeySelective(WebSiteCollection record) {
        int rows = getSqlMapClientTemplate().update("web_site_collection.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table web_site_collection
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    public int updateByPrimaryKey(WebSiteCollection record) {
        int rows = getSqlMapClientTemplate().update("web_site_collection.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table web_site_collection
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    private static class UpdateByExampleParms extends WebSiteCollectionExample {
        private Object record;

        public UpdateByExampleParms(Object record, WebSiteCollectionExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}