package com.twitpic.db.dao;

import com.twitpic.db.model.PermissionsScheme;
import com.twitpic.db.model.PermissionsSchemeExample;
import java.util.List;

public interface PermissionsSchemeDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table permissions_scheme
     *
     * @ibatorgenerated Sun Aug 30 15:33:51 CST 2009
     */
    int countByExample(PermissionsSchemeExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table permissions_scheme
     *
     * @ibatorgenerated Sun Aug 30 15:33:51 CST 2009
     */
    int deleteByExample(PermissionsSchemeExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table permissions_scheme
     *
     * @ibatorgenerated Sun Aug 30 15:33:51 CST 2009
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table permissions_scheme
     *
     * @ibatorgenerated Sun Aug 30 15:33:51 CST 2009
     */
    void insert(PermissionsScheme record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table permissions_scheme
     *
     * @ibatorgenerated Sun Aug 30 15:33:51 CST 2009
     */
    void insertSelective(PermissionsScheme record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table permissions_scheme
     *
     * @ibatorgenerated Sun Aug 30 15:33:51 CST 2009
     */
    List<PermissionsScheme> selectByExample(PermissionsSchemeExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table permissions_scheme
     *
     * @ibatorgenerated Sun Aug 30 15:33:51 CST 2009
     */
    PermissionsScheme selectByPrimaryKey(Long id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table permissions_scheme
     *
     * @ibatorgenerated Sun Aug 30 15:33:51 CST 2009
     */
    int updateByExampleSelective(PermissionsScheme record, PermissionsSchemeExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table permissions_scheme
     *
     * @ibatorgenerated Sun Aug 30 15:33:51 CST 2009
     */
    int updateByExample(PermissionsScheme record, PermissionsSchemeExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table permissions_scheme
     *
     * @ibatorgenerated Sun Aug 30 15:33:51 CST 2009
     */
    int updateByPrimaryKeySelective(PermissionsScheme record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table permissions_scheme
     *
     * @ibatorgenerated Sun Aug 30 15:33:51 CST 2009
     */
    int updateByPrimaryKey(PermissionsScheme record);
}