package com.twitpic.db.dao;

import com.twitpic.db.model.PicturesParameter;
import com.twitpic.db.model.PicturesParameterExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class PicturesParameterDAOImpl extends SqlMapClientDaoSupport implements PicturesParameterDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table pictures_parameter
	 * @ibatorgenerated  Wed Sep 02 16:12:27 CST 2009
	 */
	public PicturesParameterDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table pictures_parameter
	 * @ibatorgenerated  Wed Sep 02 16:12:27 CST 2009
	 */
	public int countByExample(PicturesParameterExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"pictures_parameter.ibatorgenerated_countByExample", example);
		return count;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table pictures_parameter
	 * @ibatorgenerated  Wed Sep 02 16:12:27 CST 2009
	 */
	public int deleteByExample(PicturesParameterExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"pictures_parameter.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table pictures_parameter
	 * @ibatorgenerated  Wed Sep 02 16:12:27 CST 2009
	 */
	public int deleteByPrimaryKey(Long idPictures) {
		PicturesParameter key = new PicturesParameter();
		key.setIdPictures(idPictures);
		int rows = getSqlMapClientTemplate().delete(
				"pictures_parameter.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table pictures_parameter
	 * @ibatorgenerated  Wed Sep 02 16:12:27 CST 2009
	 */
	public void insert(PicturesParameter record) {
		getSqlMapClientTemplate().insert(
				"pictures_parameter.ibatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table pictures_parameter
	 * @ibatorgenerated  Wed Sep 02 16:12:27 CST 2009
	 */
	public void insertSelective(PicturesParameter record) {
		getSqlMapClientTemplate().insert(
				"pictures_parameter.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table pictures_parameter
	 * @ibatorgenerated  Wed Sep 02 16:12:27 CST 2009
	 */
	@SuppressWarnings("unchecked")
	public List<PicturesParameter> selectByExampleWithBLOBs(
			PicturesParameterExample example) {
		List<PicturesParameter> list = getSqlMapClientTemplate().queryForList(
				"pictures_parameter.ibatorgenerated_selectByExampleWithBLOBs",
				example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table pictures_parameter
	 * @ibatorgenerated  Wed Sep 02 16:12:27 CST 2009
	 */
	@SuppressWarnings("unchecked")
	public List<PicturesParameter> selectByExampleWithoutBLOBs(
			PicturesParameterExample example) {
		List<PicturesParameter> list = getSqlMapClientTemplate().queryForList(
				"pictures_parameter.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table pictures_parameter
	 * @ibatorgenerated  Wed Sep 02 16:12:27 CST 2009
	 */
	public PicturesParameter selectByPrimaryKey(Long idPictures) {
		PicturesParameter key = new PicturesParameter();
		key.setIdPictures(idPictures);
		PicturesParameter record = (PicturesParameter) getSqlMapClientTemplate()
				.queryForObject(
						"pictures_parameter.ibatorgenerated_selectByPrimaryKey",
						key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table pictures_parameter
	 * @ibatorgenerated  Wed Sep 02 16:12:27 CST 2009
	 */
	public int updateByExampleSelective(PicturesParameter record,
			PicturesParameterExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"pictures_parameter.ibatorgenerated_updateByExampleSelective",
				parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table pictures_parameter
	 * @ibatorgenerated  Wed Sep 02 16:12:27 CST 2009
	 */
	public int updateByExampleWithBLOBs(PicturesParameter record,
			PicturesParameterExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"pictures_parameter.ibatorgenerated_updateByExampleWithBLOBs",
				parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table pictures_parameter
	 * @ibatorgenerated  Wed Sep 02 16:12:27 CST 2009
	 */
	public int updateByExampleWithoutBLOBs(PicturesParameter record,
			PicturesParameterExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"pictures_parameter.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table pictures_parameter
	 * @ibatorgenerated  Wed Sep 02 16:12:27 CST 2009
	 */
	public int updateByPrimaryKeySelective(PicturesParameter record) {
		int rows = getSqlMapClientTemplate()
				.update(
						"pictures_parameter.ibatorgenerated_updateByPrimaryKeySelective",
						record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table pictures_parameter
	 * @ibatorgenerated  Wed Sep 02 16:12:27 CST 2009
	 */
	public int updateByPrimaryKeyWithBLOBs(PicturesParameter record) {
		int rows = getSqlMapClientTemplate()
				.update(
						"pictures_parameter.ibatorgenerated_updateByPrimaryKeyWithBLOBs",
						record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table pictures_parameter
	 * @ibatorgenerated  Wed Sep 02 16:12:27 CST 2009
	 */
	public int updateByPrimaryKeyWithoutBLOBs(PicturesParameter record) {
		int rows = getSqlMapClientTemplate()
				.update(
						"pictures_parameter.ibatorgenerated_updateByPrimaryKey",
						record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table pictures_parameter
	 * @ibatorgenerated  Wed Sep 02 16:12:27 CST 2009
	 */
	private static class UpdateByExampleParms extends PicturesParameterExample {
		private Object record;

		public UpdateByExampleParms(Object record,
				PicturesParameterExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}