package com.zhela.cloudblog.dao.users;

import com.zhela.cloudblog.model.users.ProviderUser;
import com.zhela.cloudblog.model.users.ProviderUserExample;
import com.zhela.cloudblog.model.users.ProviderUserKey;
import java.util.List;

public interface ProviderUserDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table provider_user
	 * @ibatorgenerated  Mon Oct 25 21:54:16 CST 2010
	 */
	int countByExample(ProviderUserExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table provider_user
	 * @ibatorgenerated  Mon Oct 25 21:54:16 CST 2010
	 */
	int deleteByExample(ProviderUserExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table provider_user
	 * @ibatorgenerated  Mon Oct 25 21:54:16 CST 2010
	 */
	int deleteByPrimaryKey(ProviderUserKey key);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table provider_user
	 * @ibatorgenerated  Mon Oct 25 21:54:16 CST 2010
	 */
	void insert(ProviderUser record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table provider_user
	 * @ibatorgenerated  Mon Oct 25 21:54:16 CST 2010
	 */
	void insertSelective(ProviderUser record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table provider_user
	 * @ibatorgenerated  Mon Oct 25 21:54:16 CST 2010
	 */
	List<ProviderUser> selectByExample(ProviderUserExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table provider_user
	 * @ibatorgenerated  Mon Oct 25 21:54:16 CST 2010
	 */
	ProviderUser selectByPrimaryKey(ProviderUserKey key);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table provider_user
	 * @ibatorgenerated  Mon Oct 25 21:54:16 CST 2010
	 */
	int updateByExampleSelective(ProviderUser record,
			ProviderUserExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table provider_user
	 * @ibatorgenerated  Mon Oct 25 21:54:16 CST 2010
	 */
	int updateByExample(ProviderUser record, ProviderUserExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table provider_user
	 * @ibatorgenerated  Mon Oct 25 21:54:16 CST 2010
	 */
	int updateByPrimaryKeySelective(ProviderUser record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table provider_user
	 * @ibatorgenerated  Mon Oct 25 21:54:16 CST 2010
	 */
	int updateByPrimaryKey(ProviderUser record);
}