package com.zhela.cloudblog.dao.internalnews.impl;

import com.zhela.cloudblog.dao.internalnews.CategoryDAO;
import com.zhela.cloudblog.model.internalnews.Category;
import com.zhela.cloudblog.model.internalnews.CategoryExample;

import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class CategoryDAOImpl extends SqlMapClientDaoSupport implements CategoryDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table category
     *
     * @ibatorgenerated Fri Oct 22 23:22:19 CST 2010
     */
    public CategoryDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table category
     *
     * @ibatorgenerated Fri Oct 22 23:22:19 CST 2010
     */
    public int countByExample(CategoryExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("category.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table category
     *
     * @ibatorgenerated Fri Oct 22 23:22:19 CST 2010
     */
    public int deleteByExample(CategoryExample example) {
        int rows = getSqlMapClientTemplate().delete("category.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table category
     *
     * @ibatorgenerated Fri Oct 22 23:22:19 CST 2010
     */
    public int deleteByPrimaryKey(Long id) {
        Category key = new Category();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("category.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table category
     *
     * @ibatorgenerated Fri Oct 22 23:22:19 CST 2010
     */
    public void insert(Category record) {
        getSqlMapClientTemplate().insert("category.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table category
     *
     * @ibatorgenerated Fri Oct 22 23:22:19 CST 2010
     */
    public void insertSelective(Category record) {
        getSqlMapClientTemplate().insert("category.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table category
     *
     * @ibatorgenerated Fri Oct 22 23:22:19 CST 2010
     */
    @SuppressWarnings("unchecked")
    public List<Category> selectByExample(CategoryExample example) {
        List<Category> list = getSqlMapClientTemplate().queryForList("category.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table category
     *
     * @ibatorgenerated Fri Oct 22 23:22:19 CST 2010
     */
    public Category selectByPrimaryKey(Long id) {
        Category key = new Category();
        key.setId(id);
        Category record = (Category) getSqlMapClientTemplate().queryForObject("category.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table category
     *
     * @ibatorgenerated Fri Oct 22 23:22:19 CST 2010
     */
    public int updateByExampleSelective(Category record, CategoryExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("category.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table category
     *
     * @ibatorgenerated Fri Oct 22 23:22:19 CST 2010
     */
    public int updateByExample(Category record, CategoryExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("category.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table category
     *
     * @ibatorgenerated Fri Oct 22 23:22:19 CST 2010
     */
    public int updateByPrimaryKeySelective(Category record) {
        int rows = getSqlMapClientTemplate().update("category.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table category
     *
     * @ibatorgenerated Fri Oct 22 23:22:19 CST 2010
     */
    public int updateByPrimaryKey(Category record) {
        int rows = getSqlMapClientTemplate().update("category.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table category
     *
     * @ibatorgenerated Fri Oct 22 23:22:19 CST 2010
     */
    private static class UpdateByExampleParms extends CategoryExample {
        private Object record;

        public UpdateByExampleParms(Object record, CategoryExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}