package com.zhela.cloudblog.dao.internalnews.impl;

import com.zhela.cloudblog.dao.internalnews.NewsCategoryDAO;
import com.zhela.cloudblog.model.internalnews.NewsCategory;
import com.zhela.cloudblog.model.internalnews.NewsCategoryExample;

import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class NewsCategoryDAOImpl extends SqlMapClientDaoSupport implements NewsCategoryDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table news_category
     *
     * @ibatorgenerated Fri Oct 22 23:22:19 CST 2010
     */
    public NewsCategoryDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table news_category
     *
     * @ibatorgenerated Fri Oct 22 23:22:19 CST 2010
     */
    public int countByExample(NewsCategoryExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("news_category.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table news_category
     *
     * @ibatorgenerated Fri Oct 22 23:22:19 CST 2010
     */
    public int deleteByExample(NewsCategoryExample example) {
        int rows = getSqlMapClientTemplate().delete("news_category.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table news_category
     *
     * @ibatorgenerated Fri Oct 22 23:22:19 CST 2010
     */
    public void insert(NewsCategory record) {
        getSqlMapClientTemplate().insert("news_category.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table news_category
     *
     * @ibatorgenerated Fri Oct 22 23:22:19 CST 2010
     */
    public void insertSelective(NewsCategory record) {
        getSqlMapClientTemplate().insert("news_category.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table news_category
     *
     * @ibatorgenerated Fri Oct 22 23:22:19 CST 2010
     */
    @SuppressWarnings("unchecked")
    public List<NewsCategory> selectByExample(NewsCategoryExample example) {
        List<NewsCategory> list = getSqlMapClientTemplate().queryForList("news_category.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table news_category
     *
     * @ibatorgenerated Fri Oct 22 23:22:19 CST 2010
     */
    public int updateByExampleSelective(NewsCategory record, NewsCategoryExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("news_category.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table news_category
     *
     * @ibatorgenerated Fri Oct 22 23:22:19 CST 2010
     */
    public int updateByExample(NewsCategory record, NewsCategoryExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("news_category.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table news_category
     *
     * @ibatorgenerated Fri Oct 22 23:22:19 CST 2010
     */
    private static class UpdateByExampleParms extends NewsCategoryExample {
        private Object record;

        public UpdateByExampleParms(Object record, NewsCategoryExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}