package com.zhela.cloudblog.dao.internalnews.impl;

import com.zhela.cloudblog.dao.internalnews.TextNewsDAO;
import com.zhela.cloudblog.model.internalnews.TextNews;
import com.zhela.cloudblog.model.internalnews.TextNewsExample;

import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class TextNewsDAOImpl extends SqlMapClientDaoSupport implements TextNewsDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table text_news
     *
     * @ibatorgenerated Fri Oct 22 23:22:19 CST 2010
     */
    public TextNewsDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table text_news
     *
     * @ibatorgenerated Fri Oct 22 23:22:19 CST 2010
     */
    public int countByExample(TextNewsExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("text_news.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table text_news
     *
     * @ibatorgenerated Fri Oct 22 23:22:19 CST 2010
     */
    public int deleteByExample(TextNewsExample example) {
        int rows = getSqlMapClientTemplate().delete("text_news.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table text_news
     *
     * @ibatorgenerated Fri Oct 22 23:22:19 CST 2010
     */
    public int deleteByPrimaryKey(Long id) {
        TextNews key = new TextNews();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("text_news.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table text_news
     *
     * @ibatorgenerated Fri Oct 22 23:22:19 CST 2010
     */
    public void insert(TextNews record) {
        getSqlMapClientTemplate().insert("text_news.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table text_news
     *
     * @ibatorgenerated Fri Oct 22 23:22:19 CST 2010
     */
    public void insertSelective(TextNews record) {
        getSqlMapClientTemplate().insert("text_news.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table text_news
     *
     * @ibatorgenerated Fri Oct 22 23:22:19 CST 2010
     */
    @SuppressWarnings("unchecked")
    public List<TextNews> selectByExampleWithBLOBs(TextNewsExample example) {
        List<TextNews> list = getSqlMapClientTemplate().queryForList("text_news.ibatorgenerated_selectByExampleWithBLOBs", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table text_news
     *
     * @ibatorgenerated Fri Oct 22 23:22:19 CST 2010
     */
    @SuppressWarnings("unchecked")
    public List<TextNews> selectByExampleWithoutBLOBs(TextNewsExample example) {
        List<TextNews> list = getSqlMapClientTemplate().queryForList("text_news.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table text_news
     *
     * @ibatorgenerated Fri Oct 22 23:22:19 CST 2010
     */
    public TextNews selectByPrimaryKey(Long id) {
        TextNews key = new TextNews();
        key.setId(id);
        TextNews record = (TextNews) getSqlMapClientTemplate().queryForObject("text_news.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table text_news
     *
     * @ibatorgenerated Fri Oct 22 23:22:19 CST 2010
     */
    public int updateByExampleSelective(TextNews record, TextNewsExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("text_news.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table text_news
     *
     * @ibatorgenerated Fri Oct 22 23:22:19 CST 2010
     */
    public int updateByExampleWithBLOBs(TextNews record, TextNewsExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("text_news.ibatorgenerated_updateByExampleWithBLOBs", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table text_news
     *
     * @ibatorgenerated Fri Oct 22 23:22:19 CST 2010
     */
    public int updateByExampleWithoutBLOBs(TextNews record, TextNewsExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("text_news.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table text_news
     *
     * @ibatorgenerated Fri Oct 22 23:22:19 CST 2010
     */
    public int updateByPrimaryKeySelective(TextNews record) {
        int rows = getSqlMapClientTemplate().update("text_news.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table text_news
     *
     * @ibatorgenerated Fri Oct 22 23:22:19 CST 2010
     */
    public int updateByPrimaryKeyWithBLOBs(TextNews record) {
        int rows = getSqlMapClientTemplate().update("text_news.ibatorgenerated_updateByPrimaryKeyWithBLOBs", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table text_news
     *
     * @ibatorgenerated Fri Oct 22 23:22:19 CST 2010
     */
    public int updateByPrimaryKeyWithoutBLOBs(TextNews record) {
        int rows = getSqlMapClientTemplate().update("text_news.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table text_news
     *
     * @ibatorgenerated Fri Oct 22 23:22:19 CST 2010
     */
    private static class UpdateByExampleParms extends TextNewsExample {
        private Object record;

        public UpdateByExampleParms(Object record, TextNewsExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}