package com.zhela.cloudblog.dao.internalnews.impl;

import com.zhela.cloudblog.dao.internalnews.VideoNewsDAO;
import com.zhela.cloudblog.model.internalnews.VideoNews;
import com.zhela.cloudblog.model.internalnews.VideoNewsExample;

import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class VideoNewsDAOImpl extends SqlMapClientDaoSupport implements VideoNewsDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table video_news
     *
     * @ibatorgenerated Fri Oct 22 23:22:19 CST 2010
     */
    public VideoNewsDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table video_news
     *
     * @ibatorgenerated Fri Oct 22 23:22:19 CST 2010
     */
    public int countByExample(VideoNewsExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("video_news.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table video_news
     *
     * @ibatorgenerated Fri Oct 22 23:22:19 CST 2010
     */
    public int deleteByExample(VideoNewsExample example) {
        int rows = getSqlMapClientTemplate().delete("video_news.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table video_news
     *
     * @ibatorgenerated Fri Oct 22 23:22:19 CST 2010
     */
    public int deleteByPrimaryKey(Long id) {
        VideoNews key = new VideoNews();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("video_news.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table video_news
     *
     * @ibatorgenerated Fri Oct 22 23:22:19 CST 2010
     */
    public void insert(VideoNews record) {
        getSqlMapClientTemplate().insert("video_news.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table video_news
     *
     * @ibatorgenerated Fri Oct 22 23:22:19 CST 2010
     */
    public void insertSelective(VideoNews record) {
        getSqlMapClientTemplate().insert("video_news.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table video_news
     *
     * @ibatorgenerated Fri Oct 22 23:22:19 CST 2010
     */
    @SuppressWarnings("unchecked")
    public List<VideoNews> selectByExampleWithBLOBs(VideoNewsExample example) {
        List<VideoNews> list = getSqlMapClientTemplate().queryForList("video_news.ibatorgenerated_selectByExampleWithBLOBs", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table video_news
     *
     * @ibatorgenerated Fri Oct 22 23:22:19 CST 2010
     */
    @SuppressWarnings("unchecked")
    public List<VideoNews> selectByExampleWithoutBLOBs(VideoNewsExample example) {
        List<VideoNews> list = getSqlMapClientTemplate().queryForList("video_news.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table video_news
     *
     * @ibatorgenerated Fri Oct 22 23:22:19 CST 2010
     */
    public VideoNews selectByPrimaryKey(Long id) {
        VideoNews key = new VideoNews();
        key.setId(id);
        VideoNews record = (VideoNews) getSqlMapClientTemplate().queryForObject("video_news.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table video_news
     *
     * @ibatorgenerated Fri Oct 22 23:22:19 CST 2010
     */
    public int updateByExampleSelective(VideoNews record, VideoNewsExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("video_news.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table video_news
     *
     * @ibatorgenerated Fri Oct 22 23:22:19 CST 2010
     */
    public int updateByExampleWithBLOBs(VideoNews record, VideoNewsExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("video_news.ibatorgenerated_updateByExampleWithBLOBs", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table video_news
     *
     * @ibatorgenerated Fri Oct 22 23:22:19 CST 2010
     */
    public int updateByExampleWithoutBLOBs(VideoNews record, VideoNewsExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("video_news.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table video_news
     *
     * @ibatorgenerated Fri Oct 22 23:22:19 CST 2010
     */
    public int updateByPrimaryKeySelective(VideoNews record) {
        int rows = getSqlMapClientTemplate().update("video_news.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table video_news
     *
     * @ibatorgenerated Fri Oct 22 23:22:19 CST 2010
     */
    public int updateByPrimaryKeyWithBLOBs(VideoNews record) {
        int rows = getSqlMapClientTemplate().update("video_news.ibatorgenerated_updateByPrimaryKeyWithBLOBs", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table video_news
     *
     * @ibatorgenerated Fri Oct 22 23:22:19 CST 2010
     */
    public int updateByPrimaryKeyWithoutBLOBs(VideoNews record) {
        int rows = getSqlMapClientTemplate().update("video_news.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table video_news
     *
     * @ibatorgenerated Fri Oct 22 23:22:19 CST 2010
     */
    private static class UpdateByExampleParms extends VideoNewsExample {
        private Object record;

        public UpdateByExampleParms(Object record, VideoNewsExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}