package com.zhela.cloudblog.model.intenalnews;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.zhela.cloudblog.model.DefaultExample;

public class VideoNewsExample extends DefaultExample {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table video_news
     *
     * @ibatorgenerated Fri Oct 22 23:22:19 CST 2010
     */
    protected String orderByClause;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table video_news
     *
     * @ibatorgenerated Fri Oct 22 23:22:19 CST 2010
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table video_news
     *
     * @ibatorgenerated Fri Oct 22 23:22:19 CST 2010
     */
    public VideoNewsExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table video_news
     *
     * @ibatorgenerated Fri Oct 22 23:22:19 CST 2010
     */
    protected VideoNewsExample(VideoNewsExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table video_news
     *
     * @ibatorgenerated Fri Oct 22 23:22:19 CST 2010
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table video_news
     *
     * @ibatorgenerated Fri Oct 22 23:22:19 CST 2010
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table video_news
     *
     * @ibatorgenerated Fri Oct 22 23:22:19 CST 2010
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table video_news
     *
     * @ibatorgenerated Fri Oct 22 23:22:19 CST 2010
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table video_news
     *
     * @ibatorgenerated Fri Oct 22 23:22:19 CST 2010
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table video_news
     *
     * @ibatorgenerated Fri Oct 22 23:22:19 CST 2010
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table video_news
     *
     * @ibatorgenerated Fri Oct 22 23:22:19 CST 2010
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table video_news
     *
     * @ibatorgenerated Fri Oct 22 23:22:19 CST 2010
     */
    public static class Criteria {
        protected List<String> criteriaWithoutValue;

        protected List<Map<String, Object>> criteriaWithSingleValue;

        protected List<Map<String, Object>> criteriaWithListValue;

        protected List<Map<String, Object>> criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList<String>();
            criteriaWithSingleValue = new ArrayList<Map<String, Object>>();
            criteriaWithListValue = new ArrayList<Map<String, Object>>();
            criteriaWithBetweenValue = new ArrayList<Map<String, Object>>();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List<String> getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List<Map<String, Object>> getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List<Map<String, Object>> getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List<Map<String, Object>> getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List<? extends Object> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List<Object> list = new ArrayList<Object>();
            list.add(value1);
            list.add(value2);
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return this;
        }

        public Criteria andProviderIdIsNull() {
            addCriterion("provider_id is null");
            return this;
        }

        public Criteria andProviderIdIsNotNull() {
            addCriterion("provider_id is not null");
            return this;
        }

        public Criteria andProviderIdEqualTo(Long value) {
            addCriterion("provider_id =", value, "providerId");
            return this;
        }

        public Criteria andProviderIdNotEqualTo(Long value) {
            addCriterion("provider_id <>", value, "providerId");
            return this;
        }

        public Criteria andProviderIdGreaterThan(Long value) {
            addCriterion("provider_id >", value, "providerId");
            return this;
        }

        public Criteria andProviderIdGreaterThanOrEqualTo(Long value) {
            addCriterion("provider_id >=", value, "providerId");
            return this;
        }

        public Criteria andProviderIdLessThan(Long value) {
            addCriterion("provider_id <", value, "providerId");
            return this;
        }

        public Criteria andProviderIdLessThanOrEqualTo(Long value) {
            addCriterion("provider_id <=", value, "providerId");
            return this;
        }

        public Criteria andProviderIdIn(List<Long> values) {
            addCriterion("provider_id in", values, "providerId");
            return this;
        }

        public Criteria andProviderIdNotIn(List<Long> values) {
            addCriterion("provider_id not in", values, "providerId");
            return this;
        }

        public Criteria andProviderIdBetween(Long value1, Long value2) {
            addCriterion("provider_id between", value1, value2, "providerId");
            return this;
        }

        public Criteria andProviderIdNotBetween(Long value1, Long value2) {
            addCriterion("provider_id not between", value1, value2, "providerId");
            return this;
        }

        public Criteria andTweetIdIsNull() {
            addCriterion("tweet_id is null");
            return this;
        }

        public Criteria andTweetIdIsNotNull() {
            addCriterion("tweet_id is not null");
            return this;
        }

        public Criteria andTweetIdEqualTo(String value) {
            addCriterion("tweet_id =", value, "tweetId");
            return this;
        }

        public Criteria andTweetIdNotEqualTo(String value) {
            addCriterion("tweet_id <>", value, "tweetId");
            return this;
        }

        public Criteria andTweetIdGreaterThan(String value) {
            addCriterion("tweet_id >", value, "tweetId");
            return this;
        }

        public Criteria andTweetIdGreaterThanOrEqualTo(String value) {
            addCriterion("tweet_id >=", value, "tweetId");
            return this;
        }

        public Criteria andTweetIdLessThan(String value) {
            addCriterion("tweet_id <", value, "tweetId");
            return this;
        }

        public Criteria andTweetIdLessThanOrEqualTo(String value) {
            addCriterion("tweet_id <=", value, "tweetId");
            return this;
        }

        public Criteria andTweetIdLike(String value) {
            addCriterion("tweet_id like", value, "tweetId");
            return this;
        }

        public Criteria andTweetIdNotLike(String value) {
            addCriterion("tweet_id not like", value, "tweetId");
            return this;
        }

        public Criteria andTweetIdIn(List<String> values) {
            addCriterion("tweet_id in", values, "tweetId");
            return this;
        }

        public Criteria andTweetIdNotIn(List<String> values) {
            addCriterion("tweet_id not in", values, "tweetId");
            return this;
        }

        public Criteria andTweetIdBetween(String value1, String value2) {
            addCriterion("tweet_id between", value1, value2, "tweetId");
            return this;
        }

        public Criteria andTweetIdNotBetween(String value1, String value2) {
            addCriterion("tweet_id not between", value1, value2, "tweetId");
            return this;
        }

        public Criteria andTweetNameIsNull() {
            addCriterion("tweet_name is null");
            return this;
        }

        public Criteria andTweetNameIsNotNull() {
            addCriterion("tweet_name is not null");
            return this;
        }

        public Criteria andTweetNameEqualTo(String value) {
            addCriterion("tweet_name =", value, "tweetName");
            return this;
        }

        public Criteria andTweetNameNotEqualTo(String value) {
            addCriterion("tweet_name <>", value, "tweetName");
            return this;
        }

        public Criteria andTweetNameGreaterThan(String value) {
            addCriterion("tweet_name >", value, "tweetName");
            return this;
        }

        public Criteria andTweetNameGreaterThanOrEqualTo(String value) {
            addCriterion("tweet_name >=", value, "tweetName");
            return this;
        }

        public Criteria andTweetNameLessThan(String value) {
            addCriterion("tweet_name <", value, "tweetName");
            return this;
        }

        public Criteria andTweetNameLessThanOrEqualTo(String value) {
            addCriterion("tweet_name <=", value, "tweetName");
            return this;
        }

        public Criteria andTweetNameLike(String value) {
            addCriterion("tweet_name like", value, "tweetName");
            return this;
        }

        public Criteria andTweetNameNotLike(String value) {
            addCriterion("tweet_name not like", value, "tweetName");
            return this;
        }

        public Criteria andTweetNameIn(List<String> values) {
            addCriterion("tweet_name in", values, "tweetName");
            return this;
        }

        public Criteria andTweetNameNotIn(List<String> values) {
            addCriterion("tweet_name not in", values, "tweetName");
            return this;
        }

        public Criteria andTweetNameBetween(String value1, String value2) {
            addCriterion("tweet_name between", value1, value2, "tweetName");
            return this;
        }

        public Criteria andTweetNameNotBetween(String value1, String value2) {
            addCriterion("tweet_name not between", value1, value2, "tweetName");
            return this;
        }

        public Criteria andTweetHeaderIsNull() {
            addCriterion("tweet_header is null");
            return this;
        }

        public Criteria andTweetHeaderIsNotNull() {
            addCriterion("tweet_header is not null");
            return this;
        }

        public Criteria andTweetHeaderEqualTo(String value) {
            addCriterion("tweet_header =", value, "tweetHeader");
            return this;
        }

        public Criteria andTweetHeaderNotEqualTo(String value) {
            addCriterion("tweet_header <>", value, "tweetHeader");
            return this;
        }

        public Criteria andTweetHeaderGreaterThan(String value) {
            addCriterion("tweet_header >", value, "tweetHeader");
            return this;
        }

        public Criteria andTweetHeaderGreaterThanOrEqualTo(String value) {
            addCriterion("tweet_header >=", value, "tweetHeader");
            return this;
        }

        public Criteria andTweetHeaderLessThan(String value) {
            addCriterion("tweet_header <", value, "tweetHeader");
            return this;
        }

        public Criteria andTweetHeaderLessThanOrEqualTo(String value) {
            addCriterion("tweet_header <=", value, "tweetHeader");
            return this;
        }

        public Criteria andTweetHeaderLike(String value) {
            addCriterion("tweet_header like", value, "tweetHeader");
            return this;
        }

        public Criteria andTweetHeaderNotLike(String value) {
            addCriterion("tweet_header not like", value, "tweetHeader");
            return this;
        }

        public Criteria andTweetHeaderIn(List<String> values) {
            addCriterion("tweet_header in", values, "tweetHeader");
            return this;
        }

        public Criteria andTweetHeaderNotIn(List<String> values) {
            addCriterion("tweet_header not in", values, "tweetHeader");
            return this;
        }

        public Criteria andTweetHeaderBetween(String value1, String value2) {
            addCriterion("tweet_header between", value1, value2, "tweetHeader");
            return this;
        }

        public Criteria andTweetHeaderNotBetween(String value1, String value2) {
            addCriterion("tweet_header not between", value1, value2, "tweetHeader");
            return this;
        }

        public Criteria andPreviewIsNull() {
            addCriterion("preview is null");
            return this;
        }

        public Criteria andPreviewIsNotNull() {
            addCriterion("preview is not null");
            return this;
        }

        public Criteria andPreviewEqualTo(String value) {
            addCriterion("preview =", value, "preview");
            return this;
        }

        public Criteria andPreviewNotEqualTo(String value) {
            addCriterion("preview <>", value, "preview");
            return this;
        }

        public Criteria andPreviewGreaterThan(String value) {
            addCriterion("preview >", value, "preview");
            return this;
        }

        public Criteria andPreviewGreaterThanOrEqualTo(String value) {
            addCriterion("preview >=", value, "preview");
            return this;
        }

        public Criteria andPreviewLessThan(String value) {
            addCriterion("preview <", value, "preview");
            return this;
        }

        public Criteria andPreviewLessThanOrEqualTo(String value) {
            addCriterion("preview <=", value, "preview");
            return this;
        }

        public Criteria andPreviewLike(String value) {
            addCriterion("preview like", value, "preview");
            return this;
        }

        public Criteria andPreviewNotLike(String value) {
            addCriterion("preview not like", value, "preview");
            return this;
        }

        public Criteria andPreviewIn(List<String> values) {
            addCriterion("preview in", values, "preview");
            return this;
        }

        public Criteria andPreviewNotIn(List<String> values) {
            addCriterion("preview not in", values, "preview");
            return this;
        }

        public Criteria andPreviewBetween(String value1, String value2) {
            addCriterion("preview between", value1, value2, "preview");
            return this;
        }

        public Criteria andPreviewNotBetween(String value1, String value2) {
            addCriterion("preview not between", value1, value2, "preview");
            return this;
        }

        public Criteria andUrlIsNull() {
            addCriterion("url is null");
            return this;
        }

        public Criteria andUrlIsNotNull() {
            addCriterion("url is not null");
            return this;
        }

        public Criteria andUrlEqualTo(String value) {
            addCriterion("url =", value, "url");
            return this;
        }

        public Criteria andUrlNotEqualTo(String value) {
            addCriterion("url <>", value, "url");
            return this;
        }

        public Criteria andUrlGreaterThan(String value) {
            addCriterion("url >", value, "url");
            return this;
        }

        public Criteria andUrlGreaterThanOrEqualTo(String value) {
            addCriterion("url >=", value, "url");
            return this;
        }

        public Criteria andUrlLessThan(String value) {
            addCriterion("url <", value, "url");
            return this;
        }

        public Criteria andUrlLessThanOrEqualTo(String value) {
            addCriterion("url <=", value, "url");
            return this;
        }

        public Criteria andUrlLike(String value) {
            addCriterion("url like", value, "url");
            return this;
        }

        public Criteria andUrlNotLike(String value) {
            addCriterion("url not like", value, "url");
            return this;
        }

        public Criteria andUrlIn(List<String> values) {
            addCriterion("url in", values, "url");
            return this;
        }

        public Criteria andUrlNotIn(List<String> values) {
            addCriterion("url not in", values, "url");
            return this;
        }

        public Criteria andUrlBetween(String value1, String value2) {
            addCriterion("url between", value1, value2, "url");
            return this;
        }

        public Criteria andUrlNotBetween(String value1, String value2) {
            addCriterion("url not between", value1, value2, "url");
            return this;
        }

        public Criteria andFormatIsNull() {
            addCriterion("format is null");
            return this;
        }

        public Criteria andFormatIsNotNull() {
            addCriterion("format is not null");
            return this;
        }

        public Criteria andFormatEqualTo(String value) {
            addCriterion("format =", value, "format");
            return this;
        }

        public Criteria andFormatNotEqualTo(String value) {
            addCriterion("format <>", value, "format");
            return this;
        }

        public Criteria andFormatGreaterThan(String value) {
            addCriterion("format >", value, "format");
            return this;
        }

        public Criteria andFormatGreaterThanOrEqualTo(String value) {
            addCriterion("format >=", value, "format");
            return this;
        }

        public Criteria andFormatLessThan(String value) {
            addCriterion("format <", value, "format");
            return this;
        }

        public Criteria andFormatLessThanOrEqualTo(String value) {
            addCriterion("format <=", value, "format");
            return this;
        }

        public Criteria andFormatLike(String value) {
            addCriterion("format like", value, "format");
            return this;
        }

        public Criteria andFormatNotLike(String value) {
            addCriterion("format not like", value, "format");
            return this;
        }

        public Criteria andFormatIn(List<String> values) {
            addCriterion("format in", values, "format");
            return this;
        }

        public Criteria andFormatNotIn(List<String> values) {
            addCriterion("format not in", values, "format");
            return this;
        }

        public Criteria andFormatBetween(String value1, String value2) {
            addCriterion("format between", value1, value2, "format");
            return this;
        }

        public Criteria andFormatNotBetween(String value1, String value2) {
            addCriterion("format not between", value1, value2, "format");
            return this;
        }

        public Criteria andTimeLengthIsNull() {
            addCriterion("time_length is null");
            return this;
        }

        public Criteria andTimeLengthIsNotNull() {
            addCriterion("time_length is not null");
            return this;
        }

        public Criteria andTimeLengthEqualTo(Integer value) {
            addCriterion("time_length =", value, "timeLength");
            return this;
        }

        public Criteria andTimeLengthNotEqualTo(Integer value) {
            addCriterion("time_length <>", value, "timeLength");
            return this;
        }

        public Criteria andTimeLengthGreaterThan(Integer value) {
            addCriterion("time_length >", value, "timeLength");
            return this;
        }

        public Criteria andTimeLengthGreaterThanOrEqualTo(Integer value) {
            addCriterion("time_length >=", value, "timeLength");
            return this;
        }

        public Criteria andTimeLengthLessThan(Integer value) {
            addCriterion("time_length <", value, "timeLength");
            return this;
        }

        public Criteria andTimeLengthLessThanOrEqualTo(Integer value) {
            addCriterion("time_length <=", value, "timeLength");
            return this;
        }

        public Criteria andTimeLengthIn(List<Integer> values) {
            addCriterion("time_length in", values, "timeLength");
            return this;
        }

        public Criteria andTimeLengthNotIn(List<Integer> values) {
            addCriterion("time_length not in", values, "timeLength");
            return this;
        }

        public Criteria andTimeLengthBetween(Integer value1, Integer value2) {
            addCriterion("time_length between", value1, value2, "timeLength");
            return this;
        }

        public Criteria andTimeLengthNotBetween(Integer value1, Integer value2) {
            addCriterion("time_length not between", value1, value2, "timeLength");
            return this;
        }

        public Criteria andBitRateIsNull() {
            addCriterion("bit_rate is null");
            return this;
        }

        public Criteria andBitRateIsNotNull() {
            addCriterion("bit_rate is not null");
            return this;
        }

        public Criteria andBitRateEqualTo(Integer value) {
            addCriterion("bit_rate =", value, "bitRate");
            return this;
        }

        public Criteria andBitRateNotEqualTo(Integer value) {
            addCriterion("bit_rate <>", value, "bitRate");
            return this;
        }

        public Criteria andBitRateGreaterThan(Integer value) {
            addCriterion("bit_rate >", value, "bitRate");
            return this;
        }

        public Criteria andBitRateGreaterThanOrEqualTo(Integer value) {
            addCriterion("bit_rate >=", value, "bitRate");
            return this;
        }

        public Criteria andBitRateLessThan(Integer value) {
            addCriterion("bit_rate <", value, "bitRate");
            return this;
        }

        public Criteria andBitRateLessThanOrEqualTo(Integer value) {
            addCriterion("bit_rate <=", value, "bitRate");
            return this;
        }

        public Criteria andBitRateIn(List<Integer> values) {
            addCriterion("bit_rate in", values, "bitRate");
            return this;
        }

        public Criteria andBitRateNotIn(List<Integer> values) {
            addCriterion("bit_rate not in", values, "bitRate");
            return this;
        }

        public Criteria andBitRateBetween(Integer value1, Integer value2) {
            addCriterion("bit_rate between", value1, value2, "bitRate");
            return this;
        }

        public Criteria andBitRateNotBetween(Integer value1, Integer value2) {
            addCriterion("bit_rate not between", value1, value2, "bitRate");
            return this;
        }

        public Criteria andTitleIsNull() {
            addCriterion("title is null");
            return this;
        }

        public Criteria andTitleIsNotNull() {
            addCriterion("title is not null");
            return this;
        }

        public Criteria andTitleEqualTo(String value) {
            addCriterion("title =", value, "title");
            return this;
        }

        public Criteria andTitleNotEqualTo(String value) {
            addCriterion("title <>", value, "title");
            return this;
        }

        public Criteria andTitleGreaterThan(String value) {
            addCriterion("title >", value, "title");
            return this;
        }

        public Criteria andTitleGreaterThanOrEqualTo(String value) {
            addCriterion("title >=", value, "title");
            return this;
        }

        public Criteria andTitleLessThan(String value) {
            addCriterion("title <", value, "title");
            return this;
        }

        public Criteria andTitleLessThanOrEqualTo(String value) {
            addCriterion("title <=", value, "title");
            return this;
        }

        public Criteria andTitleLike(String value) {
            addCriterion("title like", value, "title");
            return this;
        }

        public Criteria andTitleNotLike(String value) {
            addCriterion("title not like", value, "title");
            return this;
        }

        public Criteria andTitleIn(List<String> values) {
            addCriterion("title in", values, "title");
            return this;
        }

        public Criteria andTitleNotIn(List<String> values) {
            addCriterion("title not in", values, "title");
            return this;
        }

        public Criteria andTitleBetween(String value1, String value2) {
            addCriterion("title between", value1, value2, "title");
            return this;
        }

        public Criteria andTitleNotBetween(String value1, String value2) {
            addCriterion("title not between", value1, value2, "title");
            return this;
        }

        public Criteria andReadCountIsNull() {
            addCriterion("read_count is null");
            return this;
        }

        public Criteria andReadCountIsNotNull() {
            addCriterion("read_count is not null");
            return this;
        }

        public Criteria andReadCountEqualTo(Long value) {
            addCriterion("read_count =", value, "readCount");
            return this;
        }

        public Criteria andReadCountNotEqualTo(Long value) {
            addCriterion("read_count <>", value, "readCount");
            return this;
        }

        public Criteria andReadCountGreaterThan(Long value) {
            addCriterion("read_count >", value, "readCount");
            return this;
        }

        public Criteria andReadCountGreaterThanOrEqualTo(Long value) {
            addCriterion("read_count >=", value, "readCount");
            return this;
        }

        public Criteria andReadCountLessThan(Long value) {
            addCriterion("read_count <", value, "readCount");
            return this;
        }

        public Criteria andReadCountLessThanOrEqualTo(Long value) {
            addCriterion("read_count <=", value, "readCount");
            return this;
        }

        public Criteria andReadCountIn(List<Long> values) {
            addCriterion("read_count in", values, "readCount");
            return this;
        }

        public Criteria andReadCountNotIn(List<Long> values) {
            addCriterion("read_count not in", values, "readCount");
            return this;
        }

        public Criteria andReadCountBetween(Long value1, Long value2) {
            addCriterion("read_count between", value1, value2, "readCount");
            return this;
        }

        public Criteria andReadCountNotBetween(Long value1, Long value2) {
            addCriterion("read_count not between", value1, value2, "readCount");
            return this;
        }

        public Criteria andPublishCountIsNull() {
            addCriterion("publish_count is null");
            return this;
        }

        public Criteria andPublishCountIsNotNull() {
            addCriterion("publish_count is not null");
            return this;
        }

        public Criteria andPublishCountEqualTo(Long value) {
            addCriterion("publish_count =", value, "publishCount");
            return this;
        }

        public Criteria andPublishCountNotEqualTo(Long value) {
            addCriterion("publish_count <>", value, "publishCount");
            return this;
        }

        public Criteria andPublishCountGreaterThan(Long value) {
            addCriterion("publish_count >", value, "publishCount");
            return this;
        }

        public Criteria andPublishCountGreaterThanOrEqualTo(Long value) {
            addCriterion("publish_count >=", value, "publishCount");
            return this;
        }

        public Criteria andPublishCountLessThan(Long value) {
            addCriterion("publish_count <", value, "publishCount");
            return this;
        }

        public Criteria andPublishCountLessThanOrEqualTo(Long value) {
            addCriterion("publish_count <=", value, "publishCount");
            return this;
        }

        public Criteria andPublishCountIn(List<Long> values) {
            addCriterion("publish_count in", values, "publishCount");
            return this;
        }

        public Criteria andPublishCountNotIn(List<Long> values) {
            addCriterion("publish_count not in", values, "publishCount");
            return this;
        }

        public Criteria andPublishCountBetween(Long value1, Long value2) {
            addCriterion("publish_count between", value1, value2, "publishCount");
            return this;
        }

        public Criteria andPublishCountNotBetween(Long value1, Long value2) {
            addCriterion("publish_count not between", value1, value2, "publishCount");
            return this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return this;
        }
    }
}