package com.zhelazhela.db.model;

public class BlockUser {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column block_user.user_id
     *
     * @ibatorgenerated Fri Feb 12 23:38:36 CST 2010
     */
    private Long userId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column block_user.blocked_user_id
     *
     * @ibatorgenerated Fri Feb 12 23:38:36 CST 2010
     */
    private Long blockedUserId;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column block_user.user_id
     *
     * @return the value of block_user.user_id
     *
     * @ibatorgenerated Fri Feb 12 23:38:36 CST 2010
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column block_user.user_id
     *
     * @param userId the value for block_user.user_id
     *
     * @ibatorgenerated Fri Feb 12 23:38:36 CST 2010
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column block_user.blocked_user_id
     *
     * @return the value of block_user.blocked_user_id
     *
     * @ibatorgenerated Fri Feb 12 23:38:36 CST 2010
     */
    public Long getBlockedUserId() {
        return blockedUserId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column block_user.blocked_user_id
     *
     * @param blockedUserId the value for block_user.blocked_user_id
     *
     * @ibatorgenerated Fri Feb 12 23:38:36 CST 2010
     */
    public void setBlockedUserId(Long blockedUserId) {
        this.blockedUserId = blockedUserId;
    }
}