package com.zhelazhela.db.model;

import java.util.Date;
import java.util.Locale;

import org.apache.commons.lang.StringUtils;

public class BlogDetail {
	
	private static java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("MMM,dd",Locale.US);
	
	private String month;
	
	private String day;

	public String getMonth() {
		return month;
	}

	public String getDay() {
		return day;
	}
	
	public String getTagStr(){
		if(tags==null||tags.size()==0){
			return "";
		}
		return tags.toString().replaceAll("\\u005B", "").replaceAll("]", "").replaceAll(" ", "");
	}

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column blog_detail.id
	 * @ibatorgenerated  Wed Jan 27 11:07:17 CST 2010
	 */
	private Long id;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column blog_detail.published
	 * @ibatorgenerated  Wed Jan 27 11:07:17 CST 2010
	 */
	private Boolean published;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column blog_detail.staticed
	 * @ibatorgenerated  Wed Jan 27 11:07:17 CST 2010
	 */
	private Boolean staticed;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column blog_detail.update_time
	 * @ibatorgenerated  Wed Jan 27 11:07:17 CST 2010
	 */
	private Date updateTime;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column blog_detail.category
	 * @ibatorgenerated  Wed Jan 27 11:07:17 CST 2010
	 */
	private String category;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column blog_detail.title
	 * @ibatorgenerated  Wed Jan 27 11:07:17 CST 2010
	 */
	private String title;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column blog_detail.review
	 * @ibatorgenerated  Wed Jan 27 11:07:17 CST 2010
	 */
	private String review;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column blog_detail.content
	 * @ibatorgenerated  Wed Jan 27 11:07:17 CST 2010
	 */
	private String content;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column blog_detail.id
	 * @return  the value of blog_detail.id
	 * @ibatorgenerated  Wed Jan 27 11:07:17 CST 2010
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column blog_detail.id
	 * @param id  the value for blog_detail.id
	 * @ibatorgenerated  Wed Jan 27 11:07:17 CST 2010
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column blog_detail.published
	 * @return  the value of blog_detail.published
	 * @ibatorgenerated  Wed Jan 27 11:07:17 CST 2010
	 */
	public Boolean getPublished() {
		return published;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column blog_detail.published
	 * @param published  the value for blog_detail.published
	 * @ibatorgenerated  Wed Jan 27 11:07:17 CST 2010
	 */
	public void setPublished(Boolean published) {
		this.published = published;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column blog_detail.staticed
	 * @return  the value of blog_detail.staticed
	 * @ibatorgenerated  Wed Jan 27 11:07:17 CST 2010
	 */
	public Boolean getStaticed() {
		return staticed;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column blog_detail.staticed
	 * @param staticed  the value for blog_detail.staticed
	 * @ibatorgenerated  Wed Jan 27 11:07:17 CST 2010
	 */
	public void setStaticed(Boolean staticed) {
		this.staticed = staticed;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column blog_detail.update_time
	 * @return  the value of blog_detail.update_time
	 * @ibatorgenerated  Wed Jan 27 11:07:17 CST 2010
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column blog_detail.update_time
	 * @param updateTime  the value for blog_detail.update_time
	 * @ibatorgenerated  Wed Jan 27 11:07:17 CST 2010
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
		if(updateTime!=null){
			String []md = sdf.format(updateTime).split(",");
			this.month = md[0].trim();
			this.day = md[1].trim();
		}
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column blog_detail.category
	 * @return  the value of blog_detail.category
	 * @ibatorgenerated  Wed Jan 27 11:07:17 CST 2010
	 */
	public String getCategory() {
		return category;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column blog_detail.category
	 * @param category  the value for blog_detail.category
	 * @ibatorgenerated  Wed Jan 27 11:07:17 CST 2010
	 */
	public void setCategory(String category) {
		this.category = category;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column blog_detail.title
	 * @return  the value of blog_detail.title
	 * @ibatorgenerated  Wed Jan 27 11:07:17 CST 2010
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column blog_detail.title
	 * @param title  the value for blog_detail.title
	 * @ibatorgenerated  Wed Jan 27 11:07:17 CST 2010
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column blog_detail.review
	 * @return  the value of blog_detail.review
	 * @ibatorgenerated  Wed Jan 27 11:07:17 CST 2010
	 */
	public String getReview() {
		return review;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column blog_detail.review
	 * @param review  the value for blog_detail.review
	 * @ibatorgenerated  Wed Jan 27 11:07:17 CST 2010
	 */
	public void setReview(String review) {
		this.review = review;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column blog_detail.content
	 * @return  the value of blog_detail.content
	 * @ibatorgenerated  Wed Jan 27 11:07:17 CST 2010
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column blog_detail.content
	 * @param content  the value for blog_detail.content
	 * @ibatorgenerated  Wed Jan 27 11:07:17 CST 2010
	 */
	public void setContent(String content) {
		this.content = content;
	}
	
	private java.util.List<Tags> tags;

	public java.util.List<Tags> getTags() {
		return tags;
	}

	public void setTags(java.util.List<Tags> tags) {
		this.tags = tags;
	}
	
	public boolean isValid(){
		if(StringUtils.isNotBlank(title)&&StringUtils.isNotBlank(review)&&StringUtils.isNotBlank(category)&&StringUtils.isNotBlank(content)){
			return true;
		}
		return false;
	}
	
	
}