package com.zhelazhela.db.model;

import java.util.Date;

public class GroupDiscussionPost {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column group_discussion_post.id
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    private Long id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column group_discussion_post.group_dis_id
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    private Long groupDisId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column group_discussion_post.post_user_id
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    private Long postUserId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column group_discussion_post.replied_to_id
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    private Long repliedToId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column group_discussion_post.update_time
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    private Date updateTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column group_discussion_post.status
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    private Integer status;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column group_discussion_post.content
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    private String content;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column group_discussion_post.id
     *
     * @return the value of group_discussion_post.id
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column group_discussion_post.id
     *
     * @param id the value for group_discussion_post.id
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column group_discussion_post.group_dis_id
     *
     * @return the value of group_discussion_post.group_dis_id
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    public Long getGroupDisId() {
        return groupDisId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column group_discussion_post.group_dis_id
     *
     * @param groupDisId the value for group_discussion_post.group_dis_id
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    public void setGroupDisId(Long groupDisId) {
        this.groupDisId = groupDisId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column group_discussion_post.post_user_id
     *
     * @return the value of group_discussion_post.post_user_id
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    public Long getPostUserId() {
        return postUserId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column group_discussion_post.post_user_id
     *
     * @param postUserId the value for group_discussion_post.post_user_id
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    public void setPostUserId(Long postUserId) {
        this.postUserId = postUserId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column group_discussion_post.replied_to_id
     *
     * @return the value of group_discussion_post.replied_to_id
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    public Long getRepliedToId() {
        return repliedToId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column group_discussion_post.replied_to_id
     *
     * @param repliedToId the value for group_discussion_post.replied_to_id
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    public void setRepliedToId(Long repliedToId) {
        this.repliedToId = repliedToId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column group_discussion_post.update_time
     *
     * @return the value of group_discussion_post.update_time
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column group_discussion_post.update_time
     *
     * @param updateTime the value for group_discussion_post.update_time
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column group_discussion_post.status
     *
     * @return the value of group_discussion_post.status
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column group_discussion_post.status
     *
     * @param status the value for group_discussion_post.status
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column group_discussion_post.content
     *
     * @return the value of group_discussion_post.content
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column group_discussion_post.content
     *
     * @param content the value for group_discussion_post.content
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    public void setContent(String content) {
        this.content = content;
    }
}