package com.zhelazhela.db.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class GroupDiscussionPostExample {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table group_discussion_post
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    protected String orderByClause;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table group_discussion_post
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table group_discussion_post
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    public GroupDiscussionPostExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table group_discussion_post
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    protected GroupDiscussionPostExample(GroupDiscussionPostExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table group_discussion_post
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table group_discussion_post
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table group_discussion_post
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table group_discussion_post
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table group_discussion_post
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table group_discussion_post
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table group_discussion_post
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table group_discussion_post
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    public static class Criteria {
        protected List<String> criteriaWithoutValue;

        protected List<Map<String, Object>> criteriaWithSingleValue;

        protected List<Map<String, Object>> criteriaWithListValue;

        protected List<Map<String, Object>> criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList<String>();
            criteriaWithSingleValue = new ArrayList<Map<String, Object>>();
            criteriaWithListValue = new ArrayList<Map<String, Object>>();
            criteriaWithBetweenValue = new ArrayList<Map<String, Object>>();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List<String> getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List<Map<String, Object>> getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List<Map<String, Object>> getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List<Map<String, Object>> getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List<? extends Object> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List<Object> list = new ArrayList<Object>();
            list.add(value1);
            list.add(value2);
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return this;
        }

        public Criteria andGroupDisIdIsNull() {
            addCriterion("group_dis_id is null");
            return this;
        }

        public Criteria andGroupDisIdIsNotNull() {
            addCriterion("group_dis_id is not null");
            return this;
        }

        public Criteria andGroupDisIdEqualTo(Long value) {
            addCriterion("group_dis_id =", value, "groupDisId");
            return this;
        }

        public Criteria andGroupDisIdNotEqualTo(Long value) {
            addCriterion("group_dis_id <>", value, "groupDisId");
            return this;
        }

        public Criteria andGroupDisIdGreaterThan(Long value) {
            addCriterion("group_dis_id >", value, "groupDisId");
            return this;
        }

        public Criteria andGroupDisIdGreaterThanOrEqualTo(Long value) {
            addCriterion("group_dis_id >=", value, "groupDisId");
            return this;
        }

        public Criteria andGroupDisIdLessThan(Long value) {
            addCriterion("group_dis_id <", value, "groupDisId");
            return this;
        }

        public Criteria andGroupDisIdLessThanOrEqualTo(Long value) {
            addCriterion("group_dis_id <=", value, "groupDisId");
            return this;
        }

        public Criteria andGroupDisIdIn(List<Long> values) {
            addCriterion("group_dis_id in", values, "groupDisId");
            return this;
        }

        public Criteria andGroupDisIdNotIn(List<Long> values) {
            addCriterion("group_dis_id not in", values, "groupDisId");
            return this;
        }

        public Criteria andGroupDisIdBetween(Long value1, Long value2) {
            addCriterion("group_dis_id between", value1, value2, "groupDisId");
            return this;
        }

        public Criteria andGroupDisIdNotBetween(Long value1, Long value2) {
            addCriterion("group_dis_id not between", value1, value2, "groupDisId");
            return this;
        }

        public Criteria andPostUserIdIsNull() {
            addCriterion("post_user_id is null");
            return this;
        }

        public Criteria andPostUserIdIsNotNull() {
            addCriterion("post_user_id is not null");
            return this;
        }

        public Criteria andPostUserIdEqualTo(Long value) {
            addCriterion("post_user_id =", value, "postUserId");
            return this;
        }

        public Criteria andPostUserIdNotEqualTo(Long value) {
            addCriterion("post_user_id <>", value, "postUserId");
            return this;
        }

        public Criteria andPostUserIdGreaterThan(Long value) {
            addCriterion("post_user_id >", value, "postUserId");
            return this;
        }

        public Criteria andPostUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("post_user_id >=", value, "postUserId");
            return this;
        }

        public Criteria andPostUserIdLessThan(Long value) {
            addCriterion("post_user_id <", value, "postUserId");
            return this;
        }

        public Criteria andPostUserIdLessThanOrEqualTo(Long value) {
            addCriterion("post_user_id <=", value, "postUserId");
            return this;
        }

        public Criteria andPostUserIdIn(List<Long> values) {
            addCriterion("post_user_id in", values, "postUserId");
            return this;
        }

        public Criteria andPostUserIdNotIn(List<Long> values) {
            addCriterion("post_user_id not in", values, "postUserId");
            return this;
        }

        public Criteria andPostUserIdBetween(Long value1, Long value2) {
            addCriterion("post_user_id between", value1, value2, "postUserId");
            return this;
        }

        public Criteria andPostUserIdNotBetween(Long value1, Long value2) {
            addCriterion("post_user_id not between", value1, value2, "postUserId");
            return this;
        }

        public Criteria andRepliedToIdIsNull() {
            addCriterion("replied_to_id is null");
            return this;
        }

        public Criteria andRepliedToIdIsNotNull() {
            addCriterion("replied_to_id is not null");
            return this;
        }

        public Criteria andRepliedToIdEqualTo(Long value) {
            addCriterion("replied_to_id =", value, "repliedToId");
            return this;
        }

        public Criteria andRepliedToIdNotEqualTo(Long value) {
            addCriterion("replied_to_id <>", value, "repliedToId");
            return this;
        }

        public Criteria andRepliedToIdGreaterThan(Long value) {
            addCriterion("replied_to_id >", value, "repliedToId");
            return this;
        }

        public Criteria andRepliedToIdGreaterThanOrEqualTo(Long value) {
            addCriterion("replied_to_id >=", value, "repliedToId");
            return this;
        }

        public Criteria andRepliedToIdLessThan(Long value) {
            addCriterion("replied_to_id <", value, "repliedToId");
            return this;
        }

        public Criteria andRepliedToIdLessThanOrEqualTo(Long value) {
            addCriterion("replied_to_id <=", value, "repliedToId");
            return this;
        }

        public Criteria andRepliedToIdIn(List<Long> values) {
            addCriterion("replied_to_id in", values, "repliedToId");
            return this;
        }

        public Criteria andRepliedToIdNotIn(List<Long> values) {
            addCriterion("replied_to_id not in", values, "repliedToId");
            return this;
        }

        public Criteria andRepliedToIdBetween(Long value1, Long value2) {
            addCriterion("replied_to_id between", value1, value2, "repliedToId");
            return this;
        }

        public Criteria andRepliedToIdNotBetween(Long value1, Long value2) {
            addCriterion("replied_to_id not between", value1, value2, "repliedToId");
            return this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("status =", value, "status");
            return this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("status <>", value, "status");
            return this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("status >", value, "status");
            return this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("status >=", value, "status");
            return this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("status <", value, "status");
            return this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("status <=", value, "status");
            return this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("status in", values, "status");
            return this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("status not in", values, "status");
            return this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("status between", value1, value2, "status");
            return this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("status not between", value1, value2, "status");
            return this;
        }
    }
}