package com.zhelazhela.db.model;

import java.util.Date;

public class ManageUser {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column manage_user.account
	 * @ibatorgenerated  Sat Dec 19 11:24:05 CST 2009
	 */
	private String account;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column manage_user.password
	 * @ibatorgenerated  Sat Dec 19 11:24:05 CST 2009
	 */
	private String password;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column manage_user.name
	 * @ibatorgenerated  Sat Dec 19 11:24:05 CST 2009
	 */
	private String name;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column manage_user.email
	 * @ibatorgenerated  Sat Dec 19 11:24:05 CST 2009
	 */
	private String email;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column manage_user.isvalid
	 * @ibatorgenerated  Sat Dec 19 11:24:05 CST 2009
	 */
	private Boolean isvalid;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column manage_user.update_time
	 * @ibatorgenerated  Sat Dec 19 11:24:05 CST 2009
	 */
	private Date updateTime;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column manage_user.account
	 * @return  the value of manage_user.account
	 * @ibatorgenerated  Sat Dec 19 11:24:05 CST 2009
	 */
	public String getAccount() {
		return account;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column manage_user.account
	 * @param account  the value for manage_user.account
	 * @ibatorgenerated  Sat Dec 19 11:24:05 CST 2009
	 */
	public void setAccount(String account) {
		this.account = account;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column manage_user.password
	 * @return  the value of manage_user.password
	 * @ibatorgenerated  Sat Dec 19 11:24:05 CST 2009
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column manage_user.password
	 * @param password  the value for manage_user.password
	 * @ibatorgenerated  Sat Dec 19 11:24:05 CST 2009
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column manage_user.name
	 * @return  the value of manage_user.name
	 * @ibatorgenerated  Sat Dec 19 11:24:05 CST 2009
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column manage_user.name
	 * @param name  the value for manage_user.name
	 * @ibatorgenerated  Sat Dec 19 11:24:05 CST 2009
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column manage_user.email
	 * @return  the value of manage_user.email
	 * @ibatorgenerated  Sat Dec 19 11:24:05 CST 2009
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column manage_user.email
	 * @param email  the value for manage_user.email
	 * @ibatorgenerated  Sat Dec 19 11:24:05 CST 2009
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column manage_user.isvalid
	 * @return  the value of manage_user.isvalid
	 * @ibatorgenerated  Sat Dec 19 11:24:05 CST 2009
	 */
	public Boolean getIsvalid() {
		return isvalid;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column manage_user.isvalid
	 * @param isvalid  the value for manage_user.isvalid
	 * @ibatorgenerated  Sat Dec 19 11:24:05 CST 2009
	 */
	public void setIsvalid(Boolean isvalid) {
		this.isvalid = isvalid;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column manage_user.update_time
	 * @return  the value of manage_user.update_time
	 * @ibatorgenerated  Sat Dec 19 11:24:05 CST 2009
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column manage_user.update_time
	 * @param updateTime  the value for manage_user.update_time
	 * @ibatorgenerated  Sat Dec 19 11:24:05 CST 2009
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
}