package com.zhelazhela.db.model;

import java.util.Date;

public class UserCertification {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column user_certification.id
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    private Long id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column user_certification.user_id
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    private Long userId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column user_certification.cert_id
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    private Long certId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column user_certification.parameter
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    private String parameter;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column user_certification.start_date
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    private Date startDate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column user_certification.end_date
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    private Date endDate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column user_certification.note
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    private String note;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column user_certification.id
     *
     * @return the value of user_certification.id
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column user_certification.id
     *
     * @param id the value for user_certification.id
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column user_certification.user_id
     *
     * @return the value of user_certification.user_id
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column user_certification.user_id
     *
     * @param userId the value for user_certification.user_id
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column user_certification.cert_id
     *
     * @return the value of user_certification.cert_id
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    public Long getCertId() {
        return certId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column user_certification.cert_id
     *
     * @param certId the value for user_certification.cert_id
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    public void setCertId(Long certId) {
        this.certId = certId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column user_certification.parameter
     *
     * @return the value of user_certification.parameter
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    public String getParameter() {
        return parameter;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column user_certification.parameter
     *
     * @param parameter the value for user_certification.parameter
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    public void setParameter(String parameter) {
        this.parameter = parameter;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column user_certification.start_date
     *
     * @return the value of user_certification.start_date
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column user_certification.start_date
     *
     * @param startDate the value for user_certification.start_date
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column user_certification.end_date
     *
     * @return the value of user_certification.end_date
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column user_certification.end_date
     *
     * @param endDate the value for user_certification.end_date
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column user_certification.note
     *
     * @return the value of user_certification.note
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column user_certification.note
     *
     * @param note the value for user_certification.note
     *
     * @ibatorgenerated Fri Feb 12 23:38:37 CST 2010
     */
    public void setNote(String note) {
        this.note = note;
    }
}